/*
 * This file is part of the Money package.
 *
 * Copyright (c) Eriksen Costa <eriksencosta@gmail.com>
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

/*
 * This file was auto-generated by running the "generateCryptoCurrenciesDataClasses" Gradle task. Always run the
 * task after a DTI database update.
 */

package com.eriksencosta.money.currency.crypto.data

import com.eriksencosta.money.currency.CurrencyData

// 50 currencies
@Suppress("MagicNumber", "MaxLineLength", "StringLiteralDuplication")
internal class CurrenciesData8 {
    val currencies: Map<String, CurrencyData> get() = mapOf(
        "58C8BG58J" to CurrencyData("58C8BG58J", "SUSHI", "SushiSwap", "SUSHI", "AUXILIARY", 18),
        "593KCRB2C" to CurrencyData("593KCRB2C", "SPGK", "AFREUM STABLE PGK", "SPGK", "AUXILIARY", 7),
        "593TDR8N7" to CurrencyData("593TDR8N7", "wNXM", "Wrapped NXM", "wNXM", "AUXILIARY", 18),
        "597MD9D5R" to CurrencyData("597MD9D5R", "DOT", "axlDOT", "●", "AUXILIARY", 10),
        "59NQSVPXZ" to CurrencyData("59NQSVPXZ", "CVT", "CyberVeinToken", "CVT", "AUXILIARY", 18),
        "5C3LXSVX7" to CurrencyData("5C3LXSVX7", "ETHW", "EthereumPoW", "ETHW", "NATIVE", 18),
        "5CG7SRXM1" to CurrencyData("5CG7SRXM1", "WETHW", "Wrapped ETHPoW", "WETHW", "AUXILIARY", 18),
        "5D2CZJLZN" to CurrencyData("5D2CZJLZN", "MEME", "Meow Of Meme", "MEME", "AUXILIARY", 6),
        "5DVN4L9S6" to CurrencyData("5DVN4L9S6", "UNI", "Uniswap", "UNI", "AUXILIARY", 18),
        "5F5HWZL9Z" to CurrencyData("5F5HWZL9Z", "NEAR", "NEAR", "NEAR", "AUXILIARY", 24),
        "5FPRKRKND" to CurrencyData("5FPRKRKND", "WETH", "Wrapped Ether", "WETH", "AUXILIARY", 6),
        "5FWBQM4QC" to CurrencyData("5FWBQM4QC", "ELON", "Dogelon Mars", "ELON", "AUXILIARY", 18),
        "5FWDV3WTT" to CurrencyData("5FWDV3WTT", "FUSE", "Fuse", "FUSE", "NATIVE", 8),
        "5G5BFWDJP" to CurrencyData("5G5BFWDJP", "CELR", "CelerToken", "CELR", "AUXILIARY", 18),
        "5GFDV98DG" to CurrencyData("5GFDV98DG", "EVMOS", "EVMOS", "EVMOS", "NATIVE", 8),
        "5HC9G053K" to CurrencyData("5HC9G053K", "ATM", "ATM", "ATM", "AUXILIARY", 1),
        "5HFS8PZMW" to CurrencyData("5HFS8PZMW", "KDA", "Kadena", "KDA", "NATIVE", 12),
        "5HRJP5G9J" to CurrencyData("5HRJP5G9J", "TLOS", "Telos", "TLOS", "NATIVE", 18),
        "5HS7NB85D" to CurrencyData("5HS7NB85D", "SMVR", "AFREUM STABLE MVR", "SMVR", "AUXILIARY", 7),
        "5K42Z9XZQ" to CurrencyData("5K42Z9XZQ", "USTC", "Terra Classic USD", "USTC", "AUXILIARY", 6),
        "5MHZGR5F9" to CurrencyData("5MHZGR5F9", "SUI", "GOATs of Sui", "SUI", "AUXILIARY", 6),
        "5MJ4CMDRL" to CurrencyData("5MJ4CMDRL", "DAI", "DogeZila Ai", "◈", "AUXILIARY", 18),
        "5MJBHM6D9" to CurrencyData("5MJBHM6D9", "ANPR", "AFREUM NPR", "ANPR", "AUXILIARY", 7),
        "5MNV1WP0H" to CurrencyData("5MNV1WP0H", "INV", "Inverse DAO", "INV", "AUXILIARY", 18),
        "5NJS4Q4FT" to CurrencyData("5NJS4Q4FT", "WAVES", "Waves", "WAVES", "NATIVE", 8),
        "5NRL14KDB" to CurrencyData("5NRL14KDB", "USDC", "USD Coin", "USDC", "AUXILIARY", 6),
        "5P47NQZNX" to CurrencyData("5P47NQZNX", "RDNT", "Radiant Capital", "RDNT", "AUXILIARY", 18),
        "5P5Z6CWBT" to CurrencyData("5P5Z6CWBT", "CVT", "CyberVeinToken", "CVT", "AUXILIARY", 18),
        "5PJ0X0P05" to CurrencyData("5PJ0X0P05", "FRGX", "FRGX", "FRGX", "AUXILIARY", 18),
        "5Q34Q72PJ" to CurrencyData("5Q34Q72PJ", "HOOK", "Hooked Protocol", "HOOK", "AUXILIARY", 18),
        "5QB9VPP18" to CurrencyData("5QB9VPP18", "WSB", "Wall Street Bets", "WSB", "AUXILIARY", 9),
        "5QFJKJ1J2" to CurrencyData("5QFJKJ1J2", "AAVE", "Aave", "AAVE", "AUXILIARY", 18),
        "5QW36BQK1" to CurrencyData("5QW36BQK1", "SMUR", "AFREUM STABLE MUR", "SMUR", "AUXILIARY", 7),
        "5QXDG9149" to CurrencyData("5QXDG9149", "MILK", "MILK", "MILK", "AUXILIARY", 0),
        "5R3XFPZSM" to CurrencyData("5R3XFPZSM", "USDC", "USD Coin", "USDC", "AUXILIARY", 6),
        "5R9M2H60G" to CurrencyData("5R9M2H60G", "USDC", "USD//C on xDai", "USDC", "AUXILIARY", 6),
        "5S4L884J9" to CurrencyData("5S4L884J9", "FTM", "Fantom", "FTM", "AUXILIARY", 18),
        "5SJ0BX93G" to CurrencyData("5SJ0BX93G", "USDC", "USD Coin", "USDC", "AUXILIARY", 6),
        "5TNK2PBMD" to CurrencyData("5TNK2PBMD", "BTC", "Satoshi Pumpomoto", "₿", "AUXILIARY", 9),
        "5TVKJ54NW" to CurrencyData("5TVKJ54NW", "FGC", "FantasyGold", "FGC", "AUXILIARY", 6),
        "5VNCFR2T5" to CurrencyData("5VNCFR2T5", "CRO", "Crypto.com Coin", "CRO", "AUXILIARY", 8),
        "5WTDXDVL2" to CurrencyData("5WTDXDVL2", "XEM", "NEM", "XEM", "NATIVE", 6),
        "5WW1M946Q" to CurrencyData("5WW1M946Q", "FIRO", "Firo", "FIRO", "AUXILIARY", 8),
        "5WXJ0MQZW" to CurrencyData("5WXJ0MQZW", "FRAX", "Frax", "FRAX", "AUXILIARY", 18),
        "5XB0LVT4G" to CurrencyData("5XB0LVT4G", "SNT", "Status Network Token", "SNT", "AUXILIARY", 18),
        "5XMDC8VG3" to CurrencyData("5XMDC8VG3", "PIXEL", "PixelVerse", "PIXEL", "AUXILIARY", 18),
        "5XVNTL2F4" to CurrencyData("5XVNTL2F4", "jWBTC", "Wrapped BTC", "jWBTC", "AUXILIARY", 8),
        "5Z31DKXJP" to CurrencyData("5Z31DKXJP", "HTX", "HTX", "HTX", "AUXILIARY", 18),
        "5ZNZH0CB2" to CurrencyData("5ZNZH0CB2", "DC", "Dogechain Token", "DC", "AUXILIARY", 18),
        "602XSM6GX" to CurrencyData("602XSM6GX", "OPT", "OptionFlowToken", "OPT", "AUXILIARY", 6),
    )
}
