/*
 * This file is part of the Money package.
 *
 * Copyright (c) Eriksen Costa <eriksencosta@gmail.com>
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

/*
 * This file was auto-generated by running the "generateCryptoCurrenciesDataClasses" Gradle task. Always run the
 * task after a DTI database update.
 */

package com.eriksencosta.money.currency.crypto.data

import com.eriksencosta.money.currency.CurrencyData

// 50 currencies
@Suppress("MagicNumber", "MaxLineLength", "StringLiteralDuplication")
internal class CurrenciesData29 {
    val currencies: Map<String, CurrencyData> get() = mapOf(
        "LHG7JSCRM" to CurrencyData("LHG7JSCRM", "USDT", "Tether USD", "₮", "AUXILIARY", 6),
        "LHJ7G3KXG" to CurrencyData("LHJ7G3KXG", "MATIC", "Matic", "MATIC", "AUXILIARY", 18),
        "LHLZHRH37" to CurrencyData("LHLZHRH37", "STC", "SaitaChain", "STC", "AUXILIARY", 9),
        "LHM0LH8BQ" to CurrencyData("LHM0LH8BQ", "BAND", "BandToken on xDai", "BAND", "AUXILIARY", 18),
        "LJ1PCCFGN" to CurrencyData("LJ1PCCFGN", "WBTC", "Wrapped BTC", "WBTC", "AUXILIARY", 8),
        "LJRS1XK59" to CurrencyData("LJRS1XK59", "CH1353258168", "World Bank/1.1575 Bd 20310611 Sr", "CH1353258168", "AUXILIARY", 0),
        "LK2DD49JM" to CurrencyData("LK2DD49JM", "WETH", "Wrapped Ether", "WETH", "AUXILIARY", 18),
        "LKG80JV60" to CurrencyData("LKG80JV60", "ZEN", "Horizen", "ZEN", "NATIVE", 8),
        "LKH3QWLGX" to CurrencyData("LKH3QWLGX", "ARPA", "ARPA Token", "ARPA", "AUXILIARY", 18),
        "LKHSNL59W" to CurrencyData("LKHSNL59W", "DAWN", "Dawn Protocol", "DAWN", "AUXILIARY", 18),
        "LKZ7QSC67" to CurrencyData("LKZ7QSC67", "YLDY", "Yieldly", "YLDY", "AUXILIARY", 18),
        "LLL3GN0S8" to CurrencyData("LLL3GN0S8", "BABBC", "Binance ABBC", "BABBC", "AUXILIARY", 8),
        "LLV8HGVBS" to CurrencyData("LLV8HGVBS", "APE", "ApeCoin", "APE", "AUXILIARY", 18),
        "LLVZM02K3" to CurrencyData("LLVZM02K3", "SUAH", "AFREUM STABLE UAH", "SUAH", "AUXILIARY", 7),
        "LM10WXF20" to CurrencyData("LM10WXF20", "FRONT", "Frontier", "FRONT", "AUXILIARY", 6),
        "LM15JXD5F" to CurrencyData("LM15JXD5F", "XEC", "eCash", "XEC", "AUXILIARY", 18),
        "LM4F7B48Z" to CurrencyData("LM4F7B48Z", "AVA", "Travala.com Token", "AVA", "AUXILIARY", 18),
        "LM4XRQVC6" to CurrencyData("LM4XRQVC6", "RUNE", "Rune", "RUNE", "AUXILIARY", 18),
        "LMH7N9DPB" to CurrencyData("LMH7N9DPB", "AXS", "Axie Infinity Shard", "AXS", "AUXILIARY", 18),
        "LN8H3FBKG" to CurrencyData("LN8H3FBKG", "BTT", "BitTeamToken", "BTT", "AUXILIARY", 18),
        "LN9B3VLC5" to CurrencyData("LN9B3VLC5", "FITFI", "Step", "FITFI", "NATIVE", 6),
        "LNBPTMXJL" to CurrencyData("LNBPTMXJL", "PIG", "Pigcoin", "PIG", "AUXILIARY", 18),
        "LNBTD9LN0" to CurrencyData("LNBTD9LN0", "PHB", "Phoenix Global", "PHB", "AUXILIARY", 18),
        "LNTLV89WS" to CurrencyData("LNTLV89WS", "WETH", "Wrapped Ether", "WETH", "AUXILIARY", 18),
        "LP0F0V50R" to CurrencyData("LP0F0V50R", "AKRO", "Akropolis", "AKRO", "AUXILIARY", 18),
        "LPKXFF66K" to CurrencyData("LPKXFF66K", "FIDA", "Bonfida", "FIDA", "AUXILIARY", 6),
        "LPPHF6K4C" to CurrencyData("LPPHF6K4C", "HNT", "Helium", "HNT", "NATIVE", 8),
        "LQ5NLKWNC" to CurrencyData("LQ5NLKWNC", "BTS", "BTStoken", "BTS", "AUXILIARY", 6),
        "LRR65QG7P" to CurrencyData("LRR65QG7P", "ATTD", "AFREUM TTD", "ATTD", "AUXILIARY", 7),
        "LS71LQK3L" to CurrencyData("LS71LQK3L", "USDC", "USD Coin", "USDC", "AUXILIARY", 6),
        "LSHS5Z3CZ" to CurrencyData("LSHS5Z3CZ", "ATOM", "Cosmos (PoS)", "ATOM", "AUXILIARY", 6),
        "LTD0L852N" to CurrencyData("LTD0L852N", "BUIDL", "BlackRock USD Institutional Digital Liquidity Fund", "BUIDL", "AUXILIARY", 6),
        "LTPBVZ2WN" to CurrencyData("LTPBVZ2WN", "ACVE", "AFREUM CVE", "ACVE", "AUXILIARY", 7),
        "LV8516WCR" to CurrencyData("LV8516WCR", "DODO", "DODO bird", "DODO", "AUXILIARY", 18),
        "LVX97LG0F" to CurrencyData("LVX97LG0F", "NEO", "NEO", "NEO", "AUXILIARY", 18),
        "LWKPW76T7" to CurrencyData("LWKPW76T7", "ETH", "Ether", "Ξ", "AUXILIARY", 18),
        "LXDL3LK6C" to CurrencyData("LXDL3LK6C", "REN", "Ren", "REN", "AUXILIARY", 18),
        "LXMPJ21BK" to CurrencyData("LXMPJ21BK", "BCH", "Bitcoin Cash", "Ƀ", "NATIVE", 18),
        "LZ5F4GJHT" to CurrencyData("LZ5F4GJHT", "SBOB", "AFREUM STABLE BOB", "SBOB", "AUXILIARY", 7),
        "LZ9TRNQXQ" to CurrencyData("LZ9TRNQXQ", "oUSDT", "Orbit Bridge Ton USD Tether", "oUSDT", "AUXILIARY", 6),
        "LZM81MGKJ" to CurrencyData("LZM81MGKJ", "BLOK", "BLOK", "BLOK", "AUXILIARY", 18),
        "M06FXVXKJ" to CurrencyData("M06FXVXKJ", "ASBD", "AFREUM SBD", "ASBD", "AUXILIARY", 7),
        "M0KTB2J79" to CurrencyData("M0KTB2J79", "SANG", "AFREUM STABLE ANG", "SANG", "AUXILIARY", 7),
        "M0NHKRD19" to CurrencyData("M0NHKRD19", "AMVR", "AFREUM MVR", "AMVR", "AUXILIARY", 7),
        "M0ZPLJJJR" to CurrencyData("M0ZPLJJJR", "YLDY", "Yieldly", "YLDY", "AUXILIARY", 6),
        "M175J0K8D" to CurrencyData("M175J0K8D", "SPELL", "Spell Token", "SPELL", "AUXILIARY", 8),
        "M1HZGSS0B" to CurrencyData("M1HZGSS0B", "SAWG", "AFREUM STABLE AWG", "SAWG", "AUXILIARY", 7),
        "M1KKL82QN" to CurrencyData("M1KKL82QN", "STC", "Satoshi Island Coin", "STC", "AUXILIARY", 18),
        "M1XZ3HVX3" to CurrencyData("M1XZ3HVX3", "FTM", "Fantom", "FTM", "AUXILIARY", 8),
        "M2GR9LKZ6" to CurrencyData("M2GR9LKZ6", "ETH", "Ethereum Token", "Ξ", "AUXILIARY", 18),
    )
}
