/*
 * This file is part of the Money package.
 *
 * Copyright (c) Eriksen Costa <eriksencosta@gmail.com>
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

/*
 * This file was auto-generated by running the "generateCryptoCurrenciesDataClasses" Gradle task. Always run the
 * task after a DTI database update.
 */

package com.eriksencosta.money.currency.crypto.data

// 50 currencies
@Suppress("StringLiteralDuplication")
internal class CurrenciesLookup11 {
    val currencies: Map<String, String> get() = mapOf(
        "QTF" to "7VLP56JZJ", // Quantfury Token available in CurrenciesData11
        "QTUM" to "VF6SNLQ0V", // Qtum available in CurrenciesData40
        "RAD" to "KMQC8Q056", // Radicle available in CurrenciesData27
        "RAI" to "6T4S0N42Z", // Rai Reflex Index available in CurrenciesData10
        "RARI" to "2Q90R9FDX", // Rarible available in CurrenciesData3
        "RBN" to "L7WHMH414", // Ribbon available in CurrenciesData28
        "RBTC" to "BNJBSRX1D", // Rootstock Smart Bitcoin available in CurrenciesData16
        "RCN" to "Z1Z34GC8C", // Ripio Credit Network Token available in CurrenciesData44
        "REP" to "20PR4FKVM", // Reputation available in CurrenciesData2
        "REPv2" to "G3XLSP4R8", // Reputation available in CurrenciesData21
        "REQ" to "JWSTTKP1H", // Request Token available in CurrenciesData26
        "REZ" to "12LDTQ14F", // Renzo available in CurrenciesData1
        "RFR" to "QXG6N01MP", // Refereum available in CurrenciesData35
        "RGT" to "4X6Z0FWJT", // Rari Governance Token available in CurrenciesData7
        "RIO" to "HMWPQK1GS", // Realio Network available in CurrenciesData24
        "RLC" to "3KFJPW473", // iEx.ec Network Token available in CurrenciesData5
        "ROA" to "R968F4K6R", // ROA CORE available in CurrenciesData36
        "RON" to "XTHCTZGX8", // Ronin available in CurrenciesData44
        "ROOK" to "L18GNGGX2", // ROOK available in CurrenciesData28
        "ROW" to "HKMCSJCKC", // RageOnWheels available in CurrenciesData23
        "RVN" to "Z5MQ912MD", // Ravencoin available in CurrenciesData45
        "S17A" to "3H704VXRJ", // TIGRIS IMMO/GENS 500 available in CurrenciesData5
        "SAED" to "SHJDMJKD1", // AFREUM STABLE AED available in CurrenciesData38
        "SAFE" to "VQQNZSQ1H", // Safe Token available in CurrenciesData41
        "SAFN" to "8WV98TJHC", // AFREUM STABLE AFN available in CurrenciesData13
        "SALL" to "1P1J34XQS", // AFREUM STABLE ALL available in CurrenciesData2
        "SAMD" to "NF3DZ3VNH", // AFREUM STABLE AMD available in CurrenciesData32
        "SANG" to "M0KTB2J79", // AFREUM STABLE ANG available in CurrenciesData29
        "SANTOS" to "53DCR7F4Z", // FC Santos Fan Token available in CurrenciesData7
        "SAOA" to "25ZSQKV32", // AFREUM STABLE AOA available in CurrenciesData2
        "SARS" to "GLL920C9G", // AFREUM STABLE ARS available in CurrenciesData22
        "SAUD" to "H196BL4DF", // AFREUM STABLE AUD available in CurrenciesData22
        "SAWG" to "M1HZGSS0B", // AFREUM STABLE AWG available in CurrenciesData29
        "SAZN" to "4R9LQBV39", // AFREUM STABLE AZN available in CurrenciesData7
        "SBAM" to "R6B1R112Q", // AFREUM STABLE BAM available in CurrenciesData36
        "SBBD" to "X9R8GS7R1", // AFREUM STABLE BBD available in CurrenciesData43
        "SBD" to "H2033SV4X", // Steem Dollars available in CurrenciesData22
        "SBDT" to "FD5DLL2SZ", // AFREUM STABLE BDT available in CurrenciesData20
        "SBGN" to "8VX5176BM", // AFREUM STABLE BGN available in CurrenciesData13
        "SBHD" to "XX3VQLJT0", // AFREUM STABLE BHD available in CurrenciesData44
        "SBIF" to "WVSG2WRVJ", // AFREUM STABLE BIF available in CurrenciesData43
        "SBMD" to "HPTPJJWC6", // AFREUM STABLE BMD available in CurrenciesData24
        "SBND" to "D3V3W2PX2", // AFREUM STABLE BND available in CurrenciesData18
        "SBOB" to "LZ5F4GJHT", // AFREUM STABLE BOB available in CurrenciesData29
        "SBRL" to "BD33N0T5G", // AFREUM STABLE BRL available in CurrenciesData15
        "SBSD" to "S5R7499GM", // AFREUM STABLE BSD available in CurrenciesData37
        "SBTN" to "W7XGXT546", // AFREUM STABLE BTN available in CurrenciesData41
        "SBWP" to "9CMNB37BQ", // AFREUM STABLE BWP available in CurrenciesData14
        "SBYN" to "CNBVJ1N7B", // AFREUM STABLE BYN available in CurrenciesData17
        "SBZD" to "D27DNZ98J", // AFREUM STABLE BZD available in CurrenciesData18
    )
}
