/*
 * This file is part of the Money package.
 *
 * Copyright (c) Eriksen Costa <eriksencosta@gmail.com>
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

/*
 * This file was auto-generated by running the "generateCryptoCurrenciesDataClasses" Gradle task. Always run the
 * task after a DTI database update.
 */

package com.eriksencosta.money.currency.crypto.data

import com.eriksencosta.money.currency.CurrencyData

// 50 currencies
@Suppress("MagicNumber", "MaxLineLength", "StringLiteralDuplication")
internal class CurrenciesData31 {
    val currencies: Map<String, CurrencyData> get() = mapOf(
        "MRWMZXF10" to CurrencyData("MRWMZXF10", "bcUSDT", "BlockNG-Peg USDT Token", "bcUSDT", "AUXILIARY", 18),
        "MSC61DVFZ" to CurrencyData("MSC61DVFZ", "DATA", "Streamr", "DATA", "AUXILIARY", 18),
        "MSCLXZQZZ" to CurrencyData("MSCLXZQZZ", "GCR", "GlobalCurrencyReserve", "GCR", "AUXILIARY", 6),
        "MSDC64X98" to CurrencyData("MSDC64X98", "WLD", "wLitiDAO", "WLD", "AUXILIARY", 18),
        "MSDLX4D4W" to CurrencyData("MSDLX4D4W", "META", "ABCMETA Token", "META", "AUXILIARY", 8),
        "MSSXHN2C8" to CurrencyData("MSSXHN2C8", "Titan", "TitanSwap", "Titan", "AUXILIARY", 18),
        "MSV03BRJW" to CurrencyData("MSV03BRJW", "MNTC", "Terra Classic MNT", "MNTC", "AUXILIARY", 6),
        "MTCJTRNZR" to CurrencyData("MTCJTRNZR", "ORAI", "Oraichain Token", "ORAI", "AUXILIARY", 18),
        "MVCDDN6Q2" to CurrencyData("MVCDDN6Q2", "AXL", "Axelar", "AXL", "AUXILIARY", 6),
        "MVG2CK8BD" to CurrencyData("MVG2CK8BD", "SHIB", "Shibaqua", "SHIB", "AUXILIARY", 18),
        "MVNS8ZS0X" to CurrencyData("MVNS8ZS0X", "JPTC", "Terra Classic JPY", "JPTC", "AUXILIARY", 6),
        "MWMRVLW3C" to CurrencyData("MWMRVLW3C", "FLZ", "Fellaz", "FLZ", "AUXILIARY", 18),
        "MWVTBGV5B" to CurrencyData("MWVTBGV5B", "DYDX", "dYdX", "DYDX", "AUXILIARY", 18),
        "MX24W9R15" to CurrencyData("MX24W9R15", "STJS", "AFREUM STABLE TJS", "STJS", "AUXILIARY", 7),
        "MXLJ762RF" to CurrencyData("MXLJ762RF", "KSM", "Kusama", "KSM", "NATIVE", 12),
        "MZ9J70K22" to CurrencyData("MZ9J70K22", "ABSD", "AFREUM BSD", "ABSD", "AUXILIARY", 7),
        "N018N3Q0Z" to CurrencyData("N018N3Q0Z", "GMT", "GreenMetaverseToken", "GMT", "AUXILIARY", 8),
        "N01MRH960" to CurrencyData("N01MRH960", "FET", "Fetch", "FET", "AUXILIARY", 18),
        "N19HT013T" to CurrencyData("N19HT013T", "TUSD", "TrueUSD", "TUSD", "AUXILIARY", 18),
        "N19T3PJ08" to CurrencyData("N19T3PJ08", "DIS", "DisChain", "DIS", "NATIVE", 18),
        "N25M0FSD8" to CurrencyData("N25M0FSD8", "LU2557886475", "EUROP.INVEST.BK/VAR BD 20250203", "LU2557886475", "PROVISIONAL", 0),
        "N25N2VFT7" to CurrencyData("N25N2VFT7", "QNT", "Quant", "QNT", "AUXILIARY", 18),
        "N2QHWFQNJ" to CurrencyData("N2QHWFQNJ", "NFT", "APENFT", "NFT", "AUXILIARY", 6),
        "N315XSJFS" to CurrencyData("N315XSJFS", "SCHF", "AFREUM STABLE CHF", "SCHF", "AUXILIARY", 7),
        "N3TLFXRZL" to CurrencyData("N3TLFXRZL", "DOT", "DOT", "●", "AUXILIARY", 10),
        "N47CZFR5B" to CurrencyData("N47CZFR5B", "ABOB", "AFREUM BOB", "ABOB", "AUXILIARY", 7),
        "N4L7B7NDJ" to CurrencyData("N4L7B7NDJ", "APE", "ApeCoin (PoS)", "APE", "AUXILIARY", 18),
        "N4V1RMPST" to CurrencyData("N4V1RMPST", "PEPE", "Pepe", "🐸︎", "AUXILIARY", 18),
        "N4ZHG2JLS" to CurrencyData("N4ZHG2JLS", "FXF", "Finxflo", "FXF", "AUXILIARY", 18),
        "N5V23LD36" to CurrencyData("N5V23LD36", "BUSD", "Binance USD", "BUSD", "AUXILIARY", 18),
        "N6KXWJRLD" to CurrencyData("N6KXWJRLD", "POWR", "PowerLedger", "POWR", "AUXILIARY", 6),
        "N6RVTJ7L0" to CurrencyData("N6RVTJ7L0", "XAUT", "XAUT", "XAUT", "AUXILIARY", 18),
        "N7165NQ94" to CurrencyData("N7165NQ94", "SUPER", "SuperFarm", "SUPER", "AUXILIARY", 18),
        "N747W1MJN" to CurrencyData("N747W1MJN", "AOA", "Aurora", "AOA", "AUXILIARY", 18),
        "N756VVZRC" to CurrencyData("N756VVZRC", "CRV", "Curve DAO Token", "CRV", "AUXILIARY", 8),
        "N76HBHRBS" to CurrencyData("N76HBHRBS", "USDT", "Tether", "₮", "AUXILIARY", 18),
        "N78FP3MD4" to CurrencyData("N78FP3MD4", "GEMS", "AlgoGems", "GEMS", "AUXILIARY", 6),
        "N7KDZ7X0F" to CurrencyData("N7KDZ7X0F", "NEO", "Neo", "NEO", "AUXILIARY", 0),
        "N7S814PB3" to CurrencyData("N7S814PB3", "USDT", "USDT@moonriver", "₮", "AUXILIARY", 6),
        "N82FX493S" to CurrencyData("N82FX493S", "TFUEL", "TFUEL", "TFUEL", "AUXILIARY", 4),
        "N86WQBNWK" to CurrencyData("N86WQBNWK", "1AXS", "Axie Infinity Shard", "1AXS", "AUXILIARY", 18),
        "N8J695HTD" to CurrencyData("N8J695HTD", "SHNL", "AFREUM STABLE HNL", "SHNL", "AUXILIARY", 7),
        "N8X51TRM5" to CurrencyData("N8X51TRM5", "ETH", "ETH via channel 0", "Ξ", "AUXILIARY", 18),
        "N9MN2LS4M" to CurrencyData("N9MN2LS4M", "CTX", "Cryptex", "CTX", "AUXILIARY", 18),
        "N9NW8G6MF" to CurrencyData("N9NW8G6MF", "HUNT", "HuntToken", "HUNT", "AUXILIARY", 18),
        "N9SBNKS9P" to CurrencyData("N9SBNKS9P", "TT-USDC", "TT-USDC", "TT-USDC", "AUXILIARY", 6),
        "N9TJVZ0C4" to CurrencyData("N9TJVZ0C4", "USDC", "wanUSDC", "USDC", "AUXILIARY", 6),
        "NB1RKT4SL" to CurrencyData("NB1RKT4SL", "SSCR", "AFREUM STABLE SCR", "SSCR", "AUXILIARY", 7),
        "NB40GCG21" to CurrencyData("NB40GCG21", "GPT", "QnA3.AI Token", "GPT", "AUXILIARY", 18),
        "NBM8KWVX6" to CurrencyData("NBM8KWVX6", "TT", "ETH-Peg Thunder Token", "TT", "AUXILIARY", 18),
    )
}
