/*
 * This file is part of the Money package.
 *
 * Copyright (c) Eriksen Costa <eriksencosta@gmail.com>
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

/*
 * This file was auto-generated by running the "generateCryptoCurrenciesDataClasses" Gradle task. Always run the
 * task after a DTI database update.
 */

package com.eriksencosta.money.currency.crypto.data

import com.eriksencosta.money.currency.CurrencyData

// 50 currencies
@Suppress("MagicNumber", "MaxLineLength", "StringLiteralDuplication")
internal class CurrenciesData11 {
    val currencies: Map<String, CurrencyData> get() = mapOf(
        "76F94LSWK" to CurrencyData("76F94LSWK", "TOMOE", "TomoChain", "TOMOE", "AUXILIARY", 18),
        "76X4NZXMD" to CurrencyData("76X4NZXMD", "DRGN", "Dragon", "DRGN", "AUXILIARY", 18),
        "7744P2WPH" to CurrencyData("7744P2WPH", "GRT", "Graph Token", "GRT", "AUXILIARY", 18),
        "775DWZF82" to CurrencyData("775DWZF82", "STEEM", "Steem", "ȿ", "AUXILIARY", 12),
        "77MKZP5F9" to CurrencyData("77MKZP5F9", "MAV", "Maverick Protocol", "MAV", "AUXILIARY", 18),
        "79F06FB14" to CurrencyData("79F06FB14", "CAKE", "PancakeSwap Token", "CAKE", "AUXILIARY", 18),
        "79GD8P0NK" to CurrencyData("79GD8P0NK", "SNX", "Synthetix Network Token", "SNX", "AUXILIARY", 18),
        "79PGMXP2J" to CurrencyData("79PGMXP2J", "G-CRE", "Gluwa Creditcoin Vesting Token", "G-CRE", "AUXILIARY", 18),
        "7BC6346Q2" to CurrencyData("7BC6346Q2", "vUSDC", "Venus USDC", "vUSDC", "AUXILIARY", 8),
        "7C0N41Q7D" to CurrencyData("7C0N41Q7D", "CH1142754337", "SIX Group/0.125 Bd 20261127 Sr", "CH1142754337", "AUXILIARY", 0),
        "7C3QV5V8P" to CurrencyData("7C3QV5V8P", "PYPL", "DAAG Certificat/Tracker Perp PYPL", "PYPL", "AUXILIARY", 8),
        "7CJ99308G" to CurrencyData("7CJ99308G", "SLP", "Smooth Love Potion", "SLP", "AUXILIARY", 0),
        "7CMGPDPPD" to CurrencyData("7CMGPDPPD", "AAVE", "Aave Token", "AAVE", "AUXILIARY", 18),
        "7D43KS1SD" to CurrencyData("7D43KS1SD", "BAL", "Balancer", "BAL", "AUXILIARY", 18),
        "7D68CDDQX" to CurrencyData("7D68CDDQX", "PAI", "Project Pai", "PAI", "NATIVE", 8),
        "7D7GLVKNB" to CurrencyData("7D7GLVKNB", "GAL", "Galatasaray S.K.", "GAL", "AUXILIARY", 0),
        "7DGW08CW7" to CurrencyData("7DGW08CW7", "sTETH", "stakedETH", "sTETH", "AUXILIARY", 18),
        "7DMWV9W6G" to CurrencyData("7DMWV9W6G", "TWT", "TwitFi Token", "TWT", "AUXILIARY", 9),
        "7F16CLJ2C" to CurrencyData("7F16CLJ2C", "ALBP", "AFREUM LBP", "ALBP", "AUXILIARY", 7),
        "7FMV5P1LR" to CurrencyData("7FMV5P1LR", "ICX", "ICON", "ICX", "NATIVE", 18),
        "7G3J24KP0" to CurrencyData("7G3J24KP0", "DAI", "Dai Stablecoin", "◈", "AUXILIARY", 18),
        "7GTNZH1VL" to CurrencyData("7GTNZH1VL", "ENS", "Ethereum Name Service", "ENS", "AUXILIARY", 18),
        "7HK3RP772" to CurrencyData("7HK3RP772", "ADOP", "AFREUM DOP", "ADOP", "AUXILIARY", 7),
        "7HTBVD0W5" to CurrencyData("7HTBVD0W5", "BNT", "Bancor Network Token on xDai", "BNT", "AUXILIARY", 18),
        "7HXK7GPNG" to CurrencyData("7HXK7GPNG", "MEME", "MEMETOON", "MEME", "AUXILIARY", 18),
        "7JLWRWP4B" to CurrencyData("7JLWRWP4B", "NXRA", "AllianceBlock Nexera Token", "NXRA", "AUXILIARY", 18),
        "7JMK1KK1R" to CurrencyData("7JMK1KK1R", "CH1306117073", "Canton of Zurich", "CH1306117073", "AUXILIARY", 0),
        "7K61W35NH" to CurrencyData("7K61W35NH", "1GBP", "poundtoken", "1GBP", "AUXILIARY", 18),
        "7KPJZ1DQ8" to CurrencyData("7KPJZ1DQ8", "UTK", "Utrust Token", "UTK", "AUXILIARY", 18),
        "7MKJXFW7V" to CurrencyData("7MKJXFW7V", "DINC", "Dinarcoin", "DINC", "AUXILIARY", 18),
        "7N4DZ9CSQ" to CurrencyData("7N4DZ9CSQ", "CEL", "Celsius", "CEL", "AUXILIARY", 4),
        "7NCQ6LHB3" to CurrencyData("7NCQ6LHB3", "bcUSDC", "BlockNG-Peg USDC Token", "bcUSDC", "AUXILIARY", 18),
        "7NG4RZ11N" to CurrencyData("7NG4RZ11N", "USDC", "USD Coin", "USDC", "AUXILIARY", 6),
        "7P7QV0K3R" to CurrencyData("7P7QV0K3R", "GALA", "Gala", "GALA", "AUXILIARY", 8),
        "7PDZ5890K" to CurrencyData("7PDZ5890K", "CHZ", "Chiliz", "CHZ", "NATIVE", 18),
        "7PG3L9G4F" to CurrencyData("7PG3L9G4F", "USDe", "USDe", "USDe", "AUXILIARY", 18),
        "7RQDPFX6D" to CurrencyData("7RQDPFX6D", "GOL", "GOGOLCOIN", "GOL", "AUXILIARY", 4),
        "7RRWRZ6VW" to CurrencyData("7RRWRZ6VW", "AGLD", "Adventure Gold", "AGLD", "AUXILIARY", 18),
        "7S6NLCJ58" to CurrencyData("7S6NLCJ58", "BAT", "Basic Attention Token", "BAT", "AUXILIARY", 8),
        "7SQFCF2L1" to CurrencyData("7SQFCF2L1", "SRON", "AFREUM STABLE RON", "SRON", "AUXILIARY", 7),
        "7STDR9ZL4" to CurrencyData("7STDR9ZL4", "SDKK", "AFREUM STABLE DKK", "SDKK", "AUXILIARY", 7),
        "7TDVLTNV7" to CurrencyData("7TDVLTNV7", "LRC", "LoopringCoin V2", "LRC", "AUXILIARY", 8),
        "7TPW2MLKJ" to CurrencyData("7TPW2MLKJ", "REN", "Ren", "REN", "AUXILIARY", 18),
        "7VLP56JZJ" to CurrencyData("7VLP56JZJ", "QTF", "Quantfury Token", "QTF", "AUXILIARY", 8),
        "7VTLKF0SP" to CurrencyData("7VTLKF0SP", "SKPW", "AFREUM STABLE KPW", "SKPW", "AUXILIARY", 7),
        "7VTRKSC7S" to CurrencyData("7VTRKSC7S", "XTZ", "Tezos", "ꜩ", "NATIVE", 6),
        "7W8TWSWKK" to CurrencyData("7W8TWSWKK", "SMWK", "AFREUM STABLE MWK", "SMWK", "AUXILIARY", 7),
        "7WCK2RVW2" to CurrencyData("7WCK2RVW2", "Cake", "PancakeSwap Token", "Cake", "AUXILIARY", 18),
        "7WLGNLN4P" to CurrencyData("7WLGNLN4P", "ERN", "@EthernityChain \$ERN Token", "ERN", "AUXILIARY", 18),
        "7WRD7TJGW" to CurrencyData("7WRD7TJGW", "ANAD", "AFREUM NAD", "ANAD", "AUXILIARY", 7),
    )
}
