/*
 * This file is part of the Money package.
 *
 * Copyright (c) Eriksen Costa <eriksencosta@gmail.com>
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

/*
 * This file was auto-generated by running the "generateCryptoCurrenciesDataClasses" Gradle task. Always run the
 * task after a DTI database update.
 */

package com.eriksencosta.money.currency.crypto.data

// 50 currencies
@Suppress("StringLiteralDuplication")
internal class CurrenciesLookup5 {
    val currencies: Map<String, String> get() = mapOf(
        "AZERO" to "3M5B4TQBT", // Aleph Zero available in CurrenciesData5
        "AZMW" to "QSXT5FM4C", // AFREUM ZMW available in CurrenciesData35
        "AZWL" to "KVJ1Q2SCM", // AFREUM ZWL available in CurrenciesData28
        "Amp" to "JQ7M3HRVP", // AMP available in CurrenciesData26
        "ApeX" to "NLP72SM8D", // ApexCoin available in CurrenciesData32
        "BABA" to "XWTXHV5ZR", // DAAG Certificat/Tracker Perp BABA available in CurrenciesData44
        "BABBC" to "LLL3GN0S8", // Binance ABBC available in CurrenciesData29
        "BADGER" to "NN2V3M4PW", // Badger available in CurrenciesData32
        "BAR" to "85PSZKCSZ", // FC Barcelona available in CurrenciesData12
        "BAT.e" to "JN0CW4MS7", // Basic Attention Token available in CurrenciesData25
        "BCD" to "JT74FJ4JX", // Bitcoin Diamond available in CurrenciesData26
        "BETH" to "RM9KPQ8MB", // Beacon ETH available in CurrenciesData37
        "BICO" to "74G0KS7GF", // Biconomy Token available in CurrenciesData10
        "BIGTIME" to "1K72DKCBK", // Big Time available in CurrenciesData1
        "BILI" to "LBL9J6X23", // DAAG Certificat/Tracker Perp BILI available in CurrenciesData28
        "BIX" to "P61HJW99N", // BIXToken available in CurrenciesData33
        "BLD" to "6JB14WNLK", // Agoric available in CurrenciesData9
        "BLUR" to "6Q08PZCBW", // Blur available in CurrenciesData10
        "BNB-bsc" to "WGK57QL5L", // Binance Coin available in CurrenciesData42
        "BNTX" to "PC3MG8CS1", // DAAG Certificat/Tracker Perp BNTX available in CurrenciesData33
        "BOME" to "G9S7R09HP", // BOOK OF MEME available in CurrenciesData21
        "BOND" to "R1L0DLSP1", // BarnBridge available in CurrenciesData36
        "BONE" to "4DN2C57B1", // Bone ShibaSwap available in CurrenciesData6
        "BORA" to "SHNX22R27", // BORA available in CurrenciesData38
        "BORG" to "B7J7BBMGQ", // SwissBorg Token available in CurrenciesData15
        "BOT" to "Z4LQD46FT", // BOT Token available in CurrenciesData45
        "BPD" to "CSFHC7KK7", // Beautiful Princess Disorder available in CurrenciesData18
        "BPTC" to "V1CW4WD3Z", // Business Platform Tomato Coin available in CurrenciesData40
        "BPWR" to "ZNFS8SRR3", // BLUE POWER/GENS 0.10 available in CurrenciesData45
        "BRISE" to "6QNZR6DZP", // Bitgert BRISE available in CurrenciesData10
        "BRKA" to "H60H15ZJZ", // DAAG Certificat/Tracker Perp BRK.A available in CurrenciesData23
        "BRZ" to "FGZCWWKCV", // BRZ Token available in CurrenciesData20
        "BSOL" to "K1C5K0V1S", // BlazeStake Staked SOL available in CurrenciesData26
        "BSV" to "2L8HS2MNP", // Bitcoin SV available in CurrenciesData3
        "BTC.b" to "NCK27Q8KL", // Bitcoin available in CurrenciesData32
        "BTSG" to "QNJTSSPHL", // BitSong available in CurrenciesData35
        "BUIDL" to "LTD0L852N", // BlackRock USD Institutional Digital Liquidity Fund available in CurrenciesData29
        "BURGER" to "1VF9BXDC5", // Burger Swap available in CurrenciesData2
        "BUSDet" to "FKXW411S0", // Binance USD available in CurrenciesData20
        "BYND" to "3KPN3MJG8", // DAAG Certificat/Tracker Perp BYND available in CurrenciesData5
        "BZX" to "CJ1ZBZ6RQ", // Bitcoin Zero available in CurrenciesData17
        "Bonk" to "89NNGP3K9", // Bonk available in CurrenciesData12
        "CANTO" to "VB1MQLJ23", // Canto available in CurrenciesData40
        "CBETH" to "GL9JJ4XJP", // Coinbase Wrapped Staked ETH available in CurrenciesData22
        "CCD" to "JXWZ7F8HD", // Concordium available in CurrenciesData26
        "CDAI" to "40KGHMPNB", // Compound Dai available in CurrenciesData5
        "CFX" to "3ZW8R4HSD", // Conflux available in CurrenciesData5
        "CGPT" to "8PM931M75", // ChainGPT available in CurrenciesData13
        "CH1142754337" to "7C0N41Q7D", // SIX Group/0.125 Bd 20261127 Sr available in CurrenciesData11
        "CH1199021903" to "XTNJ6KQGQ", // Tenity Group/RegSh CHF0.1 available in CurrenciesData44
    )
}
