/*
 * This file is part of the Money package.
 *
 * Copyright (c) Eriksen Costa <eriksencosta@gmail.com>
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

/*
 * This file was auto-generated by running the "generateCryptoCurrenciesDataClasses" Gradle task. Always run the
 * task after a DTI database update.
 */

package com.eriksencosta.money.currency.crypto.data

// 50 currencies
@Suppress("StringLiteralDuplication")
internal class CurrenciesLookup7 {
    val currencies: Map<String, String> get() = mapOf(
        "EUL" to "DRDR79Z38", // Euler available in CurrenciesData19
        "EURA" to "QWRDV8KCL", // Euro Electronic Money Token available in CurrenciesData35
        "EURC" to "FJM594L0V", // Euro Coin available in CurrenciesData20
        "EURR" to "G7ZDB1GZC", // StablR Euro available in CurrenciesData21
        "EURS" to "KVPVC7B5M", // STASIS EURS Token available in CurrenciesData28
        "EURX" to "6ZF4M9MTN", // Euro Cash Electronic Money Token available in CurrenciesData10
        "EURt7" to "W47GH5712", // LCX/7 Bd 20300201 Sub Unsec available in CurrenciesData41
        "EUTC" to "29DS3D8NL", // Terra Classic EUR available in CurrenciesData3
        "EWT" to "CJFQ69PKS", // Energy Web Token available in CurrenciesData17
        "EXFI" to "MJ5GFQF4P", // Experimental Finance Token available in CurrenciesData30
        "FABBC" to "PQ5GVJBH5", // Fantom ABBC available in CurrenciesData34
        "FARM" to "V6SHJRDFL", // FARM Reward Token available in CurrenciesData40
        "FCT" to "WL8WN1N51", // [FCT] FirmaChain Token available in CurrenciesData42
        "FIDA" to "LPKXFF66K", // Bonfida available in CurrenciesData29
        "FIRO" to "5WW1M946Q", // Firo available in CurrenciesData8
        "FIS" to "4K6P57CMJ", // StaFi available in CurrenciesData6
        "FLEX" to "50B1F4VSP", // FLEX Coin available in CurrenciesData7
        "FLOW" to "HFX40B3W9", // Flow available in CurrenciesData23
        "FLR" to "3KXTVG1Q5", // Flare available in CurrenciesData5
        "FLX" to "3WG9QL45B", // Flux Token available in CurrenciesData5
        "FLZ" to "MWMRVLW3C", // Fellaz available in CurrenciesData31
        "FOX" to "3PW25G3LN", // FOX available in CurrenciesData5
        "FR0014003521" to "WGHBLG826", // European Invest/Zero Cpn Bd available in CurrenciesData42
        "FRGX" to "5PJ0X0P05", // FRGX available in CurrenciesData8
        "FRP" to "WDW87KTD5", // FAME REWARD PLUS available in CurrenciesData42
        "FTN" to "202HP05GW", // Fasttoken available in CurrenciesData2
        "FUN" to "VLKQBB5L4", // FunFair available in CurrenciesData41
        "FUSE" to "5FWDV3WTT", // Fuse available in CurrenciesData8
        "FX" to "FHB7HH7LB", // Function X available in CurrenciesData20
        "Floki" to "DHC05Q331", // Baby Moon Floki available in CurrenciesData19
        "G-CRE" to "79PGMXP2J", // Gluwa Creditcoin Vesting Token available in CurrenciesData11
        "GBTC" to "1CQ8Z405P", // Terra Classic GBP available in CurrenciesData1
        "GCN" to "9BH267RHB", // Gascoin available in CurrenciesData14
        "GEMS" to "N78FP3MD4", // AlgoGems available in CurrenciesData31
        "GFI" to "4R8R6BMZW", // Goldfinch available in CurrenciesData7
        "GGP" to "P9KFC0FKC", // Geegoopuzzle available in CurrenciesData33
        "GLMR" to "B9T0TNB62", // Moonbeam available in CurrenciesData15
        "GLXY" to "M7SJDHNT0", // DAAG Certificat/Tracker Perp GLXY available in CurrenciesData30
        "GNS" to "M4CLDSDW7", // Gains Network available in CurrenciesData30
        "GNT" to "53DPPC0KF", // Golem Network Token available in CurrenciesData7
        "GODS" to "1CLCNMK9W", // Gods Unchained available in CurrenciesData1
        "GOOGL" to "ZH613B07W", // DAAG Certificat/Tracker Perp GOOGL available in CurrenciesData45
        "GPT" to "NB40GCG21", // QnA3.AI Token available in CurrenciesData31
        "GREBII" to "K71TQ0RHT", // GREENROCK EN/VAR BD OE available in CurrenciesData27
        "GRT.e" to "WGJSRNZGM", // Graph Token available in CurrenciesData42
        "GST" to "QGLWBD8RF", // GreenSatoshiToken available in CurrenciesData35
        "GTU" to "6PHT63VZJ", // Global Trade Unit available in CurrenciesData10
        "HAPI" to "1Z19CSSGT", // HAPI available in CurrenciesData2
        "HBCH" to "ML18MBJX2", // Heco-Peg HBCH Token available in CurrenciesData30
        "HBD" to "99XCCNBHW", // Hive Dollar available in CurrenciesData14
    )
}
