/*
 * This file is part of the Money package.
 *
 * Copyright (c) Eriksen Costa <eriksencosta@gmail.com>
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

/*
 * This file was auto-generated by running the "generateCryptoCurrenciesDataClasses" Gradle task. Always run the
 * task after a DTI database update.
 */

package com.eriksencosta.money.currency.crypto.data

import com.eriksencosta.money.currency.CurrencyData

// 50 currencies
@Suppress("MagicNumber", "MaxLineLength", "StringLiteralDuplication")
internal class CurrenciesData41 {
    val currencies: Map<String, CurrencyData> get() = mapOf(
        "VGNGZNRZN" to CurrencyData("VGNGZNRZN", "USDC", "USD Coin", "USDC", "AUXILIARY", 6),
        "VGSK822DJ" to CurrencyData("VGSK822DJ", "JST", "JUST", "JST", "AUXILIARY", 18),
        "VJD7G9T4F" to CurrencyData("VJD7G9T4F", "Metis", "Metis Token", "Metis", "AUXILIARY", 18),
        "VJHVRMWF8" to CurrencyData("VJHVRMWF8", "TT", "BSC-Peg Thunder Token", "TT", "AUXILIARY", 18),
        "VJVXNCJH1" to CurrencyData("VJVXNCJH1", "TEL", "Telcoin", "TEL", "AUXILIARY", 2),
        "VJXD9G4W7" to CurrencyData("VJXD9G4W7", "ENTC", "ENTERBUTTON", "ENTC", "AUXILIARY", 18),
        "VK0VS9V61" to CurrencyData("VK0VS9V61", "SCDF", "AFREUM STABLE CDF", "SCDF", "AUXILIARY", 7),
        "VKD9H47H5" to CurrencyData("VKD9H47H5", "NFT", "Neftipedia", "NFT", "AUXILIARY", 16),
        "VKJM0GHDH" to CurrencyData("VKJM0GHDH", "INJ", "Injective Protocol", "INJ", "AUXILIARY", 18),
        "VKL3V626J" to CurrencyData("VKL3V626J", "WBNB", "BNB", "WBNB", "AUXILIARY", 18),
        "VKNCKMZXB" to CurrencyData("VKNCKMZXB", "m.USDT", "USDT Token", "m.USDT", "AUXILIARY", 6),
        "VLKQBB5L4" to CurrencyData("VLKQBB5L4", "FUN", "FunFair", "FUN", "AUXILIARY", 8),
        "VM2QGSMP5" to CurrencyData("VM2QGSMP5", "ADZD", "AFREUM DZD", "ADZD", "AUXILIARY", 7),
        "VMZMZ6JRG" to CurrencyData("VMZMZ6JRG", "USDT", "Tether", "₮", "AUXILIARY", 6),
        "VNTV8K79H" to CurrencyData("VNTV8K79H", "PIXEL", "PixelVerse", "PIXEL", "AUXILIARY", 18),
        "VNX4XZ3VR" to CurrencyData("VNX4XZ3VR", "POLS", "PolkastarterToken", "POLS", "AUXILIARY", 18),
        "VPP7M4S3Z" to CurrencyData("VPP7M4S3Z", "DOGE", "SPACE DOGE", "Ð", "AUXILIARY", 9),
        "VQ98P9PRW" to CurrencyData("VQ98P9PRW", "WBNB", "Wrapped BNB", "WBNB", "AUXILIARY", 18),
        "VQQNZSQ1H" to CurrencyData("VQQNZSQ1H", "SAFE", "Safe Token", "SAFE", "AUXILIARY", 18),
        "VQZ5DNFQJ" to CurrencyData("VQZ5DNFQJ", "USDC", "USD Coin", "USDC", "AUXILIARY", 18),
        "VR0NQLSJK" to CurrencyData("VR0NQLSJK", "MDX", "MDX Token", "MDX", "AUXILIARY", 18),
        "VRDRXMC9G" to CurrencyData("VRDRXMC9G", "BLZ", "Bluzelle Token", "BLZ", "AUXILIARY", 18),
        "VRMZBD6ZQ" to CurrencyData("VRMZBD6ZQ", "WETH.e", "Wrapped Ether", "WETH.e", "AUXILIARY", 18),
        "VRN451371" to CurrencyData("VRN451371", "PEPE", "Pepe Coin", "🐸︎", "AUXILIARY", 18),
        "VS82ZDXTF" to CurrencyData("VS82ZDXTF", "INJ", "INJ", "INJ", "AUXILIARY", 18),
        "VS93QW822" to CurrencyData("VS93QW822", "HNT", "Helium", "HNT", "AUXILIARY", 8),
        "VT3TDFQDP" to CurrencyData("VT3TDFQDP", "RSR", "Reserve Rights", "RSR", "AUXILIARY", 8),
        "VTCDZS13K" to CurrencyData("VTCDZS13K", "ENA", "ENA", "ENA", "AUXILIARY", 18),
        "VTQD5DKT8" to CurrencyData("VTQD5DKT8", "VET", "VeChain", "VET", "AUXILIARY", 18),
        "VTSTB44FF" to CurrencyData("VTSTB44FF", "MATICet", "Matic", "MATICet", "AUXILIARY", 8),
        "VW1SKQ9LS" to CurrencyData("VW1SKQ9LS", "NIM", "Nimiq", "NIM", "NATIVE", 5),
        "VWH33C6Z8" to CurrencyData("VWH33C6Z8", "AXS", "Old Axie Infinity Shard", "AXS", "AUXILIARY", 18),
        "VXMMJV3SZ" to CurrencyData("VXMMJV3SZ", "LUNA", "LUNA", "LUNA", "AUXILIARY", 6),
        "VZCXR9VP5" to CurrencyData("VZCXR9VP5", "ACUP", "AFREUM CUP", "ACUP", "AUXILIARY", 7),
        "W02QK46X7" to CurrencyData("W02QK46X7", "DIS", "Disney", "DIS", "AUXILIARY", 18),
        "W03RCK39H" to CurrencyData("W03RCK39H", "ATOM", "Cosmos", "ATOM", "AUXILIARY", 6),
        "W087Q82PP" to CurrencyData("W087Q82PP", "AGBP", "AFREUM GBP", "AGBP", "AUXILIARY", 7),
        "W0GSHFPZB" to CurrencyData("W0GSHFPZB", "ETH", "Ether", "Ξ", "AUXILIARY", 8),
        "W0Q0045XW" to CurrencyData("W0Q0045XW", "MCO", "Monaco", "MCO", "AUXILIARY", 8),
        "W1C8WV1FJ" to CurrencyData("W1C8WV1FJ", "AARS", "AFREUM ARS", "AARS", "AUXILIARY", 7),
        "W1X6N0ZNR" to CurrencyData("W1X6N0ZNR", "BIT", "Biconomy Exchange Token", "BIT", "AUXILIARY", 9),
        "W47GH5712" to CurrencyData("W47GH5712", "EURt7", "LCX/7 Bd 20300201 Sub Unsec", "EURt7", "PROVISIONAL", 0),
        "W4W5CZQQ9" to CurrencyData("W4W5CZQQ9", "BCH", "Bitcoin Cash Token", "Ƀ", "AUXILIARY", 18),
        "W508F2SJ4" to CurrencyData("W508F2SJ4", "AFJD", "AFREUM FJD", "AFJD", "AUXILIARY", 7),
        "W5X0T8S6F" to CurrencyData("W5X0T8S6F", "PCI", "Paycoin", "PCI", "NATIVE", 8),
        "W6T647XQ9" to CurrencyData("W6T647XQ9", "AAVE", "Aave Token", "AAVE", "AUXILIARY", 18),
        "W7Q84JWVL" to CurrencyData("W7Q84JWVL", "ELF", "ELF Token", "ELF", "AUXILIARY", 18),
        "W7XGXT546" to CurrencyData("W7XGXT546", "SBTN", "AFREUM STABLE BTN", "SBTN", "AUXILIARY", 7),
        "W8RWVHXQQ" to CurrencyData("W8RWVHXQQ", "KLAY", "Klaytn", "KLAY", "AUXILIARY", 18),
        "W93DCQ5GP" to CurrencyData("W93DCQ5GP", "ELON", "Dogelon (PoS)", "ELON", "AUXILIARY", 18),
    )
}
