/*
 * This file is part of the Money package.
 *
 * Copyright (c) Eriksen Costa <eriksencosta@gmail.com>
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

/*
 * This file was auto-generated by running the "generateCryptoCurrenciesDataClasses" Gradle task. Always run the
 * task after a DTI database update.
 */

package com.eriksencosta.money.currency.crypto.data

import com.eriksencosta.money.currency.CurrencyData

// 50 currencies
@Suppress("MagicNumber", "MaxLineLength", "StringLiteralDuplication")
internal class CurrenciesData20 {
    val currencies: Map<String, CurrencyData> get() = mapOf(
        "F1CB20TJZ" to CurrencyData("F1CB20TJZ", "ioWBTC", "Wrapped Bitcoin", "ioWBTC", "AUXILIARY", 8),
        "F1WLWBHX9" to CurrencyData("F1WLWBHX9", "USDT", "Tether USD", "₮", "AUXILIARY", 6),
        "F276S59H1" to CurrencyData("F276S59H1", "USDK", "USDK", "USDK", "AUXILIARY", 18),
        "F27G6D5CK" to CurrencyData("F27G6D5CK", "HTX", "HTX", "HTX", "AUXILIARY", 18),
        "F2FP5N8RD" to CurrencyData("F2FP5N8RD", "XRP", "XRP", "✕", "AUXILIARY", 6),
        "F2N6WJ9S8" to CurrencyData("F2N6WJ9S8", "LCX", "LCX", "LCX", "AUXILIARY", 18),
        "F35VDQHVL" to CurrencyData("F35VDQHVL", "SOL", "Wrapped Solana", "◎", "AUXILIARY", 8),
        "F3H672QKB" to CurrencyData("F3H672QKB", "AAVE", "Aave (PoS)", "AAVE", "AUXILIARY", 18),
        "F3N8J48B5" to CurrencyData("F3N8J48B5", "USDC", "USD Coin", "USDC", "AUXILIARY", 6),
        "F3P6ZQX71" to CurrencyData("F3P6ZQX71", "MV", "Metaverse", "MV", "AUXILIARY", 18),
        "F4JQJLCFP" to CurrencyData("F4JQJLCFP", "TRB", "Tellor Tributes", "TRB", "AUXILIARY", 18),
        "F4NBSMG6L" to CurrencyData("F4NBSMG6L", "XVS", "Venus XVS", "XVS", "AUXILIARY", 18),
        "F55LF4D84" to CurrencyData("F55LF4D84", "CTXC", "Cortex", "CTXC", "NATIVE", 18),
        "F5BND751B" to CurrencyData("F5BND751B", "SPYG", "AFREUM STABLE PYG", "SPYG", "AUXILIARY", 7),
        "F5KPB426P" to CurrencyData("F5KPB426P", "ASVC", "AFREUM SVC", "ASVC", "AUXILIARY", 7),
        "F651T1H5G" to CurrencyData("F651T1H5G", "SKES", "AFREUM STABLE KES", "SKES", "AUXILIARY", 7),
        "F6RJF3JHM" to CurrencyData("F6RJF3JHM", "DAI", "Dai Stablecoin", "◈", "AUXILIARY", 18),
        "F6W5TF66L" to CurrencyData("F6W5TF66L", "MANA", "Decentraland MANA", "MANA", "AUXILIARY", 18),
        "F71L1V9DJ" to CurrencyData("F71L1V9DJ", "MYTH", "Mythos", "MYTH", "AUXILIARY", 18),
        "F776ZKLLG" to CurrencyData("F776ZKLLG", "SPELL", "Spell Token", "SPELL", "AUXILIARY", 18),
        "F8JXT234W" to CurrencyData("F8JXT234W", "ELF", "Aelf", "ELF", "NATIVE", 8),
        "FCH8D98XF" to CurrencyData("FCH8D98XF", "APE", "ApeMove Game Token", "APE", "AUXILIARY", 18),
        "FCLPJW014" to CurrencyData("FCLPJW014", "GMT", "GoMining Token", "GMT", "AUXILIARY", 18),
        "FD09MKPW4" to CurrencyData("FD09MKPW4", "XMI", "Microfi Free Flow", "XMI", "AUXILIARY", 2),
        "FD18NDNB3" to CurrencyData("FD18NDNB3", "BNB", "Binance Coin", "BNB", "AUXILIARY", 18),
        "FD58BBW01" to CurrencyData("FD58BBW01", "STG", "StargateToken", "STG", "AUXILIARY", 18),
        "FD5DLL2SZ" to CurrencyData("FD5DLL2SZ", "SBDT", "AFREUM STABLE BDT", "SBDT", "AUXILIARY", 7),
        "FDBG7XVCM" to CurrencyData("FDBG7XVCM", "BUSD", "BUSD Token", "BUSD", "AUXILIARY", 18),
        "FDGL5MD21" to CurrencyData("FDGL5MD21", "DNT", "district0x Network Token", "DNT", "AUXILIARY", 18),
        "FDKPL2KM8" to CurrencyData("FDKPL2KM8", "AAPL", "DAAG Certificat/Tracker Perp AAPL", "AAPL", "AUXILIARY", 8),
        "FF0QGWV85" to CurrencyData("FF0QGWV85", "PHA", "Phala", "PHA", "AUXILIARY", 18),
        "FF5C3VCJ2" to CurrencyData("FF5C3VCJ2", "LINK", "ChainLink Token", "LINK", "AUXILIARY", 18),
        "FG212WPJC" to CurrencyData("FG212WPJC", "MSFT", "DAAG Certificat/Tracker Perp MSFT", "MSFT", "AUXILIARY", 8),
        "FGRQJKW05" to CurrencyData("FGRQJKW05", "USDT", "USDt", "₮", "AUXILIARY", 6),
        "FGZCWWKCV" to CurrencyData("FGZCWWKCV", "BRZ", "BRZ Token", "BRZ", "AUXILIARY", 18),
        "FHB7HH7LB" to CurrencyData("FHB7HH7LB", "FX", "Function X", "FX", "AUXILIARY", 18),
        "FHJ2J54RT" to CurrencyData("FHJ2J54RT", "WLD", "Worldcoin", "WLD", "AUXILIARY", 18),
        "FHM6LZ4PM" to CurrencyData("FHM6LZ4PM", "MATIC", "Matic", "MATIC", "AUXILIARY", 18),
        "FJM594L0V" to CurrencyData("FJM594L0V", "EURC", "Euro Coin", "EURC", "AUXILIARY", 6),
        "FJZCFV5WJ" to CurrencyData("FJZCFV5WJ", "WE", "WeBuy", "WE", "AUXILIARY", 18),
        "FK0F23L2H" to CurrencyData("FK0F23L2H", "COMP", "Compound Coin", "COMP", "AUXILIARY", 18),
        "FKKWRNHCR" to CurrencyData("FKKWRNHCR", "BUSD", "Multichain BUSD", "BUSD", "AUXILIARY", 18),
        "FKXW411S0" to CurrencyData("FKXW411S0", "BUSDet", "Binance USD", "BUSDet", "AUXILIARY", 8),
        "FL9NF8SV6" to CurrencyData("FL9NF8SV6", "USDC", "USD Coin", "USDC", "AUXILIARY", 6),
        "FLQHLKTB1" to CurrencyData("FLQHLKTB1", "SRM", "Serum", "SRM", "AUXILIARY", 6),
        "FLVZ2X3S0" to CurrencyData("FLVZ2X3S0", "SUNOLD", "SUNOLD", "SUNOLD", "AUXILIARY", 18),
        "FN3FXVQ9V" to CurrencyData("FN3FXVQ9V", "ANKR", "Ankr Network", "ANKR", "AUXILIARY", 18),
        "FQQ4XZM98" to CurrencyData("FQQ4XZM98", "SSEK", "AFREUM STABLE SEK", "SSEK", "AUXILIARY", 7),
        "FR6786HH2" to CurrencyData("FR6786HH2", "SNZD", "AFREUM STABLE NZD", "SNZD", "AUXILIARY", 7),
        "FR9D0M141" to CurrencyData("FR9D0M141", "HT", "Huobi Token", "HT", "AUXILIARY", 18),
    )
}
