/*
 * This file is part of the Money package.
 *
 * Copyright (c) Eriksen Costa <eriksencosta@gmail.com>
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

/*
 * This file was auto-generated by running the "generateCryptoCurrenciesDataClasses" Gradle task. Always run the
 * task after a DTI database update.
 */

package com.eriksencosta.money.currency.crypto.data

import com.eriksencosta.money.currency.CurrencyData

// 9 currencies
@Suppress("MagicNumber", "MaxLineLength", "StringLiteralDuplication")
internal class CurrenciesData46 {
    val currencies: Map<String, CurrencyData> get() = mapOf(
        "ZTLVP2BW6" to CurrencyData("ZTLVP2BW6", "AEUR", "AFREUM EUR", "AEUR", "AUXILIARY", 7),
        "ZTQVQX1FF" to CurrencyData("ZTQVQX1FF", "USDT", "Tether USD", "₮", "AUXILIARY", 6),
        "ZVN4X2WTS" to CurrencyData("ZVN4X2WTS", "RAY", "Raydium (Wormhole)", "RAY", "AUXILIARY", 6),
        "ZW0RB0Z4C" to CurrencyData("ZW0RB0Z4C", "KCS", "KuCoin Token", "KCS", "AUXILIARY", 6),
        "ZW7LLPD42" to CurrencyData("ZW7LLPD42", "BNT", "Bancor", "BNT", "AUXILIARY", 8),
        "ZWLD1842T" to CurrencyData("ZWLD1842T", "YFI", "Heco-Peg YFI Token", "YFI", "AUXILIARY", 18),
        "ZX7463S7N" to CurrencyData("ZX7463S7N", "GUSD", "Gemini Dollar", "GUSD", "AUXILIARY", 2),
        "ZXMG7KV4S" to CurrencyData("ZXMG7KV4S", "DOGE", "DOGE SATELITTE INU", "Ð", "AUXILIARY", 9),
        "ZZLV65C4V" to CurrencyData("ZZLV65C4V", "EUROe", "EUROe Stablecoin", "EUROe", "AUXILIARY", 6),
    )
}
