/*
 * This file is part of the Money package.
 *
 * Copyright (c) Eriksen Costa <eriksencosta@gmail.com>
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

/*
 * This file was auto-generated by running the "generateCryptoCurrenciesDataClasses" Gradle task. Always run the
 * task after a DTI database update.
 */

package com.eriksencosta.money.currency.crypto.data

import com.eriksencosta.money.currency.CurrencyData

// 50 currencies
@Suppress("MagicNumber", "MaxLineLength", "StringLiteralDuplication")
internal class CurrenciesData4 {
    val currencies: Map<String, CurrencyData> get() = mapOf(
        "2T99BSRZP" to CurrencyData("2T99BSRZP", "DAI", "Dai Stablecoin", "◈", "AUXILIARY", 18),
        "2T9DV6S52" to CurrencyData("2T9DV6S52", "REN", "Republic Token", "REN", "AUXILIARY", 18),
        "2TK9S64GX" to CurrencyData("2TK9S64GX", "MXC", "MXC Token", "MXC", "AUXILIARY", 18),
        "2VDL03X13" to CurrencyData("2VDL03X13", "USDC", "USD Coin (Arb1)", "USDC", "AUXILIARY", 6),
        "2WH9XM311" to CurrencyData("2WH9XM311", "\$SOL", "Solidify", "\$SOL", "AUXILIARY", 9),
        "2XC43NWWH" to CurrencyData("2XC43NWWH", "stETH", "Lido Staked ETH", "stETH", "AUXILIARY", 8),
        "2XTW9RV1V" to CurrencyData("2XTW9RV1V", "AMRU", "AFREUM MRU", "AMRU", "AUXILIARY", 7),
        "2XVQCZ90M" to CurrencyData("2XVQCZ90M", "LEVER", "LeverFi", "LEVER", "AUXILIARY", 18),
        "2XX1FVGVH" to CurrencyData("2XX1FVGVH", "SHIB", "NicCageWaluigiElmo42069Inu", "SHIB", "AUXILIARY", 18),
        "2Z4XD1LDT" to CurrencyData("2Z4XD1LDT", "ARIX", "Arix", "ARIX", "AUXILIARY", 18),
        "2ZFH40KF6" to CurrencyData("2ZFH40KF6", "AAPL", "SwarmX/Struct Perp AAPL Sr", "AAPL", "AUXILIARY", 27),
        "2ZL0XS8CH" to CurrencyData("2ZL0XS8CH", "FRAX", "Frax", "FRAX", "AUXILIARY", 18),
        "2ZQ7BKBT1" to CurrencyData("2ZQ7BKBT1", "IOTX", "IoTeX Network (PoS)", "IOTX", "AUXILIARY", 18),
        "2ZTG3NNVB" to CurrencyData("2ZTG3NNVB", "USDC", "USDC", "USDC", "AUXILIARY", 6),
        "2ZWF6JZQK" to CurrencyData("2ZWF6JZQK", "ATZS", "AFREUM TZS", "ATZS", "AUXILIARY", 7),
        "30VMFSH1K" to CurrencyData("30VMFSH1K", "ASTR", "Astar", "ASTR", "NATIVE", 18),
        "31B5PN8TZ" to CurrencyData("31B5PN8TZ", "CORE", "cVault.finance", "CORE", "AUXILIARY", 18),
        "31J1K641M" to CurrencyData("31J1K641M", "MC", "Merit Circle", "MC", "AUXILIARY", 18),
        "31KJ5LJS6" to CurrencyData("31KJ5LJS6", "NFLX", "DAAG Certificat/Tracker Perp NFLX", "NFLX", "AUXILIARY", 8),
        "31SGMDGV4" to CurrencyData("31SGMDGV4", "GCR", "Global Currency Reserve", "GCR", "AUXILIARY", 18),
        "31VC5VD5F" to CurrencyData("31VC5VD5F", "MC", "Magic Crystal Coin", "MC", "AUXILIARY", 18),
        "32GWT7365" to CurrencyData("32GWT7365", "RARE", "RARE.UNIQUE", "RARE", "AUXILIARY", 18),
        "3360S7M85" to CurrencyData("3360S7M85", "MIM", "Magic Internet Money", "MIM", "AUXILIARY", 18),
        "349F5QPTN" to CurrencyData("349F5QPTN", "CYBER", "CyberConnect", "CYBER", "AUXILIARY", 18),
        "34DC1L78F" to CurrencyData("34DC1L78F", "wROSE", "Wrapped ROSE", "wROSE", "AUXILIARY", 18),
        "34FN0TL8K" to CurrencyData("34FN0TL8K", "ACDF", "AFREUM CDF", "ACDF", "AUXILIARY", 7),
        "34V259NQP" to CurrencyData("34V259NQP", "GAS", "Gas", "GAS", "AUXILIARY", 8),
        "354107NWV" to CurrencyData("354107NWV", "PEPE", "PEPEBSC", "🐸︎", "AUXILIARY", 9),
        "3555NMHK2" to CurrencyData("3555NMHK2", "AURORA", "Aurora", "AURORA", "NATIVE", 9),
        "35BSG6NKZ" to CurrencyData("35BSG6NKZ", "GOL", "Gogolcoin", "GOL", "AUXILIARY", 18),
        "35GRTLSHL" to CurrencyData("35GRTLSHL", "ZRX", "0x", "ZRX", "AUXILIARY", 18),
        "35S90PJVB" to CurrencyData("35S90PJVB", "AXAF", "AFREUM XAF", "AXAF", "AUXILIARY", 7),
        "35ZTMBQJX" to CurrencyData("35ZTMBQJX", "CPC", "CryptoPerformance Coin", "CPC", "NATIVE", 8),
        "36ZD0RH1T" to CurrencyData("36ZD0RH1T", "soSUSHI", "Wrapped SUSHI", "soSUSHI", "AUXILIARY", 6),
        "374KXLPZC" to CurrencyData("374KXLPZC", "DAI", "Dai Stablecoin", "◈", "AUXILIARY", 18),
        "37800ZHTJ" to CurrencyData("37800ZHTJ", "DAI", "(PoS) Dai Stablecoin", "◈", "AUXILIARY", 18),
        "379LQ80DD" to CurrencyData("379LQ80DD", "GNO", "Gnosis Token", "GNO", "AUXILIARY", 18),
        "37QP0NB0G" to CurrencyData("37QP0NB0G", "mSOL", "Marinade staked SOL (mSOL)", "mSOL", "AUXILIARY", 8),
        "381CX506V" to CurrencyData("381CX506V", "LTO", "LTO Network Token", "LTO", "AUXILIARY", 8),
        "38JSWB3MJ" to CurrencyData("38JSWB3MJ", "MEME", "MEME", "MEME", "AUXILIARY", 9),
        "38PVJ97TR" to CurrencyData("38PVJ97TR", "PICKLE", "PickleToken", "PICKLE", "AUXILIARY", 18),
        "393P69V6L" to CurrencyData("393P69V6L", "TUSD", "TrueUSD", "TUSD", "AUXILIARY", 18),
        "3BMNB50NR" to CurrencyData("3BMNB50NR", "VCO", "VCOIN", "VCO", "AUXILIARY", 18),
        "3CQ4BBQP6" to CurrencyData("3CQ4BBQP6", "WBTC", "Wrapped BTC", "WBTC", "AUXILIARY", 8),
        "3CZ5GDN41" to CurrencyData("3CZ5GDN41", "CRV", "Curve DAO", "CRV", "AUXILIARY", 18),
        "3DBPM738H" to CurrencyData("3DBPM738H", "ETC", "Ethereum Classic", "ξ", "AUXILIARY", 18),
        "3DHMJ5Q02" to CurrencyData("3DHMJ5Q02", "ZEC", "Zcash", "ⓩ", "NATIVE", 8),
        "3DJ566NFC" to CurrencyData("3DJ566NFC", "CAKE", "PancakeSwap", "CAKE", "AUXILIARY", 18),
        "3DS2V393Z" to CurrencyData("3DS2V393Z", "ATA", "Automata", "ATA", "AUXILIARY", 18),
        "3FD6ZRHD2" to CurrencyData("3FD6ZRHD2", "ASM", "ASSEMBLE", "ASM", "AUXILIARY", 18),
    )
}
