/*
 * This file is part of the Money package.
 *
 * Copyright (c) Eriksen Costa <eriksencosta@gmail.com>
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

/*
 * This file was auto-generated by running the "generateCryptoCurrenciesDataClasses" Gradle task. Always run the
 * task after a DTI database update.
 */

package com.eriksencosta.money.currency.crypto.data

import com.eriksencosta.money.currency.CurrencyData

// 50 currencies
@Suppress("MagicNumber", "MaxLineLength", "StringLiteralDuplication")
internal class CurrenciesData3 {
    val currencies: Map<String, CurrencyData> get() = mapOf(
        "26W7JCWZJ" to CurrencyData("26W7JCWZJ", "LDO", "Lido DAO Token", "LDO", "AUXILIARY", 18),
        "270RTTFW4" to CurrencyData("270RTTFW4", "OMG", "OMG Network", "OMG", "AUXILIARY", 18),
        "272G7TDKT" to CurrencyData("272G7TDKT", "AI", "Any Inu", "AI", "AUXILIARY", 18),
        "272S7DF0W" to CurrencyData("272S7DF0W", "DC", "Dogechain", "DC", "NATIVE", 8),
        "27C4DKP95" to CurrencyData("27C4DKP95", "WBTC", "Wrapped BTC", "WBTC", "AUXILIARY", 8),
        "27D2R9CNZ" to CurrencyData("27D2R9CNZ", "TOMO", "Viction", "TOMO", "NATIVE", 18),
        "27F1572QG" to CurrencyData("27F1572QG", "SUI", "Salmonation", "SUI", "AUXILIARY", 9),
        "27K77QND5" to CurrencyData("27K77QND5", "FLUX", "Flux", "FLUX", "AUXILIARY", 8),
        "27P7ZPWXD" to CurrencyData("27P7ZPWXD", "UMA.e", "UMA Voting Token v1", "UMA.e", "AUXILIARY", 18),
        "291SG90B8" to CurrencyData("291SG90B8", "KNC", "Kyber Network Crystal v2", "KNC", "AUXILIARY", 18),
        "29DD3R2SH" to CurrencyData("29DD3R2SH", "USDt", "Tether USD", "USDt", "AUXILIARY", 6),
        "29DS3D8NL" to CurrencyData("29DS3D8NL", "EUTC", "Terra Classic EUR", "EUTC", "AUXILIARY", 6),
        "29L06QD8P" to CurrencyData("29L06QD8P", "RLY", "Rally", "RLY", "AUXILIARY", 18),
        "29Q4954QS" to CurrencyData("29Q4954QS", "GME", "GME", "GME", "AUXILIARY", 9),
        "2B5CMBJW4" to CurrencyData("2B5CMBJW4", "C98", "Coin98", "C98", "AUXILIARY", 18),
        "2B7D7PF38" to CurrencyData("2B7D7PF38", "INTC", "DAAG Certificat/Tracker Perp INTC", "INTC", "AUXILIARY", 8),
        "2CTQDCXM4" to CurrencyData("2CTQDCXM4", "WLD", "Worldcoin", "WLD", "AUXILIARY", 18),
        "2CW5FXC7D" to CurrencyData("2CW5FXC7D", "WBTC", "(PoS) Wrapped BTC", "WBTC", "AUXILIARY", 8),
        "2DD7ZVGS1" to CurrencyData("2DD7ZVGS1", "MICRO", "Micromines", "MICRO", "AUXILIARY", 18),
        "2DZDLPN38" to CurrencyData("2DZDLPN38", "NEST", "NEST", "NEST", "AUXILIARY", 18),
        "2F2CKN3JL" to CurrencyData("2F2CKN3JL", "USDT", "USDT", "₮", "AUXILIARY", 6),
        "2G7WSQQCW" to CurrencyData("2G7WSQQCW", "MRNA", "DAAG Certificat/Tracker Perp MRNA", "MRNA", "AUXILIARY", 8),
        "2GJ0TGPD4" to CurrencyData("2GJ0TGPD4", "LINA", "Linear Token", "LINA", "AUXILIARY", 18),
        "2GP2MR5J2" to CurrencyData("2GP2MR5J2", "SVUV", "AFREUM STABLE VUV", "SVUV", "AUXILIARY", 7),
        "2GZBGMP2B" to CurrencyData("2GZBGMP2B", "USDe", "USDe", "USDe", "AUXILIARY", 18),
        "2HMZP9M27" to CurrencyData("2HMZP9M27", "PAXG", "Paxos Gold", "PAXG", "AUXILIARY", 18),
        "2HSQ98ND1" to CurrencyData("2HSQ98ND1", "NEAR", "NEAR Protocol", "NEAR", "AUXILIARY", 18),
        "2HVK379MD" to CurrencyData("2HVK379MD", "LUNA", "Wrapped LUNA Token", "LUNA", "AUXILIARY", 18),
        "2JHZC7W6T" to CurrencyData("2JHZC7W6T", "NFT", "NFT Protocol", "NFT", "AUXILIARY", 18),
        "2KK4GQLD5" to CurrencyData("2KK4GQLD5", "SD", "Stader", "SD", "AUXILIARY", 18),
        "2L8HS2MNP" to CurrencyData("2L8HS2MNP", "BSV", "Bitcoin SV", "Ɓ", "NATIVE", 8),
        "2LK0CT1W7" to CurrencyData("2LK0CT1W7", "MANA", "Decentraland", "MANA", "AUXILIARY", 18),
        "2M6DTN24X" to CurrencyData("2M6DTN24X", "WBTC", "Wrapped BTC", "WBTC", "AUXILIARY", 8),
        "2MKVB7SL3" to CurrencyData("2MKVB7SL3", "LDO", "Lido DAO Token", "LDO", "AUXILIARY", 8),
        "2MPCC77C1" to CurrencyData("2MPCC77C1", "CRO", "Crypto.org Cronos", "CRO", "NATIVE", 18),
        "2NPXV2W1F" to CurrencyData("2NPXV2W1F", "USDT", "Tether USD", "₮", "AUXILIARY", 6),
        "2P12H9KMJ" to CurrencyData("2P12H9KMJ", "DE000A30V6H0", "SIEMENS AG/3.531 IHS 20240213 USEC", "DE000A30V6H0", "AUXILIARY", 0),
        "2P9XQ520V" to CurrencyData("2P9XQ520V", "ATND", "AFREUM TND", "ATND", "AUXILIARY", 7),
        "2PXKDC4JS" to CurrencyData("2PXKDC4JS", "WOO.e", "Wootrade Network", "WOO.e", "AUXILIARY", 18),
        "2Q90R9FDX" to CurrencyData("2Q90R9FDX", "RARI", "Rarible", "RARI", "AUXILIARY", 18),
        "2QRVCJRG3" to CurrencyData("2QRVCJRG3", "AVAX", "Avalanche", "AVAX", "AUXILIARY", 18),
        "2QWSBDMNC" to CurrencyData("2QWSBDMNC", "USDT", "Tether USD", "₮", "AUXILIARY", 6),
        "2R4P50FGT" to CurrencyData("2R4P50FGT", "USDC", "USD Coin", "USDC", "AUXILIARY", 6),
        "2R96G6BX3" to CurrencyData("2R96G6BX3", "STRK", "Strike Token", "STRK", "AUXILIARY", 18),
        "2RBJT2VHX" to CurrencyData("2RBJT2VHX", "WEMIX", "Wemix", "WEMIX", "NATIVE", 18),
        "2RJ2NRNJ5" to CurrencyData("2RJ2NRNJ5", "USDT", "Tether", "₮", "AUXILIARY", 6),
        "2RL6ZBC9X" to CurrencyData("2RL6ZBC9X", "AKN", "Akoin", "AKN", "AUXILIARY", 7),
        "2RSRS48G1" to CurrencyData("2RSRS48G1", "DBTK", "DigiBank DBTK Token", "DBTK", "AUXILIARY", 7),
        "2RZ13PHH3" to CurrencyData("2RZ13PHH3", "ATOM", "Cosmos", "ATOM", "AUXILIARY", 6),
        "2SS7R57NM" to CurrencyData("2SS7R57NM", "USDC", "USD Coin", "USDC", "AUXILIARY", 6),
    )
}
