/*
 * This file is part of the Money package.
 *
 * Copyright (c) Eriksen Costa <eriksencosta@gmail.com>
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

/*
 * This file was auto-generated by running the "generateCryptoCurrenciesDataClasses" Gradle task. Always run the
 * task after a DTI database update.
 */

package com.eriksencosta.money.currency.crypto.data

// 50 currencies
@Suppress("StringLiteralDuplication")
internal class CurrenciesLookup4 {
    val currencies: Map<String, String> get() = mapOf(
        "AR" to "JW7SD9THP", // Arweave available in CurrenciesData26
        "ARKM" to "DWMJLGVWT", // Arkham available in CurrenciesData19
        "ARON" to "Q3V25S3B4", // AFREUM RON available in CurrenciesData34
        "ARSD" to "X6W9V011P", // AFREUM RSD available in CurrenciesData43
        "ARUB" to "GT5SQH3RH", // AFREUM RUB available in CurrenciesData22
        "ARWF" to "4KLVBDC91", // AFREUM RWF available in CurrenciesData6
        "ASAR" to "XRFWMCKSC", // AFREUM SAR available in CurrenciesData44
        "ASBD" to "M06FXVXKJ", // AFREUM SBD available in CurrenciesData29
        "ASCR" to "J2DF28585", // AFREUM SCR available in CurrenciesData24
        "ASDG" to "R0J6G4H2B", // AFREUM SDG available in CurrenciesData36
        "ASEK" to "G55J0GJD5", // AFREUM SEK available in CurrenciesData21
        "ASGD" to "6L0JD0D8R", // AFREUM SGD available in CurrenciesData10
        "ASHP" to "WJP8PMDMP", // AFREUM SHP available in CurrenciesData42
        "ASLL" to "B9RZ02BZ2", // AFREUM SLL available in CurrenciesData15
        "ASM" to "3FD6ZRHD2", // ASSEMBLE available in CurrenciesData4
        "ASOS" to "R3ZWXLWVM", // AFREUM SOS available in CurrenciesData36
        "ASR" to "H5MHJKCMH", // AS Roma available in CurrenciesData23
        "ASRD" to "MBBT2V7TR", // AFREUM SRD available in CurrenciesData30
        "ASSP" to "JG7PX6WWX", // AFREUM SSP available in CurrenciesData25
        "ASTN" to "1WKKL84PQ", // AFREUM STN available in CurrenciesData2
        "ASTR" to "30VMFSH1K", // Astar available in CurrenciesData4
        "ASVC" to "F5KPB426P", // AFREUM SVC available in CurrenciesData20
        "ASYP" to "88TQ3KNMK", // AFREUM SYP available in CurrenciesData12
        "ASZL" to "CRVMRGQTS", // AFREUM SZL available in CurrenciesData18
        "ATHB" to "KCZX82WNQ", // AFREUM THB available in CurrenciesData27
        "ATJS" to "3SVRKTB0B", // AFREUM TJS available in CurrenciesData5
        "ATMT" to "J9C7P7QVV", // AFREUM TMT available in CurrenciesData25
        "ATND" to "2P9XQ520V", // AFREUM TND available in CurrenciesData3
        "ATOP" to "G1S5FD4D4", // AFREUM TOP available in CurrenciesData21
        "ATRY" to "PL1B6SZMG", // AFREUM TRY available in CurrenciesData34
        "ATTD" to "LRR65QG7P", // AFREUM TTD available in CurrenciesData29
        "ATWD" to "55SKF2SQZ", // AFREUM TWD available in CurrenciesData7
        "ATZS" to "2ZWF6JZQK", // AFREUM TZS available in CurrenciesData4
        "AUAH" to "VB9SQC824", // AFREUM UAH available in CurrenciesData40
        "AUGX" to "XCZKWLQTV", // AFREUM UGX available in CurrenciesData43
        "AUSD" to "BX4T7CV08", // AFREUM USD available in CurrenciesData16
        "AUYU" to "15D12CMDR", // AFREUM UYU available in CurrenciesData1
        "AUZS" to "WZVKV5MVF", // AFREUM UZS available in CurrenciesData43
        "AVABBC" to "JVR2270H1", // Avalanche ABBC available in CurrenciesData26
        "AVES" to "DTMG0K77V", // AFREUM VES available in CurrenciesData19
        "AVND" to "JNF9M0TJG", // AFREUM VND available in CurrenciesData25
        "AVUV" to "PDQJHSXGM", // AFREUM VUV available in CurrenciesData33
        "AWST" to "S9Q3S18KN", // AFREUM WST available in CurrenciesData38
        "AXAF" to "35S90PJVB", // AFREUM XAF available in CurrenciesData4
        "AXCD" to "GG2FHST42", // AFREUM XCD available in CurrenciesData21
        "AXOF" to "559B8FFTR", // AFREUM XOF available in CurrenciesData7
        "AXPF" to "V0BT91RXZ", // AFREUM XPF available in CurrenciesData40
        "AXSet" to "C8R4L23ZB", // Axie Infinity Shard available in CurrenciesData17
        "AYER" to "NQ1R1BFTC", // AFREUM YER available in CurrenciesData32
        "AZAR" to "GZRMRLCD4", // AFREUM ZAR available in CurrenciesData22
    )
}
