/*
 * This file is part of the Money package.
 *
 * Copyright (c) Eriksen Costa <eriksencosta@gmail.com>
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

/*
 * This file was auto-generated by running the "generateCryptoCurrenciesDataClasses" Gradle task. Always run the
 * task after a DTI database update.
 */

package com.eriksencosta.money.currency.crypto.data

import com.eriksencosta.money.currency.CurrencyData

// 50 currencies
@Suppress("MagicNumber", "MaxLineLength", "StringLiteralDuplication")
internal class CurrenciesData19 {
    val currencies: Map<String, CurrencyData> get() = mapOf(
        "DCWNXSQQ2" to CurrencyData("DCWNXSQQ2", "ONGAS", "Ontology Gas", "ONGAS", "AUXILIARY", 9),
        "DDW2PVLH4" to CurrencyData("DDW2PVLH4", "APKR", "AFREUM PKR", "APKR", "AUXILIARY", 7),
        "DDWNJQZZH" to CurrencyData("DDWNJQZZH", "BUSD", "Binance USD", "BUSD", "AUXILIARY", 8),
        "DF7T6Z000" to CurrencyData("DF7T6Z000", "WEN", "Wen", "WEN", "AUXILIARY", 4),
        "DFCWWQ4F8" to CurrencyData("DFCWWQ4F8", "FTM", "Fantom Token", "FTM", "AUXILIARY", 18),
        "DG8313G8P" to CurrencyData("DG8313G8P", "WAN", "Wanchain", "WAN", "NATIVE", 18),
        "DG9TH5J85" to CurrencyData("DG9TH5J85", "SCZK", "AFREUM STABLE CZK", "SCZK", "AUXILIARY", 7),
        "DGSNLQPF8" to CurrencyData("DGSNLQPF8", "DFI", "DFI (DefiChain)", "DFI", "AUXILIARY", 18),
        "DHC05Q331" to CurrencyData("DHC05Q331", "Floki", "Baby Moon Floki", "Floki", "AUXILIARY", 9),
        "DHPZJQ579" to CurrencyData("DHPZJQ579", "USDT", "Tether", "₮", "AUXILIARY", 6),
        "DJ0QPRH0W" to CurrencyData("DJ0QPRH0W", "ATOM", "Cosmos", "ATOM", "AUXILIARY", 6),
        "DJB9ZPNZZ" to CurrencyData("DJB9ZPNZZ", "AERN", "AFREUM ERN", "AERN", "AUXILIARY", 7),
        "DKL80HPK3" to CurrencyData("DKL80HPK3", "BEAM", "Beam", "BEAM", "AUXILIARY", 18),
        "DKRZN4PQW" to CurrencyData("DKRZN4PQW", "AKT", "AKT", "AKT", "AUXILIARY", 6),
        "DKVK4XXQN" to CurrencyData("DKVK4XXQN", "LUNA", "LUNA (Wormhole)", "LUNA", "AUXILIARY", 6),
        "DLFDPGMTP" to CurrencyData("DLFDPGMTP", "TUSD", "TrueUSD", "TUSD", "AUXILIARY", 18),
        "DLKXXNKR7" to CurrencyData("DLKXXNKR7", "AKHR", "AFREUM KHR", "AKHR", "AUXILIARY", 7),
        "DLRCDV2P8" to CurrencyData("DLRCDV2P8", "NANO", "Nano", "NANO", "AUXILIARY", 10),
        "DM0QXMMJV" to CurrencyData("DM0QXMMJV", "GT", "GateChainToken", "GT", "AUXILIARY", 8),
        "DM37JHC2W" to CurrencyData("DM37JHC2W", "HUSD", "HUSD (Portal)", "HUSD", "AUXILIARY", 8),
        "DMRC79T0W" to CurrencyData("DMRC79T0W", "ALPHA", "AlphaToken", "ALPHA", "AUXILIARY", 18),
        "DMWC6TT9H" to CurrencyData("DMWC6TT9H", "LSK", "Lisk", "LSK", "AUXILIARY", 8),
        "DMXCFHSGP" to CurrencyData("DMXCFHSGP", "MAV", "Maverick Token", "MAV", "AUXILIARY", 18),
        "DNM47QNP7" to CurrencyData("DNM47QNP7", "JUP", "Jupiter", "JUP", "AUXILIARY", 18),
        "DPCXRM74X" to CurrencyData("DPCXRM74X", "USDC", "USDC (via Force Bridge from ETH)", "USDC", "AUXILIARY", 8),
        "DQG22RKCR" to CurrencyData("DQG22RKCR", "CRO", "Cronos", "CRO", "NATIVE", 18),
        "DQWGHC48L" to CurrencyData("DQWGHC48L", "LINK", "ChainLink", "LINK", "AUXILIARY", 18),
        "DRDR79Z38" to CurrencyData("DRDR79Z38", "EUL", "Euler", "EUL", "AUXILIARY", 18),
        "DSQSMG78K" to CurrencyData("DSQSMG78K", "POLY", "Polymath", "POLY", "AUXILIARY", 18),
        "DSRNXF5WH" to CurrencyData("DSRNXF5WH", "QRDO", "Qredo Token", "QRDO", "AUXILIARY", 8),
        "DT6XTG365" to CurrencyData("DT6XTG365", "FEI", "Fei USD", "FEI", "AUXILIARY", 18),
        "DTJP5FJRB" to CurrencyData("DTJP5FJRB", "AE", "Aeternity", "AE", "NATIVE", 18),
        "DTMG0K77V" to CurrencyData("DTMG0K77V", "AVES", "AFREUM VES", "AVES", "AUXILIARY", 7),
        "DTPJKFLST" to CurrencyData("DTPJKFLST", "AMUR", "AFREUM MUR", "AMUR", "AUXILIARY", 7),
        "DTXMP19ZC" to CurrencyData("DTXMP19ZC", "BTT", "BitTorrent-New", "BTT", "AUXILIARY", 18),
        "DV2JCPJ7P" to CurrencyData("DV2JCPJ7P", "FRAX", "Frax", "FRAX", "AUXILIARY", 18),
        "DVKQFFHGX" to CurrencyData("DVKQFFHGX", "KAVA", "Kava.io (PoS)", "KAVA", "AUXILIARY", 6),
        "DVX8H5C4G" to CurrencyData("DVX8H5C4G", "SNT", "Supernova Token", "SNT", "AUXILIARY", 18),
        "DW68N8X79" to CurrencyData("DW68N8X79", "ZBC", "Zebec", "ZBC", "AUXILIARY", 9),
        "DWBBXD2F1" to CurrencyData("DWBBXD2F1", "USDC", "USD Coin", "USDC", "AUXILIARY", 7),
        "DWLHPTD4M" to CurrencyData("DWLHPTD4M", "USDT", "Tether USD", "₮", "AUXILIARY", 6),
        "DWMJLGVWT" to CurrencyData("DWMJLGVWT", "ARKM", "Arkham", "ARKM", "AUXILIARY", 18),
        "DWR00Z22R" to CurrencyData("DWR00Z22R", "OP", "Optimism", "OP", "AUXILIARY", 18),
        "DXNJVNZC9" to CurrencyData("DXNJVNZC9", "COMP", "Compound on xDai", "COMP", "AUXILIARY", 18),
        "DXS7K41RV" to CurrencyData("DXS7K41RV", "XGLI", "Glitter Finance", "XGLI", "AUXILIARY", 6),
        "DZLGG7RRP" to CurrencyData("DZLGG7RRP", "SGHS", "AFREUM STABLE GHS", "SGHS", "AUXILIARY", 7),
        "F0CCCB311" to CurrencyData("F0CCCB311", "XDB", "digitalbits", "XDB", "AUXILIARY", 7),
        "F0ND861VB" to CurrencyData("F0ND861VB", "AETB", "AFREUM ETB", "AETB", "AUXILIARY", 7),
        "F0S5Q8B63" to CurrencyData("F0S5Q8B63", "SIRR", "AFREUM STABLE IRR", "SIRR", "AUXILIARY", 7),
        "F13T60SCG" to CurrencyData("F13T60SCG", "MTR", "Meter", "MTR", "NATIVE", 7),
    )
}
