/*
 * This file is part of the Money package.
 *
 * Copyright (c) Eriksen Costa <eriksencosta@gmail.com>
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

/*
 * This file was auto-generated by running the "generateCryptoCurrenciesDataClasses" Gradle task. Always run the
 * task after a DTI database update.
 */

package com.eriksencosta.money.currency.crypto.data

// 50 currencies
@Suppress("StringLiteralDuplication")
internal class CurrenciesLookup16 {
    val currencies: Map<String, String> get() = mapOf(
        "USDE" to "4HKZ20MN4", // USDe available in CurrenciesData6
        "USDK" to "F276S59H1", // USDK available in CurrenciesData20
        "USDL" to "52H4L48QZ", // Lift Dollar available in CurrenciesData7
        "USDM" to "NV703NKLG", // Mountain Protocol USD available in CurrenciesData33
        "USDT-PPT" to "HWD790TTS", // USDT Crosschain Token available in CurrenciesData24
        "USDT.e" to "G6P7GVF99", // Tether USD available in CurrenciesData21
        "USDT.eth" to "B4FKPN7PX", // Wrapped USDT from Ethereum on Meter available in CurrenciesData15
        "VCO" to "3BMNB50NR", // VCOIN available in CurrenciesData4
        "VITA" to "HZ2L1PBPC", // VitaDAO available in CurrenciesData24
        "VIVA" to "SZCSKG3ZQ", // Viva Classic available in CurrenciesData38
        "VLX" to "TZFBWN3DF", // Velas available in CurrenciesData40
        "VOW" to "JGGRD0Z4Z", // Vow available in CurrenciesData25
        "VOXEL" to "T54BNMRFN", // VOXEL Token available in CurrenciesData39
        "VRA" to "QR2PP5XM7", // Verasity available in CurrenciesData35
        "VXX" to "NCS9TPCC5", // DAAG Certificat/Tracker Perp VXX available in CurrenciesData32
        "WABBC" to "67J8SQKKZ", // Wrapped ABBC available in CurrenciesData9
        "WAN" to "DG8313G8P", // Wanchain available in CurrenciesData19
        "WAR" to "BNPZZNLSC", // Wrapped AR available in CurrenciesData16
        "WAXP" to "JGGW57FD9", // WAX available in CurrenciesData25
        "WBCD" to "RTHZBQTJ9", // Wrapped Bitcoin Diamond available in CurrenciesData37
        "WCFX" to "RTLD61D5C", // Wrapped Conflux available in CurrenciesData37
        "WE" to "FJZCFV5WJ", // WeBuy available in CurrenciesData20
        "WEN" to "DF7T6Z000", // Wen available in CurrenciesData19
        "WETC" to "99H118WXJ", // Wrapped Ether available in CurrenciesData14
        "WETH.e" to "VRMZBD6ZQ", // Wrapped Ether available in CurrenciesData41
        "WETH.eth" to "943FCHMV1", // Wrapped ETH from Ethereum available in CurrenciesData13
        "WETHW" to "5CG7SRXM1", // Wrapped ETHPoW available in CurrenciesData8
        "WFITFI" to "3HZXK2G14", // Wrapped FITFI available in CurrenciesData5
        "WFLOW" to "8H326R5DX", // Wrapped Flow available in CurrenciesData12
        "WHBAR" to "RFPL5QVVS", // Wrapped HBAR available in CurrenciesData36
        "WICC" to "XQ5HJF5DW", // Waykichain available in CurrenciesData44
        "WIF" to "R5M1NMD2C", // dogwifhat available in CurrenciesData36
        "WMOC" to "C86NWQC6Q", // Moss Coin available in CurrenciesData17
        "WOJAK" to "6GF6DF92W", // Wojak available in CurrenciesData9
        "WONE" to "QDLR9N7S8", // Wrapped ONE available in CurrenciesData35
        "WOO.e" to "2PXKDC4JS", // Wootrade Network available in CurrenciesData3
        "WPCI" to "CH3BZGW67", // Wrapped PCI available in CurrenciesData17
        "WPEPE" to "QTLVF7VNL", // Wrapped Pepe available in CurrenciesData35
        "WPLS" to "SV3F7VGHB", // Wrapped Pulse available in CurrenciesData38
        "WRON" to "RDNSXHDV3", // Wrapped Ronin available in CurrenciesData36
        "WSM" to "639Z2D54F", // Wall Street Memes available in CurrenciesData9
        "WTC" to "Z0JG8FVNC", // Walton Token available in CurrenciesData44
        "WTR" to "54QPBR5P3", // Water available in CurrenciesData7
        "WTRX" to "6PF7WDK49", // Wrapped TRX available in CurrenciesData10
        "WXMR" to "49C51J9T9", // Wrapped Monero available in CurrenciesData6
        "WZEN" to "TPFC3B3B9", // Wrapped ZEN available in CurrenciesData39
        "XCH" to "K40N9P386", // Chia available in CurrenciesData26
        "XCHF" to "T6MPXV0KP", // CryptoFranc available in CurrenciesData39
        "XDATA" to "Z5BDS3ZW4", // Streamr (old) available in CurrenciesData45
        "XDB" to "F0CCCB311", // digitalbits available in CurrenciesData19
    )
}
