/*
 * This file is part of the Money package.
 *
 * Copyright (c) Eriksen Costa <eriksencosta@gmail.com>
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

/*
 * This file was auto-generated by running the "generateCryptoCurrenciesDataClasses" Gradle task. Always run the
 * task after a DTI database update.
 */

package com.eriksencosta.money.currency.crypto.data

import com.eriksencosta.money.currency.CurrencyData
import com.eriksencosta.money.currency.UndefinedCurrencyData
import com.eriksencosta.money.currency.findByCode

@Suppress("CyclomaticComplexMethod")
internal object CurrenciesData {
    private val prioritizedCurrencies = CurrenciesData0().currencies

    fun of(code: String): CurrencyData = prioritizedCurrencies.getOrElse(code) {
        when (code) {
            in "10LJNZXHS".."1MKH0F6ZM" -> CurrenciesData1().currencies.findByCode(code)
            in "1ML8T1GJ6".."26DQ579GL" -> CurrenciesData2().currencies.findByCode(code)
            in "26W7JCWZJ".."2SS7R57NM" -> CurrenciesData3().currencies.findByCode(code)
            in "2T99BSRZP".."3FD6ZRHD2" -> CurrenciesData4().currencies.findByCode(code)
            in "3H20VHS4Z".."46J4RC83R" -> CurrenciesData5().currencies.findByCode(code)
            in "46LXHW242".."4PNL61HBD" -> CurrenciesData6().currencies.findByCode(code)
            in "4PWW9V7BT".."58537HRPB" -> CurrenciesData7().currencies.findByCode(code)
            in "58C8BG58J".."602XSM6GX" -> CurrenciesData8().currencies.findByCode(code)
            in "605NMSTKP".."6JB14WNLK" -> CurrenciesData9().currencies.findByCode(code)
            in "6KB4GFXG6".."75T0GP5WJ" -> CurrenciesData10().currencies.findByCode(code)
            in "76F94LSWK".."7WRD7TJGW" -> CurrenciesData11().currencies.findByCode(code)
            in "7X1XLVCB4".."8HTL22Z8Q" -> CurrenciesData12().currencies.findByCode(code)
            in "8JHVGRP3L".."986NQK6FQ" -> CurrenciesData13().currencies.findByCode(code)
            in "98MBBPTCK".."9V66W5M31" -> CurrenciesData14().currencies.findByCode(code)
            in "9V7055V26".."BG73J7X4V" -> CurrenciesData15().currencies.findByCode(code)
            in "BH3XPBG8V".."C36B1LTHB" -> CurrenciesData16().currencies.findByCode(code)
            in "C3K8KFV71".."CNNLQTXLJ" -> CurrenciesData17().currencies.findByCode(code)
            in "CP6817N4B".."DCLQGHB7K" -> CurrenciesData18().currencies.findByCode(code)
            in "DCWNXSQQ2".."F13T60SCG" -> CurrenciesData19().currencies.findByCode(code)
            in "F1CB20TJZ".."FR9D0M141" -> CurrenciesData20().currencies.findByCode(code)
            in "FRL4M33V1".."GH18F8X9K" -> CurrenciesData21().currencies.findByCode(code)
            in "GH19PKSH8".."H4N07FDCQ" -> CurrenciesData22().currencies.findByCode(code)
            in "H4WQ8DMKS".."HKMCSJCKC" -> CurrenciesData23().currencies.findByCode(code)
            in "HKWN2W8BB".."J3KTSDGXR" -> CurrenciesData24().currencies.findByCode(code)
            in "J3ZLNM7HL".."JNWL3D02V" -> CurrenciesData25().currencies.findByCode(code)
            in "JP07GJX2P".."K4QB4C4MJ" -> CurrenciesData26().currencies.findByCode(code)
            in "K4XQ9W83D".."KRC74D4T1" -> CurrenciesData27().currencies.findByCode(code)
            in "KRMN05SQP".."LHB3QXMB3" -> CurrenciesData28().currencies.findByCode(code)
            in "LHG7JSCRM".."M2GR9LKZ6" -> CurrenciesData29().currencies.findByCode(code)
            in "M2HHNHT0D".."MRT0NS181" -> CurrenciesData30().currencies.findByCode(code)
            in "MRWMZXF10".."NBM8KWVX6" -> CurrenciesData31().currencies.findByCode(code)
            in "NBVPDBTLB".."NV372F9Z9" -> CurrenciesData32().currencies.findByCode(code)
            in "NV703NKLG".."PKRTR3JHV" -> CurrenciesData33().currencies.findByCode(code)
            in "PL1B6SZMG".."QBLW2V2XS" -> CurrenciesData34().currencies.findByCode(code)
            in "QBM57R2TL".."QZ1MMQ934" -> CurrenciesData35().currencies.findByCode(code)
            in "QZF0Z87KP".."RKQK5M4KJ" -> CurrenciesData36().currencies.findByCode(code)
            in "RKZCT9KMH".."S8J06RVF2" -> CurrenciesData37().currencies.findByCode(code)
            in "S9Q3S18KN".."T4FV9055Q" -> CurrenciesData38().currencies.findByCode(code)
            in "T4J32WNT8".."TS0ZHWLV8" -> CurrenciesData39().currencies.findByCode(code)
            in "TS2347Z7N".."VGG0T9QTG" -> CurrenciesData40().currencies.findByCode(code)
            in "VGNGZNRZN".."W93DCQ5GP" -> CurrenciesData41().currencies.findByCode(code)
            in "WBQHCRVJ0".."WVBTKS08V" -> CurrenciesData42().currencies.findByCode(code)
            in "WVSG2WRVJ".."XKF87K8VJ" -> CurrenciesData43().currencies.findByCode(code)
            in "XKVJ62F6J".."Z4LCRP3TH" -> CurrenciesData44().currencies.findByCode(code)
            in "Z4LQD46FT".."ZTF814N3M" -> CurrenciesData45().currencies.findByCode(code)
            in "ZTLVP2BW6".."ZZLV65C4V" -> CurrenciesData46().currencies.findByCode(code)
            else -> UndefinedCurrencyData(code)
        }
    }
}
