/*
 * This file is part of the Money package.
 *
 * Copyright (c) Eriksen Costa <eriksencosta@gmail.com>
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

/*
 * This file was auto-generated by running the "generateCryptoCurrenciesDataClasses" Gradle task. Always run the
 * task after a DTI database update.
 */

package com.eriksencosta.money.currency.crypto.data

import com.eriksencosta.money.currency.findCodeBySecondaryCode

@Suppress("CyclomaticComplexMethod")
internal object CurrenciesLookup {
    private val prioritizedCurrencies = CurrenciesLookup0().currencies

    fun of(code: String): String = prioritizedCurrencies.getOrElse(code) {
        when (code) {
            in "\$HIB".."ACNY" -> CurrenciesLookup1().currencies.findCodeBySecondaryCode(code)
            in "ACOP".."AKN" -> CurrenciesLookup2().currencies.findCodeBySecondaryCode(code)
            in "AKPW".."AQAR" -> CurrenciesLookup3().currencies.findCodeBySecondaryCode(code)
            in "AR".."AZAR" -> CurrenciesLookup4().currencies.findCodeBySecondaryCode(code)
            in "AZERO".."CH1199021903" -> CurrenciesLookup5().currencies.findCodeBySecondaryCode(code)
            in "CH1228837865".."ETN" -> CurrenciesLookup6().currencies.findCodeBySecondaryCode(code)
            in "EUL".."HBD" -> CurrenciesLookup7().currencies.findCodeBySecondaryCode(code)
            in "HBSV".."LOKA" -> CurrenciesLookup8().currencies.findCodeBySecondaryCode(code)
            in "LOOKS".."NPXS" -> CurrenciesLookup9().currencies.findCodeBySecondaryCode(code)
            in "NU".."QSP" -> CurrenciesLookup10().currencies.findCodeBySecondaryCode(code)
            in "QTF".."SBZD" -> CurrenciesLookup11().currencies.findCodeBySecondaryCode(code)
            in "SCAD".."SJOD" -> CurrenciesLookup12().currencies.findCodeBySecondaryCode(code)
            in "SJPY".."SPKR" -> CurrenciesLookup13().currencies.findCodeBySecondaryCode(code)
            in "SPLN".."SWRV" -> CurrenciesLookup14().currencies.findCodeBySecondaryCode(code)
            in "SWST".."USDCLEGACY" -> CurrenciesLookup15().currencies.findCodeBySecondaryCode(code)
            in "USDE".."XDB" -> CurrenciesLookup16().currencies.findCodeBySecondaryCode(code)
            in "XDC".."pWING" -> CurrenciesLookup17().currencies.findCodeBySecondaryCode(code)
            in "pogai".."xDAI" -> CurrenciesLookup18().currencies.findCodeBySecondaryCode(code)
            else -> ""
        }
    }
}
