/*
 * This file is part of the Money package.
 *
 * Copyright (c) Eriksen Costa <eriksencosta@gmail.com>
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

/*
 * This file was auto-generated by running the "generateCryptoCurrenciesDataClasses" Gradle task. Always run the
 * task after a DTI database update.
 */

package com.eriksencosta.money.currency.crypto.data

import com.eriksencosta.money.currency.CurrencyData

// 50 currencies
@Suppress("MagicNumber", "MaxLineLength", "StringLiteralDuplication")
internal class CurrenciesData36 {
    val currencies: Map<String, CurrencyData> get() = mapOf(
        "QZF0Z87KP" to CurrencyData("QZF0Z87KP", "TRU", "Truebit", "TRU", "AUXILIARY", 18),
        "R0FRLCF38" to CurrencyData("R0FRLCF38", "ALICE", "My Neighbor Alice", "ALICE", "AUXILIARY", 6),
        "R0J6G4H2B" to CurrencyData("R0J6G4H2B", "ASDG", "AFREUM SDG", "ASDG", "AUXILIARY", 7),
        "R0K1ZBD7R" to CurrencyData("R0K1ZBD7R", "IOTX", "IoTeX Network", "IOTX", "AUXILIARY", 18),
        "R0NZLH529" to CurrencyData("R0NZLH529", "ALT", "Archloot", "ALT", "AUXILIARY", 18),
        "R157D2N9D" to CurrencyData("R157D2N9D", "SSVC", "AFREUM STABLE SVC", "SSVC", "AUXILIARY", 7),
        "R17WX951L" to CurrencyData("R17WX951L", "CREAM", "IceCream Finance", "CREAM", "AUXILIARY", 18),
        "R1D90QJKK" to CurrencyData("R1D90QJKK", "token-wstx", "Wrapped Stacks", "token-wstx", "AUXILIARY", 6),
        "R1DHBQJKZ" to CurrencyData("R1DHBQJKZ", "CYBER", "CyberConnect", "CYBER", "AUXILIARY", 18),
        "R1KHLJ2BS" to CurrencyData("R1KHLJ2BS", "AMDL", "AFREUM MDL", "AMDL", "AUXILIARY", 7),
        "R1L0DLSP1" to CurrencyData("R1L0DLSP1", "BOND", "BarnBridge", "BOND", "AUXILIARY", 18),
        "R231XLGMM" to CurrencyData("R231XLGMM", "ABYN", "AFREUM BYN", "ABYN", "AUXILIARY", 7),
        "R263M88WC" to CurrencyData("R263M88WC", "COMP", "Compound", "COMP", "AUXILIARY", 18),
        "R3ZWXLWVM" to CurrencyData("R3ZWXLWVM", "ASOS", "AFREUM SOS", "ASOS", "AUXILIARY", 7),
        "R4KJ7GZ0K" to CurrencyData("R4KJ7GZ0K", "REEF", "Reef.finance", "REEF", "AUXILIARY", 18),
        "R4QJQRQNJ" to CurrencyData("R4QJQRQNJ", "AKYD", "AFREUM KYD", "AKYD", "AUXILIARY", 7),
        "R4T9GLMTP" to CurrencyData("R4T9GLMTP", "WETH", "Ether", "WETH", "AUXILIARY", 18),
        "R5M1NMD2C" to CurrencyData("R5M1NMD2C", "WIF", "dogwifhat", "WIF", "AUXILIARY", 6),
        "R6B1R112Q" to CurrencyData("R6B1R112Q", "SBAM", "AFREUM STABLE BAM", "SBAM", "AUXILIARY", 7),
        "R6B7G5JGR" to CurrencyData("R6B7G5JGR", "WETH", "Ethereum", "WETH", "AUXILIARY", 18),
        "R6KK82R27" to CurrencyData("R6KK82R27", "ALT", "AltLayer Token", "ALT", "AUXILIARY", 18),
        "R7KG0MCC5" to CurrencyData("R7KG0MCC5", "ABAM", "AFREUM BAM", "ABAM", "AUXILIARY", 7),
        "R85C5SFP7" to CurrencyData("R85C5SFP7", "AGYD", "AFREUM GYD", "AGYD", "AUXILIARY", 7),
        "R8G3N2KJB" to CurrencyData("R8G3N2KJB", "AVAX", "Avalanche", "AVAX", "AUXILIARY", 18),
        "R968F4K6R" to CurrencyData("R968F4K6R", "ROA", "ROA CORE", "ROA", "AUXILIARY", 9),
        "R99MC2ZH4" to CurrencyData("R99MC2ZH4", "SVND", "AFREUM STABLE VND", "SVND", "AUXILIARY", 7),
        "R9LRZNL89" to CurrencyData("R9LRZNL89", "ONT", "Ontology Token", "ONT", "AUXILIARY", 18),
        "R9LX080HQ" to CurrencyData("R9LX080HQ", "AAVE", "Aave Token", "AAVE", "AUXILIARY", 18),
        "R9TSFJ27T" to CurrencyData("R9TSFJ27T", "IOST", "IOST", "IOST", "NATIVE", 8),
        "R9XGWTNKL" to CurrencyData("R9XGWTNKL", "CHSB", "SwissBorg Token", "CHSB", "AUXILIARY", 8),
        "RC24L83Q5" to CurrencyData("RC24L83Q5", "WETH", "Wrapped Ether", "WETH", "AUXILIARY", 18),
        "RC9WGGMXC" to CurrencyData("RC9WGGMXC", "jDAI", "Dai", "jDAI", "AUXILIARY", 18),
        "RCPCV18GL" to CurrencyData("RCPCV18GL", "LINA", "Linear Finance", "LINA", "AUXILIARY", 18),
        "RCRD3CKKT" to CurrencyData("RCRD3CKKT", "STX", "SynthetiX", "STX", "AUXILIARY", 9),
        "RD9R6Z6FM" to CurrencyData("RD9R6Z6FM", "CH1265890678", "Canton of Basel Stadt", "CH1265890678", "AUXILIARY", 0),
        "RDN206K23" to CurrencyData("RDN206K23", "TRAC", "Trace Token", "TRAC", "AUXILIARY", 18),
        "RDNSXHDV3" to CurrencyData("RDNSXHDV3", "WRON", "Wrapped Ronin", "WRON", "AUXILIARY", 18),
        "RF4V6BXGW" to CurrencyData("RF4V6BXGW", "USDP", "Pax Dollar", "USDP", "AUXILIARY", 18),
        "RFFL937SZ" to CurrencyData("RFFL937SZ", "FTT", "FTX Token", "FTT", "AUXILIARY", 8),
        "RFPL5QVVS" to CurrencyData("RFPL5QVVS", "WHBAR", "Wrapped HBAR", "WHBAR", "AUXILIARY", 8),
        "RFZ4DKGS4" to CurrencyData("RFZ4DKGS4", "ARB", "ARB Protocol", "ARB", "AUXILIARY", 6),
        "RG2BD9B0V" to CurrencyData("RG2BD9B0V", "GME", "DAAG Certificat/Tracker Perp GME", "GME", "AUXILIARY", 8),
        "RGF1L8C50" to CurrencyData("RGF1L8C50", "SXP", "Swipe", "SXP", "AUXILIARY", 18),
        "RGJMNNBSH" to CurrencyData("RGJMNNBSH", "CVP", "PowerPool", "CVP", "AUXILIARY", 18),
        "RH8F54RM6" to CurrencyData("RH8F54RM6", "EGLD", "MultiversX EGLD", "EGLD", "NATIVE", 18),
        "RHFH6BHNM" to CurrencyData("RHFH6BHNM", "CH1232107172", "Citta di Lugano/1.625 Bd 20290201", "CH1232107172", "AUXILIARY", 0),
        "RJLCSM3K2" to CurrencyData("RJLCSM3K2", "SFM", "SafeMoon", "SFM", "AUXILIARY", 9),
        "RK17NJRJP" to CurrencyData("RK17NJRJP", "LM", "LeisureMeta", "LM", "AUXILIARY", 18),
        "RKLZXFC87" to CurrencyData("RKLZXFC87", "DOGE", "ELON DOGE", "Ð", "AUXILIARY", 9),
        "RKQK5M4KJ" to CurrencyData("RKQK5M4KJ", "AMO", "AMO Coin", "AMO", "AUXILIARY", 18),
    )
}
