/*
 * This file is part of the Money package.
 *
 * Copyright (c) Eriksen Costa <eriksencosta@gmail.com>
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

/*
 * This file was auto-generated by running the "generateCryptoCurrenciesDataClasses" Gradle task. Always run the
 * task after a DTI database update.
 */

package com.eriksencosta.money.currency.crypto.data

import com.eriksencosta.money.currency.CurrencyData

// 50 currencies
@Suppress("MagicNumber", "MaxLineLength", "StringLiteralDuplication")
internal class CurrenciesData43 {
    val currencies: Map<String, CurrencyData> get() = mapOf(
        "WVSG2WRVJ" to CurrencyData("WVSG2WRVJ", "SBIF", "AFREUM STABLE BIF", "SBIF", "AUXILIARY", 7),
        "WW5P1MFF6" to CurrencyData("WW5P1MFF6", "WETH", "Wrapped Ether", "WETH", "AUXILIARY", 8),
        "WWJL4WXKN" to CurrencyData("WWJL4WXKN", "SHKD", "AFREUM STABLE HKD", "SHKD", "AUXILIARY", 7),
        "WX3CL76ZD" to CurrencyData("WX3CL76ZD", "BNT", "Bancor Network Token", "BNT", "AUXILIARY", 18),
        "WXM14KG32" to CurrencyData("WXM14KG32", "EVMOS", "EVMOS", "EVMOS", "AUXILIARY", 18),
        "WZGT1QT1K" to CurrencyData("WZGT1QT1K", "SYN", "Synapse", "SYN", "AUXILIARY", 18),
        "WZV5DWBN8" to CurrencyData("WZV5DWBN8", "BAND", "Band Protocol Token", "BAND", "AUXILIARY", 18),
        "WZVKV5MVF" to CurrencyData("WZVKV5MVF", "AUZS", "AFREUM UZS", "AUZS", "AUXILIARY", 7),
        "WZW1RJQNH" to CurrencyData("WZW1RJQNH", "BNB", "Binance", "BNB", "AUXILIARY", 18),
        "X042S97CT" to CurrencyData("X042S97CT", "PBR", "PolkaBridge", "PBR", "AUXILIARY", 18),
        "X0DNTHQ5L" to CurrencyData("X0DNTHQ5L", "SMGA", "AFREUM STABLE MGA", "SMGA", "AUXILIARY", 7),
        "X15WLXLTJ" to CurrencyData("X15WLXLTJ", "AMOP", "AFREUM MOP", "AMOP", "AUXILIARY", 7),
        "X1G2C294C" to CurrencyData("X1G2C294C", "SUPER", "SUPER-ERC20", "SUPER", "AUXILIARY", 18),
        "X1T3WM8CN" to CurrencyData("X1T3WM8CN", "USDC", "USD Coin", "USDC", "AUXILIARY", 6),
        "X2319Z02S" to CurrencyData("X2319Z02S", "LSK", "Lisk", "LSK", "NATIVE", 8),
        "X2JWTZP4D" to CurrencyData("X2JWTZP4D", "TRB", "Tellor", "TRB", "AUXILIARY", 18),
        "X2SKFZ8HS" to CurrencyData("X2SKFZ8HS", "EUROe", "EUROe Stablecoin", "EUROe", "AUXILIARY", 6),
        "X40KMGXMJ" to CurrencyData("X40KMGXMJ", "ACM", "AC Milan", "ACM", "AUXILIARY", 0),
        "X4BWZHCFX" to CurrencyData("X4BWZHCFX", "CRPT", "Crypterium", "CRPT", "AUXILIARY", 9),
        "X4CDSGRZK" to CurrencyData("X4CDSGRZK", "MANA", "Decentraland MANA on xDai", "MANA", "AUXILIARY", 18),
        "X5B92NG0R" to CurrencyData("X5B92NG0R", "AXL", "AXL", "AXL", "AUXILIARY", 6),
        "X61SH4DV8" to CurrencyData("X61SH4DV8", "POND", "Marlin POND", "POND", "AUXILIARY", 18),
        "X637KL2DZ" to CurrencyData("X637KL2DZ", "SUPER", "PeerMe", "SUPER", "AUXILIARY", 18),
        "X66RKJLT5" to CurrencyData("X66RKJLT5", "SNX", "Synthetix", "SNX", "AUXILIARY", 18),
        "X6TPRZQCP" to CurrencyData("X6TPRZQCP", "RNDR", "Render Token", "RNDR", "AUXILIARY", 18),
        "X6W9V011P" to CurrencyData("X6W9V011P", "ARSD", "AFREUM RSD", "ARSD", "AUXILIARY", 7),
        "X80TDN5SX" to CurrencyData("X80TDN5SX", "SKWD", "AFREUM STABLE KWD", "SKWD", "AUXILIARY", 7),
        "X82R2ZQC8" to CurrencyData("X82R2ZQC8", "cbETH", "Coinbase Wrapped Staked ETH", "cbETH", "AUXILIARY", 18),
        "X851DCW19" to CurrencyData("X851DCW19", "mADA", "Milkomeda C1", "mADA", "NATIVE", 15),
        "X8H3BH6V7" to CurrencyData("X8H3BH6V7", "MICRO", "Micromines", "MICRO", "AUXILIARY", 18),
        "X8N7P3B1M" to CurrencyData("X8N7P3B1M", "DAI", "Dai Stablecoin", "◈", "AUXILIARY", 18),
        "X9R8GS7R1" to CurrencyData("X9R8GS7R1", "SBBD", "AFREUM STABLE BBD", "SBBD", "AUXILIARY", 7),
        "X9VFJ4V65" to CurrencyData("X9VFJ4V65", "SNGN", "AFREUM STABLE NGN", "SNGN", "AUXILIARY", 7),
        "XB0MQJ1K5" to CurrencyData("XB0MQJ1K5", "HIGH", "Highstreet token", "HIGH", "AUXILIARY", 18),
        "XBM60NHWR" to CurrencyData("XBM60NHWR", "WBTC", "Wrapped BTC", "WBTC", "AUXILIARY", 8),
        "XC96DF5QG" to CurrencyData("XC96DF5QG", "TT", "Thunder Core", "TT", "NATIVE", 9),
        "XCKS7TCS3" to CurrencyData("XCKS7TCS3", "AI", "Any Inu", "AI", "AUXILIARY", 8),
        "XCQ4TZM6H" to CurrencyData("XCQ4TZM6H", "ATM", "Atletico De Madrid", "ATM", "AUXILIARY", 0),
        "XCZKWLQTV" to CurrencyData("XCZKWLQTV", "AUGX", "AFREUM UGX", "AUGX", "AUXILIARY", 7),
        "XD1LCN74F" to CurrencyData("XD1LCN74F", "LINK", "ChainLink Token", "LINK", "AUXILIARY", 18),
        "XD44HXHLT" to CurrencyData("XD44HXHLT", "USDT", "Tether USD", "₮", "AUXILIARY", 6),
        "XF936QSL4" to CurrencyData("XF936QSL4", "YGG", "Yield Guild Games Token", "YGG", "AUXILIARY", 18),
        "XFQDP0NMW" to CurrencyData("XFQDP0NMW", "USDC", "USD Coin", "USDC", "AUXILIARY", 6),
        "XG0CNRQ6P" to CurrencyData("XG0CNRQ6P", "ANIO", "AFREUM NIO", "ANIO", "AUXILIARY", 7),
        "XG3S0NSVG" to CurrencyData("XG3S0NSVG", "LOKA", "League of Kingdoms Arena", "LOKA", "AUXILIARY", 18),
        "XG60JPRQ8" to CurrencyData("XG60JPRQ8", "WIN", "WINkLink", "WIN", "AUXILIARY", 6),
        "XHKMM2P1P" to CurrencyData("XHKMM2P1P", "AURORA", "Aurora", "AURORA", "AUXILIARY", 18),
        "XJJVDPSK0" to CurrencyData("XJJVDPSK0", "OSMO", "OSMO", "OSMO", "AUXILIARY", 6),
        "XJZGRR954" to CurrencyData("XJZGRR954", "PEOPLE", "ConstitutionDAO", "PEOPLE", "AUXILIARY", 18),
        "XKF87K8VJ" to CurrencyData("XKF87K8VJ", "WOO", "Wootrade Network", "WOO", "AUXILIARY", 18),
    )
}
