/*
 * This file is part of the Money package.
 *
 * Copyright (c) Eriksen Costa <eriksencosta@gmail.com>
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

/*
 * This file was auto-generated by running the "generateCryptoCurrenciesDataClasses" Gradle task. Always run the
 * task after a DTI database update.
 */

package com.eriksencosta.money.currency.crypto.data

// 50 currencies
@Suppress("StringLiteralDuplication")
internal class CurrenciesLookup1 {
    val currencies: Map<String, String> get() = mapOf(
        "\$HIB" to "44SDQ6NX0", // SHIBA INU available in CurrenciesData5
        "\$MINA" to "54Q07XMTH", // MINA available in CurrenciesData7
        "\$MONG" to "BD3C0Z950", // MongCoin available in CurrenciesData15
        "\$SOL" to "2WH9XM311", // Solidify available in CurrenciesData4
        "1AXS" to "N86WQBNWK", // Axie Infinity Shard available in CurrenciesData31
        "1DAI" to "SV2TN9RGG", // Dai Stablecoin available in CurrenciesData38
        "1ETH" to "609V971PP", // ETH available in CurrenciesData9
        "1GBP" to "7K61W35NH", // poundtoken available in CurrenciesData11
        "1INCH.e" to "J7KQCG93W", // 1INCH Token available in CurrenciesData25
        "1ONE" to "9L10PQT5B", // Harmony ONE available in CurrenciesData14
        "1TRB" to "4KNVZ4G11", // Tellor Tributes available in CurrenciesData6
        "1USDC" to "L0SDJTMGX", // USD Coin available in CurrenciesData28
        "1USDT" to "H4WRM7576", // Tether USD available in CurrenciesData23
        "1WBTC" to "JMRDMZJ79", // Wrapped BTC available in CurrenciesData25
        "AAED" to "Q2ST0HB14", // AFREUM AED available in CurrenciesData34
        "AAFN" to "4DXMWBSFW", // AFREUM AFN available in CurrenciesData6
        "AALL" to "MPPKGK6LT", // AFREUM ALL available in CurrenciesData30
        "AAMD" to "KDNZDLDMP", // AFREUM AMD available in CurrenciesData27
        "AANG" to "HXF80XGRG", // AFREUM ANG available in CurrenciesData24
        "AAOA" to "4P3XPDRCK", // AFREUM AOA available in CurrenciesData6
        "AARS" to "W1C8WV1FJ", // AFREUM ARS available in CurrenciesData41
        "AAUD" to "WK2NPGFKC", // AFREUM AUD available in CurrenciesData42
        "AAWG" to "K940C51QC", // AFREUM AWG available in CurrenciesData27
        "AAZN" to "T1FDR8JWM", // AFREUM AZN available in CurrenciesData38
        "ABAM" to "R7KG0MCC5", // AFREUM BAM available in CurrenciesData36
        "ABBD" to "M54P10X8Q", // AFREUM BBD available in CurrenciesData30
        "ABC" to "B1H54F7WS", // DAAG Certificat/Tracker Perp ABC available in CurrenciesData15
        "ABDT" to "V23M4RT1K", // AFREUM BDT available in CurrenciesData40
        "ABGN" to "FSSDHV1GM", // AFREUM BGN available in CurrenciesData21
        "ABHD" to "GVPKZC9M6", // AFREUM BHD available in CurrenciesData22
        "ABIF" to "XQM2NVXC8", // AFREUM BIF available in CurrenciesData44
        "ABMD" to "HBFLG5WP5", // AFREUM BMD available in CurrenciesData23
        "ABNB" to "V71NNNTJZ", // DAAG Certificat/Tracker Perp ABNB available in CurrenciesData40
        "ABND" to "HTNP7JDH6", // AFREUM BND available in CurrenciesData24
        "ABOB" to "N47CZFR5B", // AFREUM BOB available in CurrenciesData31
        "ABRL" to "HHQKBGG5C", // AFREUM BRL available in CurrenciesData23
        "ABSD" to "MZ9J70K22", // AFREUM BSD available in CurrenciesData31
        "ABTN" to "WKZB29MBZ", // AFREUM BTN available in CurrenciesData42
        "ABWP" to "L8PVH70D0", // AFREUM BWP available in CurrenciesData28
        "ABYN" to "R231XLGMM", // AFREUM BYN available in CurrenciesData36
        "ABZD" to "Q8PG1VP4V", // AFREUM BZD available in CurrenciesData34
        "ACA" to "V6HT38SS8", // ACA Token available in CurrenciesData40
        "ACAD" to "TJ3JW9MSS", // AFREUM CAD available in CurrenciesData39
        "ACB" to "P5WWMTS41", // DAAG Certificat/Tracker Perp ACB available in CurrenciesData33
        "ACDF" to "34FN0TL8K", // AFREUM CDF available in CurrenciesData4
        "ACE" to "L9L5XQX5V", // ACEToken available in CurrenciesData28
        "ACHF" to "3JKNVJZ38", // AFREUM CHF available in CurrenciesData5
        "ACLP" to "PXSD2D57B", // AFREUM CLP available in CurrenciesData34
        "ACM" to "X40KMGXMJ", // AC Milan available in CurrenciesData43
        "ACNY" to "3JW30Z3MV", // AFREUM CNY available in CurrenciesData5
    )
}
