/*
 * This file is part of the Money package.
 *
 * Copyright (c) Eriksen Costa <eriksencosta@gmail.com>
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

/*
 * This file was auto-generated by running the "generateCryptoCurrenciesDataClasses" Gradle task. Always run the
 * task after a DTI database update.
 */

package com.eriksencosta.money.currency.crypto.data

import com.eriksencosta.money.currency.CurrencyData

// 50 currencies
@Suppress("MagicNumber", "MaxLineLength", "StringLiteralDuplication")
internal class CurrenciesData38 {
    val currencies: Map<String, CurrencyData> get() = mapOf(
        "S9Q3S18KN" to CurrencyData("S9Q3S18KN", "AWST", "AFREUM WST", "AWST", "AUXILIARY", 7),
        "S9QXPWW3V" to CurrencyData("S9QXPWW3V", "NOK", "DAAG Certificat/Tracker Perp NOK", "NOK", "AUXILIARY", 8),
        "SCGJ000V6" to CurrencyData("SCGJ000V6", "SJPY", "AFREUM STABLE JPY", "SJPY", "AUXILIARY", 7),
        "SCHGL48KC" to CurrencyData("SCHGL48KC", "BAT", "Basic Attention Token on xDai", "BAT", "AUXILIARY", 18),
        "SCRSVGNF0" to CurrencyData("SCRSVGNF0", "MIR", "Mirror", "MIR", "AUXILIARY", 6),
        "SD3T05550" to CurrencyData("SD3T05550", "BAT", "Basic Attention Token", "BAT", "AUXILIARY", 18),
        "SFHGMDSR5" to CurrencyData("SFHGMDSR5", "SINR", "AFREUM STABLE INR", "SINR", "AUXILIARY", 7),
        "SFPDRQ20W" to CurrencyData("SFPDRQ20W", "CHSB", "SwissBorg Token on xDai", "CHSB", "AUXILIARY", 8),
        "SHJDMJKD1" to CurrencyData("SHJDMJKD1", "SAED", "AFREUM STABLE AED", "SAED", "AUXILIARY", 7),
        "SHNX22R27" to CurrencyData("SHNX22R27", "BORA", "BORA", "BORA", "AUXILIARY", 18),
        "SJ1T9WHMM" to CurrencyData("SJ1T9WHMM", "ioETH", "Wrapped Ether", "ioETH", "AUXILIARY", 18),
        "SJ3RNWXFZ" to CurrencyData("SJ3RNWXFZ", "KRW", "Krown", "KRW", "AUXILIARY", 9),
        "SKPFT5GMM" to CurrencyData("SKPFT5GMM", "NUM", "NUM Token", "NUM", "AUXILIARY", 18),
        "SKQJ8Z2MJ" to CurrencyData("SKQJ8Z2MJ", "JUV", "Juventus", "JUV", "AUXILIARY", 0),
        "SL4HG6SPN" to CurrencyData("SL4HG6SPN", "CRV", "Curve DAO Token on xDai", "CRV", "AUXILIARY", 18),
        "SL73WHFTW" to CurrencyData("SL73WHFTW", "STMT", "AFREUM STABLE TMT", "STMT", "AUXILIARY", 7),
        "SLG4QQXJZ" to CurrencyData("SLG4QQXJZ", "ROSE", "ROSE", "ROSE", "AUXILIARY", 8),
        "SM7H7LS97" to CurrencyData("SM7H7LS97", "vUSDT", "Venus USDT", "vUSDT", "AUXILIARY", 8),
        "SM9PJ8SVS" to CurrencyData("SM9PJ8SVS", "COVAL", "CircuitsOfValue", "COVAL", "AUXILIARY", 8),
        "SMB9ZBCGN" to CurrencyData("SMB9ZBCGN", "APT", "Aptos", "APT", "AUXILIARY", 8),
        "SMKPML4NV" to CurrencyData("SMKPML4NV", "KCS", "KuCoin Token", "KCS", "NATIVE", 18),
        "SMX3M2FTZ" to CurrencyData("SMX3M2FTZ", "SNM", "SONM", "SNM", "AUXILIARY", 18),
        "SN607HQ8K" to CurrencyData("SN607HQ8K", "FORTH", "Ampleforth Governance", "FORTH", "AUXILIARY", 18),
        "SNXFH384V" to CurrencyData("SNXFH384V", "RARE", "SuperRare", "RARE", "AUXILIARY", 18),
        "SP4TK9V09" to CurrencyData("SP4TK9V09", "ETN", "Electroneum", "ETN", "NATIVE", 2),
        "SPMNCM9BT" to CurrencyData("SPMNCM9BT", "KISHIMOTO", "Kishimoto", "KISHIMOTO", "AUXILIARY", 9),
        "SPNQ3WKPH" to CurrencyData("SPNQ3WKPH", "SRM", "Serum", "SRM", "AUXILIARY", 6),
        "SQB8ZGMQR" to CurrencyData("SQB8ZGMQR", "SDZD", "AFREUM STABLE DZD", "SDZD", "AUXILIARY", 7),
        "SQWBQ78FT" to CurrencyData("SQWBQ78FT", "SLERF", "SLERF", "SLERF", "AUXILIARY", 9),
        "SRFC3M3BQ" to CurrencyData("SRFC3M3BQ", "USDe", "USDe", "USDe", "AUXILIARY", 18),
        "SRNJBLCPX" to CurrencyData("SRNJBLCPX", "XDCE", "XinFin XDCE", "XDCE", "AUXILIARY", 18),
        "SRW24S034" to CurrencyData("SRW24S034", "FRAX", "Frax", "FRAX", "AUXILIARY", 18),
        "ST2TSCVS5" to CurrencyData("ST2TSCVS5", "LINA", "Lina Network", "LINA", "AUXILIARY", 18),
        "ST76PJN2F" to CurrencyData("ST76PJN2F", "SRM", "Serum", "SRM", "AUXILIARY", 6),
        "STXDTB1ZW" to CurrencyData("STXDTB1ZW", "KAI", "Kardia Chain", "KAI", "NATIVE", 9),
        "SV2TN9RGG" to CurrencyData("SV2TN9RGG", "1DAI", "Dai Stablecoin", "1DAI", "AUXILIARY", 18),
        "SV3F7VGHB" to CurrencyData("SV3F7VGHB", "WPLS", "Wrapped Pulse", "WPLS", "AUXILIARY", 18),
        "SVVMMG3CC" to CurrencyData("SVVMMG3CC", "AI", "Any Inu", "AI", "AUXILIARY", 18),
        "SW2NXBK4D" to CurrencyData("SW2NXBK4D", "HIVE", "Hive", "HIVE", "AUXILIARY", 12),
        "SXWX4Q3KV" to CurrencyData("SXWX4Q3KV", "wROSE", "Wrapped ROSE", "wROSE", "AUXILIARY", 18),
        "SZCSKG3ZQ" to CurrencyData("SZCSKG3ZQ", "VIVA", "Viva Classic", "VIVA", "AUXILIARY", 9),
        "SZDV9MN5L" to CurrencyData("SZDV9MN5L", "SKMF", "AFREUM STABLE KMF", "SKMF", "AUXILIARY", 7),
        "T09PK5WL6" to CurrencyData("T09PK5WL6", "DAI", "Dai Stablecoin", "◈", "AUXILIARY", 18),
        "T0BJXLRC0" to CurrencyData("T0BJXLRC0", "BONK", "SUPER BONK", "BONK", "AUXILIARY", 9),
        "T0Z7P32CR" to CurrencyData("T0Z7P32CR", "SMYR", "AFREUM STABLE MYR", "SMYR", "AUXILIARY", 7),
        "T1FDR8JWM" to CurrencyData("T1FDR8JWM", "AAZN", "AFREUM AZN", "AAZN", "AUXILIARY", 7),
        "T35QJWGMX" to CurrencyData("T35QJWGMX", "BAL", "Heco-Peg BAL Token", "BAL", "AUXILIARY", 18),
        "T3BH60MPF" to CurrencyData("T3BH60MPF", "TWT", "Trust Wallet", "TWT", "AUXILIARY", 18),
        "T45DTMP9G" to CurrencyData("T45DTMP9G", "SNT", "Supernova Token", "SNT", "AUXILIARY", 18),
        "T4FV9055Q" to CurrencyData("T4FV9055Q", "BNB", "opBNB", "BNB", "NATIVE", 6),
    )
}
