/*
 * This file is part of the Money package.
 *
 * Copyright (c) Eriksen Costa <eriksencosta@gmail.com>
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

/*
 * This file was auto-generated by running the "generateCryptoCurrenciesDataClasses" Gradle task. Always run the
 * task after a DTI database update.
 */

package com.eriksencosta.money.currency.crypto.data

import com.eriksencosta.money.currency.CurrencyData

// 50 currencies
@Suppress("MagicNumber", "MaxLineLength", "StringLiteralDuplication")
internal class CurrenciesData5 {
    val currencies: Map<String, CurrencyData> get() = mapOf(
        "3H20VHS4Z" to CurrencyData("3H20VHS4Z", "SYN", "Synapse", "SYN", "AUXILIARY", 18),
        "3H704VXRJ" to CurrencyData("3H704VXRJ", "S17A", "TIGRIS IMMO/GENS 500", "S17A", "AUXILIARY", 0),
        "3H7N254SR" to CurrencyData("3H7N254SR", "tUSD", "Trusted USD", "tUSD", "AUXILIARY", 0),
        "3HXKB75DG" to CurrencyData("3HXKB75DG", "ALT", "Archloot", "ALT", "AUXILIARY", 18),
        "3HZXK2G14" to CurrencyData("3HZXK2G14", "WFITFI", "Wrapped FITFI", "WFITFI", "AUXILIARY", 18),
        "3J0FB8R16" to CurrencyData("3J0FB8R16", "YFI", "yearn.finance on xDai", "YFI", "AUXILIARY", 18),
        "3JKNVJZ38" to CurrencyData("3JKNVJZ38", "ACHF", "AFREUM CHF", "ACHF", "AUXILIARY", 7),
        "3JW30Z3MV" to CurrencyData("3JW30Z3MV", "ACNY", "AFREUM CNY", "ACNY", "AUXILIARY", 7),
        "3K7QKD9N8" to CurrencyData("3K7QKD9N8", "EDU", "Open Campus", "EDU", "AUXILIARY", 18),
        "3KFJPW473" to CurrencyData("3KFJPW473", "RLC", "iEx.ec Network Token", "RLC", "AUXILIARY", 9),
        "3KMQGXCWL" to CurrencyData("3KMQGXCWL", "jUSDC", "USD Coin", "jUSDC", "AUXILIARY", 6),
        "3KPN3MJG8" to CurrencyData("3KPN3MJG8", "BYND", "DAAG Certificat/Tracker Perp BYND", "BYND", "AUXILIARY", 8),
        "3KXTVG1Q5" to CurrencyData("3KXTVG1Q5", "FLR", "Flare", "FLR", "NATIVE", 18),
        "3LN0XMH8V" to CurrencyData("3LN0XMH8V", "KP3R", "Keep3rV1", "KP3R", "AUXILIARY", 8),
        "3LN7TVVTS" to CurrencyData("3LN7TVVTS", "WMATIC", "Wrapped Matic", "WMATIC", "AUXILIARY", 18),
        "3M09TZ9GS" to CurrencyData("3M09TZ9GS", "USDT", "Tether USD", "₮", "AUXILIARY", 6),
        "3M5B4TQBT" to CurrencyData("3M5B4TQBT", "AZERO", "Aleph Zero", "AZERO", "NATIVE", 12),
        "3MHSLZ3SX" to CurrencyData("3MHSLZ3SX", "SNAD", "AFREUM STABLE NAD", "SNAD", "AUXILIARY", 7),
        "3N4C4HF8D" to CurrencyData("3N4C4HF8D", "WETH", "Ether", "WETH", "AUXILIARY", 18),
        "3P79PSL71" to CurrencyData("3P79PSL71", "DRGN", "Dragonchain", "DRGN", "AUXILIARY", 9),
        "3PHS59CQR" to CurrencyData("3PHS59CQR", "USDT", "Multichain USDT", "₮", "AUXILIARY", 6),
        "3PW25G3LN" to CurrencyData("3PW25G3LN", "FOX", "FOX", "FOX", "AUXILIARY", 18),
        "3Q05VSFSK" to CurrencyData("3Q05VSFSK", "FRAX", "Frax", "FRAX", "AUXILIARY", 18),
        "3QGDL261W" to CurrencyData("3QGDL261W", "1INCH", "1INCH Token on xDai", "1INCH", "AUXILIARY", 18),
        "3RKMK45LQ" to CurrencyData("3RKMK45LQ", "RAY", "Raydium", "RAY", "AUXILIARY", 6),
        "3SVRKTB0B" to CurrencyData("3SVRKTB0B", "ATJS", "AFREUM TJS", "ATJS", "AUXILIARY", 7),
        "3SX33ZF5T" to CurrencyData("3SX33ZF5T", "DAR", "Dalarnia", "DAR", "AUXILIARY", 6),
        "3TMDQB6H2" to CurrencyData("3TMDQB6H2", "UST", "Wrapped UST Token", "UST", "AUXILIARY", 18),
        "3WCGMWKQM" to CurrencyData("3WCGMWKQM", "CH1319968462", "Citta di Lugano/1.415 Bd 20340307", "CH1319968462", "AUXILIARY", 0),
        "3WG9QL45B" to CurrencyData("3WG9QL45B", "FLX", "Flux Token", "FLX", "AUXILIARY", 18),
        "3XJQ6H2H8" to CurrencyData("3XJQ6H2H8", "SMXN", "AFREUM STABLE MXN", "SMXN", "AUXILIARY", 7),
        "3XXKVNWLW" to CurrencyData("3XXKVNWLW", "ARDR", "Ardor", "ARDR", "NATIVE", 8),
        "3ZP1Z5FM1" to CurrencyData("3ZP1Z5FM1", "sUSD", "Synth sUSD", "sUSD", "AUXILIARY", 18),
        "3ZP724GZS" to CurrencyData("3ZP724GZS", "ELA", "ELA on Ethereum", "ELA", "AUXILIARY", 18),
        "3ZW8R4HSD" to CurrencyData("3ZW8R4HSD", "CFX", "Conflux", "CFX", "NATIVE", 8),
        "40KGHMPNB" to CurrencyData("40KGHMPNB", "CDAI", "Compound Dai", "CDAI", "AUXILIARY", 8),
        "40PG5WNZN" to CurrencyData("40PG5WNZN", "POLA", "Polaris Share", "POLA", "AUXILIARY", 18),
        "415ZR3PP6" to CurrencyData("415ZR3PP6", "AKRO", "Akropolis", "AKRO", "AUXILIARY", 8),
        "41W3DC2R4" to CurrencyData("41W3DC2R4", "BUSD", "Binance USD", "BUSD", "AUXILIARY", 18),
        "41X0XL7NC" to CurrencyData("41X0XL7NC", "AOMR", "AFREUM OMR", "AOMR", "AUXILIARY", 7),
        "42HL692HW" to CurrencyData("42HL692HW", "SOMR", "AFREUM STABLE OMR", "SOMR", "AUXILIARY", 7),
        "43WK0G4MT" to CurrencyData("43WK0G4MT", "UNFI", "UNFI", "UNFI", "AUXILIARY", 18),
        "43ZFR0SQ6" to CurrencyData("43ZFR0SQ6", "SGBP", "AFREUM STABLE GBP", "SGBP", "AUXILIARY", 7),
        "44J786HSB" to CurrencyData("44J786HSB", "MASK", "Mask Network", "MASK", "AUXILIARY", 18),
        "44SDQ6NX0" to CurrencyData("44SDQ6NX0", "\$HIB", "SHIBA INU", "\$HIB", "AUXILIARY", 9),
        "45J3BLQQC" to CurrencyData("45J3BLQQC", "BAND", "Band", "BAND", "AUXILIARY", 18),
        "45J6XJX7H" to CurrencyData("45J6XJX7H", "USDC", "USD Coin", "USDC", "AUXILIARY", 6),
        "45PR013P3" to CurrencyData("45PR013P3", "SYN", "Synapse", "SYN", "AUXILIARY", 18),
        "45XFB3QZP" to CurrencyData("45XFB3QZP", "ONE", "Harmony", "ONE", "NATIVE", 18),
        "46J4RC83R" to CurrencyData("46J4RC83R", "TWT", "Trust Wallet", "TWT", "AUXILIARY", 8),
    )
}
