/*
 * This file is part of the Money package.
 *
 * Copyright (c) Eriksen Costa <eriksencosta@gmail.com>
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

/*
 * This file was auto-generated by running the "generateCryptoCurrenciesDataClasses" Gradle task. Always run the
 * task after a DTI database update.
 */

package com.eriksencosta.money.currency.crypto.data

// 50 currencies
@Suppress("StringLiteralDuplication")
internal class CurrenciesLookup10 {
    val currencies: Map<String, String> get() = mapOf(
        "NU" to "CPHVJTT11", // NuCypher available in CurrenciesData18
        "NUM" to "SKPFT5GMM", // NUM Token available in CurrenciesData38
        "NVDA" to "935N5X17W", // DAAG Certificat/Tracker Perp NVDA available in CurrenciesData13
        "NXRA" to "7JLWRWP4B", // AllianceBlock Nexera Token available in CurrenciesData11
        "OCEAN" to "K9NSZWF6J", // Ocean Token available in CurrenciesData27
        "OCT" to "S6TLXKRV9", // Octopus Network Token available in CurrenciesData37
        "OG" to "C6JQ8RKN5", // OG available in CurrenciesData17
        "OGN" to "58537HRPB", // OriginToken available in CurrenciesData7
        "OKT" to "72L4WS94B", // OKC Token available in CurrenciesData10
        "OMI" to "PXLZ7B5Q4", // OMI Token available in CurrenciesData34
        "ONDO" to "8DM439GVJ", // Ondo available in CurrenciesData12
        "ONG" to "52RQ0017K", // Ontology Gas available in CurrenciesData7
        "ONGAS" to "DCWNXSQQ2", // Ontology Gas available in CurrenciesData19
        "OOKI" to "S793VR9KV", // Ooki Token available in CurrenciesData37
        "OPT" to "602XSM6GX", // OptionFlowToken available in CurrenciesData8
        "ORAI" to "MTCJTRNZR", // Oraichain Token available in CurrenciesData31
        "ORBR" to "BDPL44QB2", // Orbler available in CurrenciesData15
        "ORCA" to "Z63372HJ5", // Orca available in CurrenciesData45
        "OXT" to "QD1L1XC82", // Orchid available in CurrenciesData35
        "PAI" to "7D68CDDQX", // Project Pai available in CurrenciesData11
        "PAX" to "QLRMVKR7K", // Paxos Standard available in CurrenciesData35
        "PCI" to "W5X0T8S6F", // Paycoin available in CurrenciesData41
        "PDT" to "H2WS5TW9R", // Paragons DAO Token available in CurrenciesData22
        "PENN" to "H6KSPR2ZV", // DAAG Certificat/Tracker Perp PENN available in CurrenciesData23
        "PEPE2.0" to "BTKVSX8GP", // Pepe 2.0 available in CurrenciesData16
        "PEPEBOMB" to "CTC433GV4", // pepe available in CurrenciesData18
        "PFE" to "WKQ2QXHT4", // DAAG Certificat/Tracker Perp PFE available in CurrenciesData42
        "PHA" to "FF0QGWV85", // Phala available in CurrenciesData20
        "PHB" to "LNBTD9LN0", // Phoenix Global available in CurrenciesData29
        "PICKLE" to "38PVJ97TR", // PickleToken available in CurrenciesData4
        "PIG" to "LNBPTMXJL", // Pigcoin available in CurrenciesData29
        "PIVX" to "903W19SSS", // PIVX available in CurrenciesData13
        "PNT" to "KDNJ1M5PQ", // pNetwork Token available in CurrenciesData27
        "POL" to "52M6VXQTD", // Polygon Ecosystem Token available in CurrenciesData7
        "POLA" to "40PG5WNZN", // Polaris Share available in CurrenciesData5
        "POLS" to "VNX4XZ3VR", // PolkastarterToken available in CurrenciesData41
        "POLY" to "DSQSMG78K", // Polymath available in CurrenciesData19
        "POPCAT" to "WCFP5ZBK5", // POPCAT available in CurrenciesData42
        "PORK" to "Z9L49GGRX", // PepeFork available in CurrenciesData45
        "PORTAL" to "TTRNBWRVR", // PORTAL available in CurrenciesData40
        "PORTO" to "BVFNTJFBM", // FC Porto Fan Token available in CurrenciesData16
        "POWR" to "N6KXWJRLD", // PowerLedger available in CurrenciesData31
        "PRQ" to "RZ43VKXQ0", // Parsiq Token available in CurrenciesData37
        "PUNDIX" to "NJVDLVNH7", // Pundi X Token available in CurrenciesData32
        "PYPL" to "7C3QV5V8P", // DAAG Certificat/Tracker Perp PYPL available in CurrenciesData11
        "PYTH" to "ZQHL971M3", // Pyth Network available in CurrenciesData45
        "Planets" to "HHD5KXJNR", // PLANET available in CurrenciesData23
        "QKC" to "2685VTQTR", // QuarkChain available in CurrenciesData2
        "QRDO" to "DSRNXF5WH", // Qredo Token available in CurrenciesData19
        "QSP" to "V5Z1G0H8C", // Quantstamp available in CurrenciesData40
    )
}
