/*
 * This file is part of the Money package.
 *
 * Copyright (c) Eriksen Costa <eriksencosta@gmail.com>
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

/*
 * This file was auto-generated by running the "generateCryptoCurrenciesDataClasses" Gradle task. Always run the
 * task after a DTI database update.
 */

package com.eriksencosta.money.currency.crypto.data

import com.eriksencosta.money.currency.CurrencyData

// 50 currencies
@Suppress("MagicNumber", "MaxLineLength", "StringLiteralDuplication")
internal class CurrenciesData45 {
    val currencies: Map<String, CurrencyData> get() = mapOf(
        "Z4LQD46FT" to CurrencyData("Z4LQD46FT", "BOT", "BOT Token", "BOT", "AUXILIARY", 18),
        "Z4WDVXT0Z" to CurrencyData("Z4WDVXT0Z", "SUI", "Sui", "SUI", "AUXILIARY", 9),
        "Z4ZVNRF9R" to CurrencyData("Z4ZVNRF9R", "USDC", "UpSideDownCat", "USDC", "AUXILIARY", 6),
        "Z506F8FCP" to CurrencyData("Z506F8FCP", "AFKP", "AFREUM FKP", "AFKP", "AUXILIARY", 7),
        "Z5BDS3ZW4" to CurrencyData("Z5BDS3ZW4", "XDATA", "Streamr (old)", "XDATA", "AUXILIARY", 18),
        "Z5MQ912MD" to CurrencyData("Z5MQ912MD", "RVN", "Ravencoin", "RVN", "NATIVE", 8),
        "Z5XNR3H8K" to CurrencyData("Z5XNR3H8K", "AGI", "Agility", "AGI", "AUXILIARY", 18),
        "Z63372HJ5" to CurrencyData("Z63372HJ5", "ORCA", "Orca", "ORCA", "AUXILIARY", 6),
        "Z7ZX774BJ" to CurrencyData("Z7ZX774BJ", "USDT", "USDT", "₮", "AUXILIARY", 4),
        "Z850KSNZX" to CurrencyData("Z850KSNZX", "AIDOGE", "ArbDoge AI", "AIDOGE", "AUXILIARY", 6),
        "Z9L49GGRX" to CurrencyData("Z9L49GGRX", "PORK", "PepeFork", "PORK", "AUXILIARY", 18),
        "Z9Q32C947" to CurrencyData("Z9Q32C947", "MONA", "MonaCoin", "MONA", "NATIVE", 8),
        "ZBC8DTX8G" to CurrencyData("ZBC8DTX8G", "CRO", "Cronos", "CRO", "AUXILIARY", 8),
        "ZBGBZSRB5" to CurrencyData("ZBGBZSRB5", "CORE", "Core", "CORE", "NATIVE", 10),
        "ZC550MZJM" to CurrencyData("ZC550MZJM", "PAXG", "Paxos Gold", "PAXG", "AUXILIARY", 8),
        "ZCPQKPV0W" to CurrencyData("ZCPQKPV0W", "MBL", "MovieBloc", "MBL", "AUXILIARY", 8),
        "ZCR8MBTJT" to CurrencyData("ZCR8MBTJT", "ELON", "Dogelon Mars", "ELON", "AUXILIARY", 18),
        "ZD011268C" to CurrencyData("ZD011268C", "UPP", "SENTINEL PROTOCOL", "UPP", "AUXILIARY", 18),
        "ZD5HWJ37C" to CurrencyData("ZD5HWJ37C", "ENG", "Enigma", "ENG", "AUXILIARY", 8),
        "ZDVC2M4CH" to CurrencyData("ZDVC2M4CH", "DCR", "Decred", "DCR", "NATIVE", 8),
        "ZDVJ27GFR" to CurrencyData("ZDVJ27GFR", "WAVAX", "Wrapped AVAX", "WAVAX", "AUXILIARY", 18),
        "ZFP9K2W9F" to CurrencyData("ZFP9K2W9F", "USDT", "Tether USD Token", "₮", "AUXILIARY", 6),
        "ZFWL1RK29" to CurrencyData("ZFWL1RK29", "AKRW", "AFREUM KRW", "AKRW", "AUXILIARY", 7),
        "ZG42CBT72" to CurrencyData("ZG42CBT72", "MATIC", "Matic Token", "MATIC", "AUXILIARY", 18),
        "ZGTT2QDM5" to CurrencyData("ZGTT2QDM5", "PIXEL", "PIXEL", "PIXEL", "AUXILIARY", 18),
        "ZH2TB4L7D" to CurrencyData("ZH2TB4L7D", "XVG", "Verge", "XVG", "NATIVE", 6),
        "ZH613B07W" to CurrencyData("ZH613B07W", "GOOGL", "DAAG Certificat/Tracker Perp GOOGL", "GOOGL", "AUXILIARY", 8),
        "ZHMB0ZJ99" to CurrencyData("ZHMB0ZJ99", "FSN", "Fusion", "FSN", "AUXILIARY", 8),
        "ZJ4RT6DMH" to CurrencyData("ZJ4RT6DMH", "PERL", "Perlin", "PERL", "AUXILIARY", 18),
        "ZJBJZLQ3K" to CurrencyData("ZJBJZLQ3K", "AUDIO", "Audius", "AUDIO", "AUXILIARY", 18),
        "ZJD7QGC9N" to CurrencyData("ZJD7QGC9N", "USDC", "USD Coin", "USDC", "AUXILIARY", 6),
        "ZJW681B5B" to CurrencyData("ZJW681B5B", "MOVR", "Moonriver", "MOVR", "NATIVE", 18),
        "ZLJFS3L81" to CurrencyData("ZLJFS3L81", "ESCE", "Escroco Emerald", "ESCE", "AUXILIARY", 8),
        "ZLX3SSPX5" to CurrencyData("ZLX3SSPX5", "KNC", "Kyber Network Crystal v2 (PoS)", "KNC", "AUXILIARY", 18),
        "ZLZ8X4SKJ" to CurrencyData("ZLZ8X4SKJ", "GRT", "Graph Token", "GRT", "AUXILIARY", 18),
        "ZMHPT2ZQ2" to CurrencyData("ZMHPT2ZQ2", "REEF", "Reef.finance", "REEF", "AUXILIARY", 18),
        "ZMSF31QG8" to CurrencyData("ZMSF31QG8", "pogai", "POGAI", "pogai", "AUXILIARY", 18),
        "ZMXL8PJX8" to CurrencyData("ZMXL8PJX8", "CH1331113444", "Stadt St Gallen/1.25 Bd 20270308 Sr", "CH1331113444", "AUXILIARY", 0),
        "ZN227BVRW" to CurrencyData("ZN227BVRW", "WBTC", "Wrapped BTC", "WBTC", "AUXILIARY", 8),
        "ZNFS8SRR3" to CurrencyData("ZNFS8SRR3", "BPWR", "BLUE POWER/GENS 0.10", "BPWR", "AUXILIARY", 0),
        "ZNVLQS2NN" to CurrencyData("ZNVLQS2NN", "ANKR", "Ankr Network", "ANKR", "AUXILIARY", 8),
        "ZPMDCJJVP" to CurrencyData("ZPMDCJJVP", "PEOPLE", "ConstitutionDAO", "PEOPLE", "AUXILIARY", 8),
        "ZQHL971M3" to CurrencyData("ZQHL971M3", "PYTH", "Pyth Network", "PYTH", "AUXILIARY", 6),
        "ZRPCKHNML" to CurrencyData("ZRPCKHNML", "WETH", "ETH@moonriver", "WETH", "AUXILIARY", 18),
        "ZRXB208K2" to CurrencyData("ZRXB208K2", "ATOM", "Atom via channel 2", "ATOM", "AUXILIARY", 6),
        "ZS04VSPWD" to CurrencyData("ZS04VSPWD", "ETH", "Ethereum Token", "Ξ", "AUXILIARY", 18),
        "ZS4FZ9TFL" to CurrencyData("ZS4FZ9TFL", "YGG", "Yield Guild Games Token", "YGG", "AUXILIARY", 18),
        "ZST44VTRK" to CurrencyData("ZST44VTRK", "CYBER", "CyberConnect", "CYBER", "AUXILIARY", 18),
        "ZT5GRK275" to CurrencyData("ZT5GRK275", "PERP", "Perpetual", "PERP", "AUXILIARY", 8),
        "ZTF814N3M" to CurrencyData("ZTF814N3M", "AGMD", "AFREUM GMD", "AGMD", "AUXILIARY", 7),
    )
}
