/*
 * This file is part of the Money package.
 *
 * Copyright (c) Eriksen Costa <eriksencosta@gmail.com>
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

/*
 * This file was auto-generated by running the "generateCryptoCurrenciesDataClasses" Gradle task. Always run the
 * task after a DTI database update.
 */

package com.eriksencosta.money.currency.crypto.data

import com.eriksencosta.money.currency.CurrencyData

// 50 currencies
@Suppress("MagicNumber", "MaxLineLength", "StringLiteralDuplication")
internal class CurrenciesData39 {
    val currencies: Map<String, CurrencyData> get() = mapOf(
        "T4J32WNT8" to CurrencyData("T4J32WNT8", "AAVE", "Aave", "AAVE", "AUXILIARY", 18),
        "T4K8C1K5J" to CurrencyData("T4K8C1K5J", "RPL", "Rocket Pool Protocol", "RPL", "AUXILIARY", 18),
        "T4KZZQ8M5" to CurrencyData("T4KZZQ8M5", "WAVAX", "Wrapped AVAX", "WAVAX", "AUXILIARY", 18),
        "T4SZ0VV5R" to CurrencyData("T4SZ0VV5R", "UST", "UST", "UST", "AUXILIARY", 6),
        "T4XB0S25S" to CurrencyData("T4XB0S25S", "AHTG", "AFREUM HTG", "AHTG", "AUXILIARY", 7),
        "T54BNMRFN" to CurrencyData("T54BNMRFN", "VOXEL", "VOXEL Token", "VOXEL", "AUXILIARY", 18),
        "T67DW1N39" to CurrencyData("T67DW1N39", "USDC", "USD Coin", "USDC", "AUXILIARY", 6),
        "T6MPXV0KP" to CurrencyData("T6MPXV0KP", "XCHF", "CryptoFranc", "XCHF", "AUXILIARY", 18),
        "T6TQ8GN7L" to CurrencyData("T6TQ8GN7L", "USDC", "USD Coin", "USDC", "AUXILIARY", 6),
        "T70ZXRP6K" to CurrencyData("T70ZXRP6K", "PLA", "PlayDapp Token", "PLA", "AUXILIARY", 18),
        "T7GMJBZDR" to CurrencyData("T7GMJBZDR", "SUSHI", "SushiSwap", "SUSHI", "AUXILIARY", 18),
        "T7JHJTN7F" to CurrencyData("T7JHJTN7F", "HK0000976420", "HKSAR/FR BD 20260202 UNSEC", "HK0000976420", "PROVISIONAL", 0),
        "T842ZR60W" to CurrencyData("T842ZR60W", "sUSD", "Synth sUSD", "sUSD", "AUXILIARY", 18),
        "T8HCTG9W6" to CurrencyData("T8HCTG9W6", "BUSD", "Binance-Peg BUSD Token", "BUSD", "AUXILIARY", 18),
        "T8TPN2450" to CurrencyData("T8TPN2450", "APLN", "AFREUM PLN", "APLN", "AUXILIARY", 7),
        "T9D0PM4KM" to CurrencyData("T9D0PM4KM", "WETH", "Wrapped Ether", "WETH", "AUXILIARY", 18),
        "T9FD00F70" to CurrencyData("T9FD00F70", "FRAX", "Frax", "FRAX", "AUXILIARY", 8),
        "T9KV5G6F7" to CurrencyData("T9KV5G6F7", "AKGS", "AFREUM KGS", "AKGS", "AUXILIARY", 7),
        "T9V7CHLSZ" to CurrencyData("T9V7CHLSZ", "MAV", "Massive Protocol", "MAV", "AUXILIARY", 18),
        "TB1DL70FB" to CurrencyData("TB1DL70FB", "MATIC", "Matic Token", "MATIC", "AUXILIARY", 18),
        "TBTN3M2G1" to CurrencyData("TBTN3M2G1", "YFI", "yearn.finance", "YFI", "AUXILIARY", 18),
        "TCP80SSH2" to CurrencyData("TCP80SSH2", "YFI", "yearn.finance", "YFI", "AUXILIARY", 8),
        "TCTS7KBJW" to CurrencyData("TCTS7KBJW", "MAGIC", "MAGIC", "MAGIC", "AUXILIARY", 18),
        "TD3VWXG02" to CurrencyData("TD3VWXG02", "AXL", "Axelar", "AXL", "AUXILIARY", 6),
        "TD9P9R111" to CurrencyData("TD9P9R111", "PEPE", "Pepe Coin", "🐸︎", "AUXILIARY", 18),
        "TDNKQTJRV" to CurrencyData("TDNKQTJRV", "AJMD", "AFREUM JMD", "AJMD", "AUXILIARY", 7),
        "TDWLL16VZ" to CurrencyData("TDWLL16VZ", "W", "Wormhole Token", "W", "AUXILIARY", 18),
        "TF2ZQH50W" to CurrencyData("TF2ZQH50W", "PROM", "Token Prometeus Network", "PROM", "AUXILIARY", 18),
        "TFNCXDB75" to CurrencyData("TFNCXDB75", "DEXE", "Dexe", "DEXE", "AUXILIARY", 18),
        "TFW1VM14P" to CurrencyData("TFW1VM14P", "SYS", "Syscoin", "SYS", "NATIVE", 8),
        "TGK66XK73" to CurrencyData("TGK66XK73", "ANKR", "Ankr", "ANKR", "AUXILIARY", 18),
        "TGKS7TRQT" to CurrencyData("TGKS7TRQT", "PEPE", "Pepe Coin", "🐸︎", "AUXILIARY", 18),
        "TJ3JW9MSS" to CurrencyData("TJ3JW9MSS", "ACAD", "AFREUM CAD", "ACAD", "AUXILIARY", 7),
        "TJ40H4L9S" to CurrencyData("TJ40H4L9S", "XYO", "XY Oracle", "XYO", "AUXILIARY", 18),
        "TJ7XZ9RZ4" to CurrencyData("TJ7XZ9RZ4", "USDC", "USDC token", "USDC", "AUXILIARY", 6),
        "TJRRPX0XC" to CurrencyData("TJRRPX0XC", "PEPE", "Pepe Community", "🐸︎", "AUXILIARY", 18),
        "TJZP16CLW" to CurrencyData("TJZP16CLW", "TRIBE", "Tribe", "TRIBE", "AUXILIARY", 18),
        "TL38L96B0" to CurrencyData("TL38L96B0", "DAI", "Dai", "◈", "AUXILIARY", 18),
        "TM1M7GJG0" to CurrencyData("TM1M7GJG0", "XEC", "eCash", "XEC", "NATIVE", 2),
        "TM9Q9FG6R" to CurrencyData("TM9Q9FG6R", "TRX", "TRON", "TRX", "AUXILIARY", 6),
        "TMSFFQGJH" to CurrencyData("TMSFFQGJH", "BETA", "Beta Token", "BETA", "AUXILIARY", 18),
        "TN24N8PPF" to CurrencyData("TN24N8PPF", "BUSD", "Binance USD", "BUSD", "AUXILIARY", 18),
        "TNKFPG09Q" to CurrencyData("TNKFPG09Q", "BCN", "Bytecoin", "BCN", "NATIVE", 0),
        "TPFC3B3B9" to CurrencyData("TPFC3B3B9", "WZEN", "Wrapped ZEN", "WZEN", "AUXILIARY", 18),
        "TPX7CR3V3" to CurrencyData("TPX7CR3V3", "WETH", "Wrapped Ether", "WETH", "AUXILIARY", 18),
        "TQ1G4JDD1" to CurrencyData("TQ1G4JDD1", "TIA", "Celestia", "TIA", "AUXILIARY", 6),
        "TQB32FQ1C" to CurrencyData("TQB32FQ1C", "ARDR", "Ardor Token", "ARDR", "AUXILIARY", 18),
        "TQHKN71CZ" to CurrencyData("TQHKN71CZ", "ORBS", "Orbs", "ORBS", "AUXILIARY", 8),
        "TRC6P8BJ8" to CurrencyData("TRC6P8BJ8", "AGTQ", "AFREUM GTQ", "AGTQ", "AUXILIARY", 7),
        "TS0ZHWLV8" to CurrencyData("TS0ZHWLV8", "UNI", "Uniswap", "UNI", "AUXILIARY", 18),
    )
}
