/*
 * This file is part of the Money package.
 *
 * Copyright (c) Eriksen Costa <eriksencosta@gmail.com>
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

/*
 * This file was auto-generated by running the "generateCryptoCurrenciesDataClasses" Gradle task. Always run the
 * task after a DTI database update.
 */

package com.eriksencosta.money.currency.crypto.data

// 21 currencies
@Suppress("StringLiteralDuplication")
internal class CurrenciesLookup18 {
    val currencies: Map<String, String> get() = mapOf(
        "pogai" to "ZMSF31QG8", // POGAI available in CurrenciesData45
        "sTETH" to "7DGW08CW7", // stakedETH available in CurrenciesData11
        "soETH" to "CHB6L1NZK", // Wrapped Ethereum available in CurrenciesData17
        "soFTT" to "HV8VLQR0P", // Wrapped FTT available in CurrenciesData24
        "soLINK" to "LG4RGB1ML", // Wrapped Chainlink available in CurrenciesData28
        "soSUSHI" to "36ZD0RH1T", // Wrapped SUSHI available in CurrenciesData4
        "token-wbtc" to "RVNGR71QZ", // Wrapped Bitcoin available in CurrenciesData37
        "token-wstx" to "R1D90QJKK", // Wrapped Stacks available in CurrenciesData36
        "vADA" to "KLSV179PN", // Venus ADA available in CurrenciesData27
        "vBNB" to "1SH5G969H", // Venus BNB available in CurrenciesData2
        "vBTC" to "HXG1Q34R4", // Venus BTC available in CurrenciesData24
        "vBUSD" to "QNC5Z77DJ", // Venus BUSD available in CurrenciesData35
        "vETH" to "9KT5X4GCT", // Venus ETH available in CurrenciesData14
        "vUSDC" to "7BC6346Q2", // Venus USDC available in CurrenciesData11
        "vUSDT" to "SM7H7LS97", // Venus USDT available in CurrenciesData38
        "wCFG" to "B2TVJN7Q1", // Wrapped Centrifuge available in CurrenciesData15
        "wNXM" to "593TDR8N7", // Wrapped NXM available in CurrenciesData8
        "wXLM" to "1DHZCHX0N", // Wrapped Stellar Lumens available in CurrenciesData1
        "xAI" to "6BP8GLQ1G", // xAI available in CurrenciesData9
        "xALGO" to "K88GZL5XP", // Wrapped ALGO available in CurrenciesData27
        "xDAI" to "JXG6Q514K", // Gnosis Chain available in CurrenciesData26
    )
}
