/*
 * This file is part of the Money package.
 *
 * Copyright (c) Eriksen Costa <eriksencosta@gmail.com>
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

/*
 * This file was auto-generated by running the "generateCryptoCurrenciesDataClasses" Gradle task. Always run the
 * task after a DTI database update.
 */

package com.eriksencosta.money.currency.crypto.data

import com.eriksencosta.money.currency.CurrencyData

// 50 currencies
@Suppress("MagicNumber", "MaxLineLength", "StringLiteralDuplication")
internal class CurrenciesData24 {
    val currencies: Map<String, CurrencyData> get() = mapOf(
        "HKWN2W8BB" to CurrencyData("HKWN2W8BB", "ACOP", "AFREUM COP", "ACOP", "AUXILIARY", 7),
        "HL3C0GQQ4" to CurrencyData("HL3C0GQQ4", "ADS", "Alkimi", "ADS", "AUXILIARY", 18),
        "HLG5F3MRM" to CurrencyData("HLG5F3MRM", "SISK", "AFREUM STABLE ISK", "SISK", "AUXILIARY", 7),
        "HM2QQX7P2" to CurrencyData("HM2QQX7P2", "GAS", "GasToken", "GAS", "AUXILIARY", 8),
        "HMWPQK1GS" to CurrencyData("HMWPQK1GS", "RIO", "Realio Network", "RIO", "AUXILIARY", 18),
        "HNFKFK6WL" to CurrencyData("HNFKFK6WL", "KMD", "Komodo", "KMD", "NATIVE", 8),
        "HNWNNN9TC" to CurrencyData("HNWNNN9TC", "SPEN", "AFREUM STABLE PEN", "SPEN", "AUXILIARY", 7),
        "HPDQBWZM7" to CurrencyData("HPDQBWZM7", "AVAX", "Avalanche", "AVAX", "AUXILIARY", 18),
        "HPKBG5PLB" to CurrencyData("HPKBG5PLB", "SSTN", "AFREUM STABLE STN", "SSTN", "AUXILIARY", 7),
        "HPTPJJWC6" to CurrencyData("HPTPJJWC6", "SBMD", "AFREUM STABLE BMD", "SBMD", "AUXILIARY", 7),
        "HPTSNQ86T" to CurrencyData("HPTSNQ86T", "WBT", "WBT", "WBT", "AUXILIARY", 8),
        "HPVXGTF8V" to CurrencyData("HPVXGTF8V", "AXL", "Axelar", "AXL", "AUXILIARY", 6),
        "HQG84W64N" to CurrencyData("HQG84W64N", "SOL", "WRAPPED SOL", "◎", "AUXILIARY", 9),
        "HQTDJBN5L" to CurrencyData("HQTDJBN5L", "GMX", "GAMEX", "GMX", "AUXILIARY", 9),
        "HR4QWLL9R" to CurrencyData("HR4QWLL9R", "PBR", "PolkaBridge", "PBR", "AUXILIARY", 18),
        "HRBN31W17" to CurrencyData("HRBN31W17", "BUSD", "BUSD Token", "BUSD", "AUXILIARY", 18),
        "HRG4CB749" to CurrencyData("HRG4CB749", "WMATIC", "Wrapped Matic", "WMATIC", "AUXILIARY", 8),
        "HRH14SVJP" to CurrencyData("HRH14SVJP", "LINK", "ChainLink Token", "LINK", "AUXILIARY", 18),
        "HRJ0ZBW0D" to CurrencyData("HRJ0ZBW0D", "ALCX", "Alchemix", "ALCX", "AUXILIARY", 18),
        "HRJTD84JR" to CurrencyData("HRJTD84JR", "LIT", "Lition", "LIT", "AUXILIARY", 8),
        "HRNDPZXJC" to CurrencyData("HRNDPZXJC", "USDC.e", "USD Coin", "USDC.e", "AUXILIARY", 6),
        "HRTC9BR9W" to CurrencyData("HRTC9BR9W", "jUSDT", "Tether USD", "jUSDT", "AUXILIARY", 6),
        "HT742VTHT" to CurrencyData("HT742VTHT", "CAKE", "PancakeSwap Token", "CAKE", "AUXILIARY", 18),
        "HTB0MXW5D" to CurrencyData("HTB0MXW5D", "VELO", "Velo", "VELO", "AUXILIARY", 7),
        "HTNP7JDH6" to CurrencyData("HTNP7JDH6", "ABND", "AFREUM BND", "ABND", "AUXILIARY", 7),
        "HV68JKT6L" to CurrencyData("HV68JKT6L", "MMT", "MyMetaTrader", "MMT", "AUXILIARY", 18),
        "HV8VLQR0P" to CurrencyData("HV8VLQR0P", "soFTT", "Wrapped FTT", "soFTT", "AUXILIARY", 6),
        "HW5NLL0X6" to CurrencyData("HW5NLL0X6", "USDC", "USD Coin on Fuse", "USDC", "AUXILIARY", 6),
        "HWD790TTS" to CurrencyData("HWD790TTS", "USDT-PPT", "USDT Crosschain Token", "USDT-PPT", "AUXILIARY", 6),
        "HWN9T781J" to CurrencyData("HWN9T781J", "BIT", "Bitmon", "BIT", "AUXILIARY", 9),
        "HX1NSP98N" to CurrencyData("HX1NSP98N", "ATOM", "Cosmos", "ATOM", "AUXILIARY", 6),
        "HX4LPG01H" to CurrencyData("HX4LPG01H", "ALPHA.e", "AlphaToken", "ALPHA.e", "AUXILIARY", 18),
        "HXF80XGRG" to CurrencyData("HXF80XGRG", "AANG", "AFREUM ANG", "AANG", "AUXILIARY", 7),
        "HXG1Q34R4" to CurrencyData("HXG1Q34R4", "vBTC", "Venus BTC", "vBTC", "AUXILIARY", 8),
        "HXNV8RN16" to CurrencyData("HXNV8RN16", "LIT", "LITION", "LIT", "AUXILIARY", 18),
        "HXR0K92NW" to CurrencyData("HXR0K92NW", "CNNC", "Cannation", "CNNC", "AUXILIARY", 18),
        "HXT7XMJ7C" to CurrencyData("HXT7XMJ7C", "ID", "SPACE ID", "ID", "AUXILIARY", 18),
        "HZ2L1PBPC" to CurrencyData("HZ2L1PBPC", "VITA", "VitaDAO", "VITA", "AUXILIARY", 18),
        "HZNM91RM2" to CurrencyData("HZNM91RM2", "KRW", "KROWN", "KRW", "AUXILIARY", 18),
        "J00HX4V8D" to CurrencyData("J00HX4V8D", "ZRX", "0x Protocol Token", "ZRX", "AUXILIARY", 18),
        "J04F1K9H3" to CurrencyData("J04F1K9H3", "BGB", "Bitget Token", "BGB", "AUXILIARY", 18),
        "J0D6B3L47" to CurrencyData("J0D6B3L47", "XS2615318289", "INTERNATIONAL B/3.399EMTN 20261023", "XS2615318289", "AUXILIARY", 0),
        "J0DRNZL29" to CurrencyData("J0DRNZL29", "SUPER", "SuperFarm", "SUPER", "AUXILIARY", 18),
        "J1MQPP9CT" to CurrencyData("J1MQPP9CT", "ADJF", "AFREUM DJF", "ADJF", "AUXILIARY", 7),
        "J26X57R97" to CurrencyData("J26X57R97", "USDC", "WrappedUSDC", "USDC", "AUXILIARY", 6),
        "J2DF28585" to CurrencyData("J2DF28585", "ASCR", "AFREUM SCR", "ASCR", "AUXILIARY", 7),
        "J340Z369K" to CurrencyData("J340Z369K", "SPHP", "AFREUM STABLE PHP", "SPHP", "AUXILIARY", 7),
        "J34Q9G7BC" to CurrencyData("J34Q9G7BC", "TIA", "Tia Token", "TIA", "AUXILIARY", 9),
        "J3CPZT31G" to CurrencyData("J3CPZT31G", "STMX", "StormX", "STMX", "AUXILIARY", 18),
        "J3KTSDGXR" to CurrencyData("J3KTSDGXR", "SUN", "SUN", "SUN", "AUXILIARY", 18),
    )
}
