/*
 * This file is part of the Money package.
 *
 * Copyright (c) Eriksen Costa <eriksencosta@gmail.com>
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

/*
 * This file was auto-generated by running the "generateCryptoCurrenciesDataClasses" Gradle task. Always run the
 * task after a DTI database update.
 */

package com.eriksencosta.money.currency.crypto.data

import com.eriksencosta.money.currency.CurrencyData

// 50 currencies
@Suppress("MagicNumber", "MaxLineLength", "StringLiteralDuplication")
internal class CurrenciesData7 {
    val currencies: Map<String, CurrencyData> get() = mapOf(
        "4PWW9V7BT" to CurrencyData("4PWW9V7BT", "ZIL", "Zilliqa", "ZIL", "AUXILIARY", 12),
        "4Q1NFZLDQ" to CurrencyData("4Q1NFZLDQ", "AMWK", "AFREUM MWK", "AMWK", "AUXILIARY", 7),
        "4Q2GK7RLN" to CurrencyData("4Q2GK7RLN", "FTM", "Fantom", "FTM", "AUXILIARY", 18),
        "4Q4B9PD9X" to CurrencyData("4Q4B9PD9X", "WETH", "Wrapped Ether", "WETH", "AUXILIARY", 18),
        "4Q6M5M99B" to CurrencyData("4Q6M5M99B", "USDT", "(PoS) Tether USD", "₮", "AUXILIARY", 6),
        "4R8R6BMZW" to CurrencyData("4R8R6BMZW", "GFI", "Goldfinch", "GFI", "AUXILIARY", 18),
        "4R9LQBV39" to CurrencyData("4R9LQBV39", "SAZN", "AFREUM STABLE AZN", "SAZN", "AUXILIARY", 7),
        "4RVGHRGM9" to CurrencyData("4RVGHRGM9", "DF", "dForce (PoS)", "DF", "AUXILIARY", 18),
        "4S144N5PR" to CurrencyData("4S144N5PR", "TLOS", "pTokens TLOS", "TLOS", "AUXILIARY", 18),
        "4SKFT9BB9" to CurrencyData("4SKFT9BB9", "COCOS", "CocosTokenV2", "COCOS", "AUXILIARY", 18),
        "4SNDZGBVP" to CurrencyData("4SNDZGBVP", "YGG", "Yield Guild Games Token", "YGG", "AUXILIARY", 18),
        "4TLSSHJS8" to CurrencyData("4TLSSHJS8", "FGC", "FantasyGold", "FGC", "AUXILIARY", 18),
        "4TRRQ5JRL" to CurrencyData("4TRRQ5JRL", "", "HSBC Gold Token", "", "PROVISIONAL", 0),
        "4WWX57DCQ" to CurrencyData("4WWX57DCQ", "ANKR", "Ankr Network", "ANKR", "AUXILIARY", 18),
        "4X31PW3DP" to CurrencyData("4X31PW3DP", "DAI", "Dai", "◈", "AUXILIARY", 18),
        "4X6Z0FWJT" to CurrencyData("4X6Z0FWJT", "RGT", "Rari Governance Token", "RGT", "AUXILIARY", 18),
        "4XZ3B56FT" to CurrencyData("4XZ3B56FT", "TWT", "Trust Wallet", "TWT", "AUXILIARY", 8),
        "4ZLW05RXQ" to CurrencyData("4ZLW05RXQ", "LBA", "LibraToken", "LBA", "AUXILIARY", 18),
        "4ZSZS1F4F" to CurrencyData("4ZSZS1F4F", "USDC", "USD Coin", "USDC", "AUXILIARY", 6),
        "50B1F4VSP" to CurrencyData("50B1F4VSP", "FLEX", "FLEX Coin", "FLEX", "AUXILIARY", 18),
        "50P510QC2" to CurrencyData("50P510QC2", "TRU", "TrueFi", "TRU", "AUXILIARY", 8),
        "510BQMK10" to CurrencyData("510BQMK10", "TRB", "Tellor Tributes (PoS)", "TRB", "AUXILIARY", 18),
        "515SFJ0CX" to CurrencyData("515SFJ0CX", "GAS", "Gas DAO", "GAS", "AUXILIARY", 18),
        "51NW699FS" to CurrencyData("51NW699FS", "BTS", "BitShares", "BTS", "NATIVE", 5),
        "51SB6GM6Q" to CurrencyData("51SB6GM6Q", "WETH", "Wrapped Ether", "WETH", "AUXILIARY", 18),
        "523PVPHKS" to CurrencyData("523PVPHKS", "TRX", "TRON", "TRX", "AUXILIARY", 6),
        "52G4MLV30" to CurrencyData("52G4MLV30", "AEVO", "Aevo", "AEVO", "AUXILIARY", 18),
        "52H4L48QZ" to CurrencyData("52H4L48QZ", "USDL", "Lift Dollar", "USDL", "AUXILIARY", 18),
        "52M6VXQTD" to CurrencyData("52M6VXQTD", "POL", "Polygon Ecosystem Token", "POL", "AUXILIARY", 18),
        "52PW0VNZJ" to CurrencyData("52PW0VNZJ", "JOE", "JoeToken", "JOE", "AUXILIARY", 18),
        "52RQ0017K" to CurrencyData("52RQ0017K", "ONG", "Ontology Gas", "ONG", "AUXILIARY", 18),
        "52XM4KWDV" to CurrencyData("52XM4KWDV", "DEGOV2", "dego.finance", "DEGOV2", "AUXILIARY", 18),
        "53DCR7F4Z" to CurrencyData("53DCR7F4Z", "SANTOS", "FC Santos Fan Token", "SANTOS", "AUXILIARY", 8),
        "53DPPC0KF" to CurrencyData("53DPPC0KF", "GNT", "Golem Network Token", "GNT", "AUXILIARY", 18),
        "53LS02VPW" to CurrencyData("53LS02VPW", "UST", "Wrapped UST Token", "UST", "AUXILIARY", 18),
        "546Q433WH" to CurrencyData("546Q433WH", "ACH", "Alchemy", "ACH", "AUXILIARY", 8),
        "54FQ0XCGP" to CurrencyData("54FQ0XCGP", "CHR", "Chromia", "CHR", "AUXILIARY", 6),
        "54Q07XMTH" to CurrencyData("54Q07XMTH", "\$MINA", "MINA", "\$MINA", "AUXILIARY", 9),
        "54QPBR5P3" to CurrencyData("54QPBR5P3", "WTR", "Water", "WTR", "AUXILIARY", 18),
        "559B8FFTR" to CurrencyData("559B8FFTR", "AXOF", "AFREUM XOF", "AXOF", "AUXILIARY", 7),
        "55C3M9MNM" to CurrencyData("55C3M9MNM", "ALICE", "ALICE", "ALICE", "AUXILIARY", 6),
        "55K9KLJ40" to CurrencyData("55K9KLJ40", "APE", "APEcoin", "APE", "AUXILIARY", 18),
        "55P8G61RZ" to CurrencyData("55P8G61RZ", "LOOM", "LoomToken", "LOOM", "AUXILIARY", 18),
        "55SKF2SQZ" to CurrencyData("55SKF2SQZ", "ATWD", "AFREUM TWD", "ATWD", "AUXILIARY", 7),
        "562T78F9X" to CurrencyData("562T78F9X", "HDOT", "Heco-Peg HDOT Token", "HDOT", "AUXILIARY", 18),
        "56QKD8Q78" to CurrencyData("56QKD8Q78", "SFJD", "AFREUM STABLE FJD", "SFJD", "AUXILIARY", 7),
        "56XMCCLGF" to CurrencyData("56XMCCLGF", "BNB", "Binance", "BNB", "AUXILIARY", 18),
        "57QNVL8FZ" to CurrencyData("57QNVL8FZ", "ANKR", "Ankr", "ANKR", "AUXILIARY", 18),
        "57SQPW4CQ" to CurrencyData("57SQPW4CQ", "AXL", "AXL INU", "AXL", "AUXILIARY", 18),
        "58537HRPB" to CurrencyData("58537HRPB", "OGN", "OriginToken", "OGN", "AUXILIARY", 18),
    )
}
