/*
 * This file is part of the Money package.
 *
 * Copyright (c) Eriksen Costa <eriksencosta@gmail.com>
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

/*
 * This file was auto-generated by running the "generateCryptoCurrenciesDataClasses" Gradle task. Always run the
 * task after a DTI database update.
 */

package com.eriksencosta.money.currency.crypto.data

// 50 currencies
@Suppress("StringLiteralDuplication")
internal class CurrenciesLookup2 {
    val currencies: Map<String, String> get() = mapOf(
        "ACOP" to "HKWN2W8BB", // AFREUM COP available in CurrenciesData24
        "ACRC" to "BJDTGB94T", // AFREUM CRC available in CurrenciesData16
        "ACUP" to "VZCXR9VP5", // AFREUM CUP available in CurrenciesData41
        "ACVE" to "LTPBVZ2WN", // AFREUM CVE available in CurrenciesData29
        "ACZK" to "GNDDSWKVB", // AFREUM CZK available in CurrenciesData22
        "ADJF" to "J1MQPP9CT", // AFREUM DJF available in CurrenciesData24
        "ADKK" to "BFJ5HHBGK", // AFREUM DKK available in CurrenciesData15
        "ADOP" to "7HK3RP772", // AFREUM DOP available in CurrenciesData11
        "ADS" to "HL3C0GQQ4", // Alkimi available in CurrenciesData24
        "ADZD" to "VM2QGSMP5", // AFREUM DZD available in CurrenciesData41
        "AEGP" to "L3B80KTH1", // AFREUM EGP available in CurrenciesData28
        "AERN" to "DJB9ZPNZZ", // AFREUM ERN available in CurrenciesData19
        "AETB" to "F0ND861VB", // AFREUM ETB available in CurrenciesData19
        "AEUR" to "ZTLVP2BW6", // AFREUM EUR available in CurrenciesData46
        "AEVO" to "52G4MLV30", // Aevo available in CurrenciesData7
        "AFJD" to "W508F2SJ4", // AFREUM FJD available in CurrenciesData41
        "AFKP" to "Z506F8FCP", // AFREUM FKP available in CurrenciesData45
        "AFR" to "L9CD41JMV", // AFREUM available in CurrenciesData28
        "AFRX" to "1BG77R3KX", // AFREUM X available in CurrenciesData1
        "AGBP" to "W087Q82PP", // AFREUM GBP available in CurrenciesData41
        "AGEL" to "V27S314VQ", // AFREUM GEL available in CurrenciesData40
        "AGHS" to "LB4LXVSTG", // AFREUM GHS available in CurrenciesData28
        "AGIP" to "JHTSDGP4V", // AFREUM GIP available in CurrenciesData25
        "AGIX" to "WKLHJRTP2", // SingularityNET Token available in CurrenciesData42
        "AGLD" to "7RRWRZ6VW", // Adventure Gold available in CurrenciesData11
        "AGMD" to "ZTF814N3M", // AFREUM GMD available in CurrenciesData45
        "AGNF" to "WRF47PN5M", // AFREUM GNF available in CurrenciesData42
        "AGTQ" to "TRC6P8BJ8", // AFREUM GTQ available in CurrenciesData39
        "AGYD" to "R85C5SFP7", // AFREUM GYD available in CurrenciesData36
        "AHKD" to "KWRMXG9TJ", // AFREUM HKD available in CurrenciesData28
        "AHNL" to "S7KWCDTFT", // AFREUM HNL available in CurrenciesData37
        "AHRK" to "M7MD3JKNS", // AFREUM HRK available in CurrenciesData30
        "AHTG" to "T4XB0S25S", // AFREUM HTG available in CurrenciesData39
        "AHUF" to "WLGL2R5HW", // AFREUM HUF available in CurrenciesData42
        "AIDOGE" to "Z850KSNZX", // ArbDoge AI available in CurrenciesData45
        "AIDR" to "K8WPL9GB8", // AFREUM IDR available in CurrenciesData27
        "AILS" to "S8J06RVF2", // AFREUM ILS available in CurrenciesData37
        "AINR" to "91D172VTL", // AFREUM INR available in CurrenciesData13
        "AIOZ" to "BQ1Q6B9SZ", // AIOZ Network available in CurrenciesData16
        "AIQD" to "Q5RVN1R5W", // AFREUM IQD available in CurrenciesData34
        "AIRR" to "PKRTR3JHV", // AFREUM IRR available in CurrenciesData33
        "AISK" to "QL1NXPV8S", // AFREUM ISK available in CurrenciesData35
        "AJMD" to "TDNKQTJRV", // AFREUM JMD available in CurrenciesData39
        "AJOD" to "26DQ579GL", // AFREUM JOD available in CurrenciesData2
        "AJPY" to "PHM8B4RQT", // AFREUM JPY available in CurrenciesData33
        "AKES" to "GN65TVTQ1", // AFREUM KES available in CurrenciesData22
        "AKGS" to "T9KV5G6F7", // AFREUM KGS available in CurrenciesData39
        "AKHR" to "DLKXXNKR7", // AFREUM KHR available in CurrenciesData19
        "AKMF" to "C2P0RCJ74", // AFREUM KMF available in CurrenciesData16
        "AKN" to "2RL6ZBC9X", // Akoin available in CurrenciesData3
    )
}
