/*
 * This file is part of the Money package.
 *
 * Copyright (c) Eriksen Costa <eriksencosta@gmail.com>
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

/*
 * This file was auto-generated by running the "generateCryptoCurrenciesDataClasses" Gradle task. Always run the
 * task after a DTI database update.
 */

package com.eriksencosta.money.currency.crypto.data

// 24 currencies
@Suppress("StringLiteralDuplication")
internal class CurrenciesLookup0 {
    val currencies: Map<String, String> get() = mapOf(
        "ADA" to "HWGL1C2CK", // Cardano ADA available in CurrenciesData0
        "APT" to "SSFZXXTDD", // Aptos Token available in CurrenciesData0
        "AVAX" to "M3Z631TN4", // Avalanche AVAX available in CurrenciesData0
        "BNB" to "HWRGLMT9T", // Binance Smart Chain available in CurrenciesData0
        "BTC" to "4H95J0R2X", // Bitcoin available in CurrenciesData0
        "DOGE" to "820B7G1NL", // Dogecoin available in CurrenciesData0
        "DOT" to "P5B46MFPP", // Polkadot DOT available in CurrenciesData0
        "ETC" to "GWQWXVV7J", // Ethereum Classic Ether available in CurrenciesData0
        "ETH" to "X9J9K872S", // Ethereum Ether available in CurrenciesData0
        "FIL" to "K8B662X5Z", // Filecoin available in CurrenciesData0
        "HBAR" to "DHQPD433B", // Hedera Hashgraph HBAR available in CurrenciesData0
        "ICP" to "7KL6LCVWQ", // Internet Computer Token available in CurrenciesData0
        "KAS" to "ZWK6RM36C", // Kaspa available in CurrenciesData0
        "LTC" to "WTX0G7K46", // Litecoin available in CurrenciesData0
        "MATIC" to "RQWW6J6K0", // Polygon Matic available in CurrenciesData0
        "MNT" to "C0D7M4H0R", // Mantle available in CurrenciesData0
        "NEAR" to "DC83NXWML", // NEAR Protocol available in CurrenciesData0
        "SOL" to "20J63Z4N3", // Solana SOL available in CurrenciesData0
        "STX" to "W7BGSQ91D", // Stacks available in CurrenciesData0
        "TON" to "QBZLT5MT1", // Toncoin available in CurrenciesData0
        "TRX" to "993D8X1FB", // TRON TRX available in CurrenciesData0
        "XLM" to "C4SRNZD8K", // Stellar Lumen available in CurrenciesData0
        "XMR" to "24VV95T9F", // Monero XMR available in CurrenciesData0
        "XRP" to "L6GTZC9G4", // Ripple XRP available in CurrenciesData0
    )
}
