/*
 * This file is part of the Money package.
 *
 * Copyright (c) Eriksen Costa <eriksencosta@gmail.com>
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

/*
 * This file was auto-generated by running the "generateCryptoCurrenciesDataClasses" Gradle task. Always run the
 * task after a DTI database update.
 */

package com.eriksencosta.money.currency.crypto.data

import com.eriksencosta.money.currency.CurrencyData

// 50 currencies
@Suppress("MagicNumber", "MaxLineLength", "StringLiteralDuplication")
internal class CurrenciesData18 {
    val currencies: Map<String, CurrencyData> get() = mapOf(
        "CP6817N4B" to CurrencyData("CP6817N4B", "USDC", "USDC", "USDC", "AUXILIARY", 6),
        "CP7F0V4HW" to CurrencyData("CP7F0V4HW", "STG", "StargateToken", "STG", "AUXILIARY", 18),
        "CPHVJTT11" to CurrencyData("CPHVJTT11", "NU", "NuCypher", "NU", "AUXILIARY", 18),
        "CQX5M5XB5" to CurrencyData("CQX5M5XB5", "DYDX", "dYdX", "DYDX", "AUXILIARY", 8),
        "CR7LW773L" to CurrencyData("CR7LW773L", "AMZN", "AFREUM MZN", "AMZN", "AUXILIARY", 7),
        "CRVMRGQTS" to CurrencyData("CRVMRGQTS", "ASZL", "AFREUM SZL", "ASZL", "AUXILIARY", 7),
        "CRVW55129" to CurrencyData("CRVW55129", "USDC", "USD Coin", "USDC", "AUXILIARY", 6),
        "CS7R4B4FQ" to CurrencyData("CS7R4B4FQ", "WETH", "Wrapped Ether", "WETH", "AUXILIARY", 18),
        "CSFHC7KK7" to CurrencyData("CSFHC7KK7", "BPD", "Beautiful Princess Disorder", "BPD", "AUXILIARY", 9),
        "CSFXXS6Z1" to CurrencyData("CSFXXS6Z1", "ARK", "ARKCOIN", "ARK", "AUXILIARY", 7),
        "CSMVGBMN3" to CurrencyData("CSMVGBMN3", "AXL", "AXL INU", "AXL", "AUXILIARY", 18),
        "CSR1WSZQF" to CurrencyData("CSR1WSZQF", "SWTH", "Switcheo Token", "SWTH", "AUXILIARY", 8),
        "CT1TWGPSJ" to CurrencyData("CT1TWGPSJ", "USDN", "Neutrino USD", "USDN", "AUXILIARY", 18),
        "CTC433GV4" to CurrencyData("CTC433GV4", "PEPEBOMB", "pepe", "PEPEBOMB", "AUXILIARY", 18),
        "CTZ6BN3P9" to CurrencyData("CTZ6BN3P9", "KAVA", "Kava BEP2 Token", "KAVA", "AUXILIARY", 8),
        "CVJQ5L4LP" to CurrencyData("CVJQ5L4LP", "CVC", "Civic", "CVC", "AUXILIARY", 0),
        "CWF6HXWFB" to CurrencyData("CWF6HXWFB", "STG", "StargateToken", "STG", "AUXILIARY", 18),
        "CWRMRKQRG" to CurrencyData("CWRMRKQRG", "SSYP", "AFREUM STABLE SYP", "SSYP", "AUXILIARY", 7),
        "CX0WF9HMH" to CurrencyData("CX0WF9HMH", "MEME", "Memecoin", "MEME", "AUXILIARY", 18),
        "CX40TTLS7" to CurrencyData("CX40TTLS7", "TRYB", "BiLira", "TRYB", "AUXILIARY", 6),
        "CXNJZ1C70" to CurrencyData("CXNJZ1C70", "PAXG", "PAX Gold", "PAXG", "AUXILIARY", 18),
        "CZZ52R5L3" to CurrencyData("CZZ52R5L3", "NULS", "Nuls", "NULS", "AUXILIARY", 8),
        "D00BX2H21" to CurrencyData("D00BX2H21", "CRO", "CRO", "CRO", "AUXILIARY", 8),
        "D0H261TJ2" to CurrencyData("D0H261TJ2", "KISHIMOTO", "Kishimoto", "KISHIMOTO", "AUXILIARY", 9),
        "D1BQDZR9S" to CurrencyData("D1BQDZR9S", "BTM", "Bytom", "BTM", "NATIVE", 8),
        "D1FSLC60F" to CurrencyData("D1FSLC60F", "EURCV", "EUR Coinvertible", "EURCV", "AUXILIARY", 18),
        "D1MPWZP6C" to CurrencyData("D1MPWZP6C", "BAND", "BandToken", "BAND", "AUXILIARY", 18),
        "D1QDBGC4F" to CurrencyData("D1QDBGC4F", "SYN", "Synapse", "SYN", "AUXILIARY", 18),
        "D1QHRHXR7" to CurrencyData("D1QHRHXR7", "ANKR", "Ankr Network", "ANKR", "AUXILIARY", 18),
        "D27DNZ98J" to CurrencyData("D27DNZ98J", "SBZD", "AFREUM STABLE BZD", "SBZD", "AUXILIARY", 7),
        "D3K7WMHT1" to CurrencyData("D3K7WMHT1", "HFIL", "Heco-Peg HFIL Token", "HFIL", "AUXILIARY", 18),
        "D3S7BV71L" to CurrencyData("D3S7BV71L", "OSMO", "Osmosis (PoS)", "OSMO", "AUXILIARY", 6),
        "D3V3W2PX2" to CurrencyData("D3V3W2PX2", "SBND", "AFREUM STABLE BND", "SBND", "AUXILIARY", 7),
        "D4W32DPGP" to CurrencyData("D4W32DPGP", "AXL", "Axelar", "AXL", "AUXILIARY", 6),
        "D5NHZ17DZ" to CurrencyData("D5NHZ17DZ", "FXS", "Frax Share", "FXS", "AUXILIARY", 8),
        "D608V9MJ1" to CurrencyData("D608V9MJ1", "ceUSDC", "USD Coin (Celer)", "ceUSDC", "AUXILIARY", 6),
        "D6T3P3N7G" to CurrencyData("D6T3P3N7G", "NULS", "NULS", "NULS", "AUXILIARY", 8),
        "D7HNWV9FV" to CurrencyData("D7HNWV9FV", "DODO", "DODO bird", "DODO", "AUXILIARY", 18),
        "D7HWJF6WZ" to CurrencyData("D7HWJF6WZ", "WAVAX", "Wrapped AVAX", "WAVAX", "AUXILIARY", 18),
        "D7XF135B1" to CurrencyData("D7XF135B1", "FRAX", "Frax", "FRAX", "AUXILIARY", 18),
        "D80V19S6F" to CurrencyData("D80V19S6F", "YFI", "yearn.finance", "YFI", "AUXILIARY", 18),
        "D94114L7T" to CurrencyData("D94114L7T", "SNX", "Synthetix Network Token", "SNX", "AUXILIARY", 18),
        "D978RVDVC" to CurrencyData("D978RVDVC", "CHZ", "Chiliz", "CHZ", "AUXILIARY", 8),
        "D9H3GJVD5" to CurrencyData("D9H3GJVD5", "SHPING", "Shping Coin", "SHPING", "AUXILIARY", 18),
        "D9Q5HX9QN" to CurrencyData("D9Q5HX9QN", "UPT", "Universal Protocol Token", "UPT", "AUXILIARY", 18),
        "DB3JBQS37" to CurrencyData("DB3JBQS37", "FRAX", "Frax", "FRAX", "AUXILIARY", 18),
        "DBH5126HL" to CurrencyData("DBH5126HL", "VGX", "Voyager Token", "VGX", "AUXILIARY", 8),
        "DCDN58XDP" to CurrencyData("DCDN58XDP", "SGEL", "AFREUM STABLE GEL", "SGEL", "AUXILIARY", 7),
        "DCHH2W0VW" to CurrencyData("DCHH2W0VW", "CNNC", "Cannation", "CNNC", "AUXILIARY", 18),
        "DCLQGHB7K" to CurrencyData("DCLQGHB7K", "USDT", "Tether USD", "₮", "AUXILIARY", 6),
    )
}
