/*
 * This file is part of the Money package.
 *
 * Copyright (c) Eriksen Costa <eriksencosta@gmail.com>
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

/*
 * This file was auto-generated by running the "generateCryptoCurrenciesDataClasses" Gradle task. Always run the
 * task after a DTI database update.
 */

package com.eriksencosta.money.currency.crypto.data

import com.eriksencosta.money.currency.CurrencyData

// 50 currencies
@Suppress("MagicNumber", "MaxLineLength", "StringLiteralDuplication")
internal class CurrenciesData21 {
    val currencies: Map<String, CurrencyData> get() = mapOf(
        "FRL4M33V1" to CurrencyData("FRL4M33V1", "CELR", "CelerToken", "CELR", "AUXILIARY", 18),
        "FRRW9S9KR" to CurrencyData("FRRW9S9KR", "ALAK", "AFREUM LAK", "ALAK", "AUXILIARY", 7),
        "FSSDHV1GM" to CurrencyData("FSSDHV1GM", "ABGN", "AFREUM BGN", "ABGN", "AUXILIARY", 7),
        "FT1FW2Z8F" to CurrencyData("FT1FW2Z8F", "EUROe", "EUROe Stablecoin", "EUROe", "AUXILIARY", 6),
        "FTSVS8G4S" to CurrencyData("FTSVS8G4S", "NEXO", "Nexo", "NEXO", "AUXILIARY", 8),
        "FVVM5K1LJ" to CurrencyData("FVVM5K1LJ", "GMT", "Green Metaverse Token", "GMT", "AUXILIARY", 8),
        "FW5059XW8" to CurrencyData("FW5059XW8", "EUROe", "EUROe Stablecoin", "EUROe", "AUXILIARY", 6),
        "FX7ZCPFPX" to CurrencyData("FX7ZCPFPX", "COTI", "Currency of the Internet", "COTI", "AUXILIARY", 18),
        "FXLLS1VBR" to CurrencyData("FXLLS1VBR", "SOLA", "SOLA Token", "SOLA", "AUXILIARY", 9),
        "FZ3W43J1Q" to CurrencyData("FZ3W43J1Q", "SUGX", "AFREUM STABLE UGX", "SUGX", "AUXILIARY", 7),
        "FZJ3Q9MHV" to CurrencyData("FZJ3Q9MHV", "HDL", "HEADLINE", "HDL", "AUXILIARY", 6),
        "FZP9CBTG1" to CurrencyData("FZP9CBTG1", "USDT", "TetherUSD", "₮", "AUXILIARY", 6),
        "G00RGKXM8" to CurrencyData("G00RGKXM8", "AMYR", "AFREUM MYR", "AMYR", "AUXILIARY", 7),
        "G0NFT3W7B" to CurrencyData("G0NFT3W7B", "PEPE", "Pepe", "🐸︎", "AUXILIARY", 18),
        "G0V71VTTX" to CurrencyData("G0V71VTTX", "CRO", "Cronos", "CRO", "AUXILIARY", 8),
        "G1HDCB6XX" to CurrencyData("G1HDCB6XX", "SDTC", "Terra Classic SDR", "SDTC", "AUXILIARY", 6),
        "G1NP4B0R1" to CurrencyData("G1NP4B0R1", "AI", "Any Inu", "AI", "AUXILIARY", 18),
        "G1S5FD4D4" to CurrencyData("G1S5FD4D4", "ATOP", "AFREUM TOP", "ATOP", "AUXILIARY", 7),
        "G1Z52QNDQ" to CurrencyData("G1Z52QNDQ", "LU2637450516", "EUROP.INVEST.BK/BD 20250619", "LU2637450516", "PROVISIONAL", 0),
        "G248MCQL8" to CurrencyData("G248MCQL8", "MANA", "Decentraland", "MANA", "AUXILIARY", 8),
        "G2TZXGDWP" to CurrencyData("G2TZXGDWP", "SKHR", "AFREUM STABLE KHR", "SKHR", "AUXILIARY", 7),
        "G3GL41LFS" to CurrencyData("G3GL41LFS", "SSDG", "AFREUM STABLE SDG", "SSDG", "AUXILIARY", 7),
        "G3XJPRBB1" to CurrencyData("G3XJPRBB1", "WEMIX", "WEMIX TOKEN", "WEMIX", "AUXILIARY", 18),
        "G3XLSP4R8" to CurrencyData("G3XLSP4R8", "REPv2", "Reputation", "REPv2", "AUXILIARY", 18),
        "G4FGGX4BL" to CurrencyData("G4FGGX4BL", "SERN", "AFREUM STABLE ERN", "SERN", "AUXILIARY", 7),
        "G55J0GJD5" to CurrencyData("G55J0GJD5", "ASEK", "AFREUM SEK", "ASEK", "AUXILIARY", 7),
        "G5V1VW077" to CurrencyData("G5V1VW077", "CVP", "PowerPool", "CVP", "AUXILIARY", 18),
        "G6JFHNCZ2" to CurrencyData("G6JFHNCZ2", "OSMO", "Osmo Bot", "OSMO", "AUXILIARY", 18),
        "G6P7GVF99" to CurrencyData("G6P7GVF99", "USDT.e", "Tether USD", "USDT.e", "AUXILIARY", 6),
        "G6QG2LNJX" to CurrencyData("G6QG2LNJX", "UNI", "Uniswap", "UNI", "AUXILIARY", 8),
        "G6X7XVSNW" to CurrencyData("G6X7XVSNW", "SSRD", "AFREUM STABLE SRD", "SSRD", "AUXILIARY", 7),
        "G7N3LZPVB" to CurrencyData("G7N3LZPVB", "LOOKS", "LooksRare Token", "LOOKS", "AUXILIARY", 18),
        "G7ZDB1GZC" to CurrencyData("G7ZDB1GZC", "EURR", "StablR Euro", "EURR", "AUXILIARY", 6),
        "G8HDVQ7QL" to CurrencyData("G8HDVQ7QL", "LTC", "Litecoin Token", "Ł", "AUXILIARY", 18),
        "G9JQ1S1DG" to CurrencyData("G9JQ1S1DG", "WOO", "Wootrade Network (PoS)", "WOO", "AUXILIARY", 18),
        "G9S7R09HP" to CurrencyData("G9S7R09HP", "BOME", "BOOK OF MEME", "BOME", "AUXILIARY", 6),
        "G9VQ1W3GL" to CurrencyData("G9VQ1W3GL", "WBNB", "Wrapped BNB", "WBNB", "AUXILIARY", 8),
        "GBDZ44R7L" to CurrencyData("GBDZ44R7L", "WETH", "Wrapped Ether", "WETH", "AUXILIARY", 18),
        "GCFC6B8MZ" to CurrencyData("GCFC6B8MZ", "VOLT", "Volt Inu V2", "VOLT", "AUXILIARY", 9),
        "GDBFM94L0" to CurrencyData("GDBFM94L0", "AMB", "Apple", "AMB", "AUXILIARY", 9),
        "GDMZVG68T" to CurrencyData("GDMZVG68T", "STWD", "AFREUM STABLE TWD", "STWD", "AUXILIARY", 7),
        "GDSV666LN" to CurrencyData("GDSV666LN", "BOBA", "Boba Token", "BOBA", "AUXILIARY", 18),
        "GDX74SST8" to CurrencyData("GDX74SST8", "W", "Wormhole Token", "W", "AUXILIARY", 6),
        "GF3P57PFK" to CurrencyData("GF3P57PFK", "WEVMOS", "Wrapped Evmos", "WEVMOS", "AUXILIARY", 18),
        "GFB995KNJ" to CurrencyData("GFB995KNJ", "SDOP", "AFREUM STABLE DOP", "SDOP", "AUXILIARY", 7),
        "GFJRSQG02" to CurrencyData("GFJRSQG02", "USDC", "USD Coin", "USDC", "AUXILIARY", 18),
        "GFN2JK0GV" to CurrencyData("GFN2JK0GV", "SCOP", "AFREUM STABLE COP", "SCOP", "AUXILIARY", 7),
        "GG2FHST42" to CurrencyData("GG2FHST42", "AXCD", "AFREUM XCD", "AXCD", "AUXILIARY", 7),
        "GGZ8TTCM9" to CurrencyData("GGZ8TTCM9", "WETH", "WETH", "WETH", "AUXILIARY", 8),
        "GH18F8X9K" to CurrencyData("GH18F8X9K", "CQT", "Covalent Query Token", "CQT", "AUXILIARY", 18),
    )
}
