/*
 * This file is part of the Money package.
 *
 * Copyright (c) Eriksen Costa <eriksencosta@gmail.com>
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

/*
 * This file was auto-generated by running the "generateCryptoCurrenciesDataClasses" Gradle task. Always run the
 * task after a DTI database update.
 */

package com.eriksencosta.money.currency.crypto.data

import com.eriksencosta.money.currency.CurrencyData

// 50 currencies
@Suppress("MagicNumber", "MaxLineLength", "StringLiteralDuplication")
internal class CurrenciesData1 {
    val currencies: Map<String, CurrencyData> get() = mapOf(
        "10LJNZXHS" to CurrencyData("10LJNZXHS", "BIT", "BitDAO", "BIT", "PROVISIONAL", 0),
        "10ZW1X3N5" to CurrencyData("10ZW1X3N5", "TBONDS13", "SwarmX/Struct Perp Fds Sr Unsec", "TBONDS13", "AUXILIARY", 27),
        "11PXFLMVJ" to CurrencyData("11PXFLMVJ", "LPT", "Livepeer", "LPT", "AUXILIARY", 18),
        "11XNLBSDG" to CurrencyData("11XNLBSDG", "DAI", "Dai Stablecoin", "◈", "AUXILIARY", 18),
        "123ZSRM6D" to CurrencyData("123ZSRM6D", "NFTN", "NFTNetwork", "NFTN", "AUXILIARY", 9),
        "125J528CN" to CurrencyData("125J528CN", "jUSDT", "Tether USD", "jUSDT", "AUXILIARY", 6),
        "12LDTQ14F" to CurrencyData("12LDTQ14F", "REZ", "Renzo", "REZ", "AUXILIARY", 18),
        "12NRRG38S" to CurrencyData("12NRRG38S", "TIA", "TIA", "TIA", "AUXILIARY", 6),
        "13D0SQH97" to CurrencyData("13D0SQH97", "USDC", "USD Coin", "USDC", "AUXILIARY", 18),
        "13T549QT3" to CurrencyData("13T549QT3", "ALYD", "AFREUM LYD", "ALYD", "AUXILIARY", 7),
        "13XBRDZWR" to CurrencyData("13XBRDZWR", "DAI", "Dai Stablecoin", "◈", "AUXILIARY", 8),
        "1424T4TL9" to CurrencyData("1424T4TL9", "FORTH", "Ampleforth Governance", "FORTH", "AUXILIARY", 18),
        "146FHT2GR" to CurrencyData("146FHT2GR", "SOL", "BonkHoneyHNTMobileSOL", "◎", "AUXILIARY", 0),
        "14CCHV9R7" to CurrencyData("14CCHV9R7", "NANO", "Nano", "Ӿ", "NATIVE", 30),
        "15D12CMDR" to CurrencyData("15D12CMDR", "AUYU", "AFREUM UYU", "AUYU", "AUXILIARY", 7),
        "16V5MJQMH" to CurrencyData("16V5MJQMH", "FDUSD", "First Digital USD", "FDUSD", "AUXILIARY", 18),
        "17002NH5Z" to CurrencyData("17002NH5Z", "FXS", "Frax Share", "FXS", "AUXILIARY", 18),
        "177515SPS" to CurrencyData("177515SPS", "MULTI", "Multichain", "MULTI", "AUXILIARY", 18),
        "17GWTST28" to CurrencyData("17GWTST28", "milkALGO", "Milkomeda A1", "milkALGO", "NATIVE", 18),
        "17HBZ5XCJ" to CurrencyData("17HBZ5XCJ", "ZETA", "stoicDAO", "ZETA", "AUXILIARY", 18),
        "17KZJVLZQ" to CurrencyData("17KZJVLZQ", "AXS", "Axie Infinity Shard", "AXS", "AUXILIARY", 18),
        "18VXVXV30" to CurrencyData("18VXVXV30", "DOGE", "DOGE", "Ð", "AUXILIARY", 18),
        "19T0P4NPX" to CurrencyData("19T0P4NPX", "UFT", "UniLend Finance Token", "UFT", "AUXILIARY", 18),
        "1B9XWTSFN" to CurrencyData("1B9XWTSFN", "BAT", "Basic Attention Token", "BAT", "AUXILIARY", 18),
        "1BG77R3KX" to CurrencyData("1BG77R3KX", "AFRX", "AFREUM X", "AFRX", "AUXILIARY", 7),
        "1C7HJGT98" to CurrencyData("1C7HJGT98", "FTM", "Fantom Token", "FTM", "AUXILIARY", 8),
        "1C9P62QQ1" to CurrencyData("1C9P62QQ1", "PYR", "PYR Token", "PYR", "AUXILIARY", 18),
        "1CFNM04RC" to CurrencyData("1CFNM04RC", "ZERO", "ZERO", "ZERO", "AUXILIARY", 18),
        "1CLCNMK9W" to CurrencyData("1CLCNMK9W", "GODS", "Gods Unchained", "GODS", "AUXILIARY", 18),
        "1CQ8Z405P" to CurrencyData("1CQ8Z405P", "GBTC", "Terra Classic GBP", "GBTC", "AUXILIARY", 6),
        "1CTDC3RXV" to CurrencyData("1CTDC3RXV", "MASK", "Mask Network (PoS)", "MASK", "AUXILIARY", 18),
        "1D1FZF75M" to CurrencyData("1D1FZF75M", "PEPE", "pepecoin on SOL", "🐸︎", "AUXILIARY", 9),
        "1DHZCHX0N" to CurrencyData("1DHZCHX0N", "wXLM", "Wrapped Stellar Lumens", "wXLM", "AUXILIARY", 18),
        "1DP7Q57L6" to CurrencyData("1DP7Q57L6", "BNB", "BNB", "BNB", "AUXILIARY", 18),
        "1FGHSCJ0S" to CurrencyData("1FGHSCJ0S", "BEL", "Bella Protocol", "BEL", "AUXILIARY", 18),
        "1FRZDTR6N" to CurrencyData("1FRZDTR6N", "WETH", "Ethereum", "Ξ", "AUXILIARY", 18),
        "1FWNCRC0S" to CurrencyData("1FWNCRC0S", "USDT", "Tether USD from Ethereum", "₮", "AUXILIARY", 6),
        "1G7Z6TH24" to CurrencyData("1G7Z6TH24", "SIDR", "AFREUM STABLE IDR", "SIDR", "AUXILIARY", 7),
        "1GNML4FGK" to CurrencyData("1GNML4FGK", "FTM", "Fantom", "FTM", "AUXILIARY", 18),
        "1HRGNM93Z" to CurrencyData("1HRGNM93Z", "SLP", "Smooth Love Potion", "SLP", "AUXILIARY", 18),
        "1JJHQLX4D" to CurrencyData("1JJHQLX4D", "USDT", "Frapped USDT", "₮", "AUXILIARY", 6),
        "1K72DKCBK" to CurrencyData("1K72DKCBK", "BIGTIME", "Big Time", "BIGTIME", "AUXILIARY", 18),
        "1K8HT8SZW" to CurrencyData("1K8HT8SZW", "GRT", "Graph Token", "GRT", "AUXILIARY", 18),
        "1KH493WDN" to CurrencyData("1KH493WDN", "GHST", "Aavegotchi GHST Token (PoS)", "GHST", "AUXILIARY", 18),
        "1LGQ2D5W4" to CurrencyData("1LGQ2D5W4", "ZBC", "ZEBEC", "ZBC", "AUXILIARY", 9),
        "1LR9460XV" to CurrencyData("1LR9460XV", "REV", "Revain", "REV", "AUXILIARY", 6),
        "1LW8ZQ7QK" to CurrencyData("1LW8ZQ7QK", "TIME", "ChronoTech Token", "TIME", "AUXILIARY", 8),
        "1LZRJ8L3C" to CurrencyData("1LZRJ8L3C", "EVMOS", "EVMOS", "EVMOS", "AUXILIARY", 18),
        "1MBXSD6KL" to CurrencyData("1MBXSD6KL", "UQC", "Uquid Coin", "UQC", "AUXILIARY", 18),
        "1MKH0F6ZM" to CurrencyData("1MKH0F6ZM", "FITFI", "STEP.APP", "FITFI", "AUXILIARY", 18),
    )
}
