/*
 * This file is part of the Money package.
 *
 * Copyright (c) Eriksen Costa <eriksencosta@gmail.com>
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

/*
 * This file was auto-generated by running the "generateCryptoCurrenciesDataClasses" Gradle task. Always run the
 * task after a DTI database update.
 */

package com.eriksencosta.money.currency.crypto.data

import com.eriksencosta.money.currency.CurrencyData

// 50 currencies
@Suppress("MagicNumber", "MaxLineLength", "StringLiteralDuplication")
internal class CurrenciesData40 {
    val currencies: Map<String, CurrencyData> get() = mapOf(
        "TS2347Z7N" to CurrencyData("TS2347Z7N", "USDC", "USD Coin", "USDC", "AUXILIARY", 6),
        "TSXCH30TD" to CurrencyData("TSXCH30TD", "USDT", "Tether", "₮", "AUXILIARY", 6),
        "TTC7MQ9FW" to CurrencyData("TTC7MQ9FW", "aUSDT", "aUSDT", "aUSDT", "AUXILIARY", 6),
        "TTQ2HJFWN" to CurrencyData("TTQ2HJFWN", "1INCH", "1INCH Token", "1INCH", "AUXILIARY", 18),
        "TTRNBWRVR" to CurrencyData("TTRNBWRVR", "PORTAL", "PORTAL", "PORTAL", "AUXILIARY", 18),
        "TV5T68SZJ" to CurrencyData("TV5T68SZJ", "LUNC", "Terra Classic", "LUNC", "AUXILIARY", 6),
        "TVDFR4GBX" to CurrencyData("TVDFR4GBX", "APHP", "AFREUM PHP", "APHP", "AUXILIARY", 7),
        "TVRL92VD9" to CurrencyData("TVRL92VD9", "PEPE", "Pepecoin", "🐸︎", "AUXILIARY", 9),
        "TVXBKJ6LP" to CurrencyData("TVXBKJ6LP", "CRV", "Curve DAO Token", "CRV", "AUXILIARY", 18),
        "TWJVSFWL0" to CurrencyData("TWJVSFWL0", "ZEUS", "ZEUS", "ZEUS", "AUXILIARY", 6),
        "TX5Q26B5F" to CurrencyData("TX5Q26B5F", "NEON", "NEON EVM", "NEON", "NATIVE", 9),
        "TX7TRXHS0" to CurrencyData("TX7TRXHS0", "SHUF", "AFREUM STABLE HUF", "SHUF", "AUXILIARY", 7),
        "TZFBWN3DF" to CurrencyData("TZFBWN3DF", "VLX", "Velas", "VLX", "NATIVE", 9),
        "TZFM5MHWR" to CurrencyData("TZFM5MHWR", "USDt", "Tether USD", "USDt", "AUXILIARY", 6),
        "TZM1MNSRF" to CurrencyData("TZM1MNSRF", "TBONDS01", "SwarmX/Struct Perp Fds Sr Unsec", "TBONDS01", "AUXILIARY", 27),
        "V0BT91RXZ" to CurrencyData("V0BT91RXZ", "AXPF", "AFREUM XPF", "AXPF", "AUXILIARY", 7),
        "V0H1T9C2Z" to CurrencyData("V0H1T9C2Z", "LOOM", "Loom Token", "LOOM", "AUXILIARY", 18),
        "V0SSRMM4T" to CurrencyData("V0SSRMM4T", "USDD", "Decentralized USD", "USDD", "AUXILIARY", 18),
        "V0V1Z17C1" to CurrencyData("V0V1Z17C1", "MATICpo", "Matic", "MATICpo", "AUXILIARY", 8),
        "V1CW4WD3Z" to CurrencyData("V1CW4WD3Z", "BPTC", "Business Platform Tomato Coin", "BPTC", "AUXILIARY", 8),
        "V1HLCMXP4" to CurrencyData("V1HLCMXP4", "LUNA", "LUNA", "LUNA", "AUXILIARY", 6),
        "V21R899BV" to CurrencyData("V21R899BV", "ETH", "Ethereum", "Ξ", "AUXILIARY", 18),
        "V23M4RT1K" to CurrencyData("V23M4RT1K", "ABDT", "AFREUM BDT", "ABDT", "AUXILIARY", 7),
        "V260VFVT8" to CurrencyData("V260VFVT8", "DAI", "Dai Stablecoin", "◈", "AUXILIARY", 18),
        "V27S314VQ" to CurrencyData("V27S314VQ", "AGEL", "AFREUM GEL", "AGEL", "AUXILIARY", 7),
        "V2N9ZRBHG" to CurrencyData("V2N9ZRBHG", "WETH", "Wrapped Ether", "WETH", "AUXILIARY", 18),
        "V4M48TB9S" to CurrencyData("V4M48TB9S", "ORN", "Orion Protocol", "ORN", "AUXILIARY", 8),
        "V5VW73Q6S" to CurrencyData("V5VW73Q6S", "VOLT", "Volt Inu V2", "VOLT", "AUXILIARY", 9),
        "V5Z1G0H8C" to CurrencyData("V5Z1G0H8C", "QSP", "Quantstamp", "QSP", "AUXILIARY", 18),
        "V6HT38SS8" to CurrencyData("V6HT38SS8", "ACA", "ACA Token", "ACA", "AUXILIARY", 9),
        "V6SHJRDFL" to CurrencyData("V6SHJRDFL", "FARM", "FARM Reward Token", "FARM", "AUXILIARY", 18),
        "V71NNNTJZ" to CurrencyData("V71NNNTJZ", "ABNB", "DAAG Certificat/Tracker Perp ABNB", "ABNB", "AUXILIARY", 8),
        "V7P9R08H7" to CurrencyData("V7P9R08H7", "VELO", "VelodromeV2", "VELO", "AUXILIARY", 18),
        "V87B4J23J" to CurrencyData("V87B4J23J", "SRWF", "AFREUM STABLE RWF", "SRWF", "AUXILIARY", 7),
        "V8P86MVQ3" to CurrencyData("V8P86MVQ3", "GMT", "GoMining Token", "GMT", "AUXILIARY", 18),
        "V8PXFHZ9T" to CurrencyData("V8PXFHZ9T", "BGB", "Bitget Token", "BGB", "AUXILIARY", 9),
        "V9RDNLSMZ" to CurrencyData("V9RDNLSMZ", "HOP", "Hop", "HOP", "AUXILIARY", 18),
        "V9SDBRC1X" to CurrencyData("V9SDBRC1X", "CHESS", "Chess", "CHESS", "AUXILIARY", 18),
        "VB1MQLJ23" to CurrencyData("VB1MQLJ23", "CANTO", "Canto", "CANTO", "NATIVE", 9),
        "VB2Q3G56B" to CurrencyData("VB2Q3G56B", "SHIB", "SHIBA INU", "SHIB", "AUXILIARY", 18),
        "VB2VZNNP0" to CurrencyData("VB2VZNNP0", "LTO", "LTO Network", "LTO", "AUXILIARY", 18),
        "VB9SQC824" to CurrencyData("VB9SQC824", "AUAH", "AFREUM UAH", "AUAH", "AUXILIARY", 7),
        "VBLS1XVN4" to CurrencyData("VBLS1XVN4", "BTT", "BitTorrent", "BTT", "AUXILIARY", 6),
        "VC55ZVQC4" to CurrencyData("VC55ZVQC4", "CH1348614202", "UBS Switzerland/1.5075 MB 20290528", "CH1348614202", "AUXILIARY", 0),
        "VF6SNLQ0V" to CurrencyData("VF6SNLQ0V", "QTUM", "Qtum", "QTUM", "NATIVE", 8),
        "VF9HWNFF7" to CurrencyData("VF9HWNFF7", "SHIB", "SHIBA INU (Wormhole)", "SHIB", "AUXILIARY", 8),
        "VFB2MN7HC" to CurrencyData("VFB2MN7HC", "SYN", "Synapse", "SYN", "AUXILIARY", 18),
        "VFLDZKHPK" to CurrencyData("VFLDZKHPK", "ACH", "Alchemy", "ACH", "AUXILIARY", 8),
        "VFN4XKRL6" to CurrencyData("VFN4XKRL6", "SUN", "DAAG Certificat/Tracker Perp SUN", "SUN", "AUXILIARY", 8),
        "VGG0T9QTG" to CurrencyData("VGG0T9QTG", "EDU", "Open Campus", "EDU", "AUXILIARY", 18),
    )
}
