/*
 * This file is part of the Money package.
 *
 * Copyright (c) Eriksen Costa <eriksencosta@gmail.com>
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

/*
 * This file was auto-generated by running the "generateCryptoCurrenciesDataClasses" Gradle task. Always run the
 * task after a DTI database update.
 */

package com.eriksencosta.money.currency.crypto.data

// 2283 currencies
@Suppress("LargeClass")
internal class CurrenciesSecondaryCodes {
    val codes: Set<String> get() = setOf(
        "\$HIB", // SHIBA INU
        "\$MINA", // MINA
        "\$MONG", // MongCoin
        "\$SOL", // Solidify
        "1AXS", // Axie Infinity Shard
        "1DAI", // Dai Stablecoin
        "1ETH", // ETH
        "1GBP", // poundtoken
        "1INCH.e", // 1INCH Token
        "1ONE", // Harmony ONE
        "1TRB", // Tellor Tributes
        "1USDC", // USD Coin
        "1USDT", // Tether USD
        "1WBTC", // Wrapped BTC
        "AAED", // AFREUM AED
        "AAFN", // AFREUM AFN
        "AALL", // AFREUM ALL
        "AAMD", // AFREUM AMD
        "AANG", // AFREUM ANG
        "AAOA", // AFREUM AOA
        "AARS", // AFREUM ARS
        "AAUD", // AFREUM AUD
        "AAWG", // AFREUM AWG
        "AAZN", // AFREUM AZN
        "ABAM", // AFREUM BAM
        "ABBD", // AFREUM BBD
        "ABC", // DAAG Certificat/Tracker Perp ABC
        "ABDT", // AFREUM BDT
        "ABGN", // AFREUM BGN
        "ABHD", // AFREUM BHD
        "ABIF", // AFREUM BIF
        "ABMD", // AFREUM BMD
        "ABNB", // DAAG Certificat/Tracker Perp ABNB
        "ABND", // AFREUM BND
        "ABOB", // AFREUM BOB
        "ABRL", // AFREUM BRL
        "ABSD", // AFREUM BSD
        "ABTN", // AFREUM BTN
        "ABWP", // AFREUM BWP
        "ABYN", // AFREUM BYN
        "ABZD", // AFREUM BZD
        "ACA", // ACA Token
        "ACAD", // AFREUM CAD
        "ACB", // DAAG Certificat/Tracker Perp ACB
        "ACDF", // AFREUM CDF
        "ACE", // ACEToken
        "ACHF", // AFREUM CHF
        "ACLP", // AFREUM CLP
        "ACM", // AC Milan
        "ACNY", // AFREUM CNY
        "ACOP", // AFREUM COP
        "ACRC", // AFREUM CRC
        "ACUP", // AFREUM CUP
        "ACVE", // AFREUM CVE
        "ACZK", // AFREUM CZK
        "ADA", // Cardano ADA
        "ADJF", // AFREUM DJF
        "ADKK", // AFREUM DKK
        "ADOP", // AFREUM DOP
        "ADS", // Alkimi
        "ADZD", // AFREUM DZD
        "AEGP", // AFREUM EGP
        "AERN", // AFREUM ERN
        "AETB", // AFREUM ETB
        "AEUR", // AFREUM EUR
        "AEVO", // Aevo
        "AFJD", // AFREUM FJD
        "AFKP", // AFREUM FKP
        "AFR", // AFREUM
        "AFRX", // AFREUM X
        "AGBP", // AFREUM GBP
        "AGEL", // AFREUM GEL
        "AGHS", // AFREUM GHS
        "AGIP", // AFREUM GIP
        "AGIX", // SingularityNET Token
        "AGLD", // Adventure Gold
        "AGMD", // AFREUM GMD
        "AGNF", // AFREUM GNF
        "AGTQ", // AFREUM GTQ
        "AGYD", // AFREUM GYD
        "AHKD", // AFREUM HKD
        "AHNL", // AFREUM HNL
        "AHRK", // AFREUM HRK
        "AHTG", // AFREUM HTG
        "AHUF", // AFREUM HUF
        "AIDOGE", // ArbDoge AI
        "AIDR", // AFREUM IDR
        "AILS", // AFREUM ILS
        "AINR", // AFREUM INR
        "AIOZ", // AIOZ Network
        "AIQD", // AFREUM IQD
        "AIRR", // AFREUM IRR
        "AISK", // AFREUM ISK
        "AJMD", // AFREUM JMD
        "AJOD", // AFREUM JOD
        "AJPY", // AFREUM JPY
        "AKES", // AFREUM KES
        "AKGS", // AFREUM KGS
        "AKHR", // AFREUM KHR
        "AKMF", // AFREUM KMF
        "AKN", // Akoin
        "AKPW", // AFREUM KPW
        "AKRW", // AFREUM KRW
        "AKT", // AKT
        "AKWD", // AFREUM KWD
        "AKYD", // AFREUM KYD
        "AKZT", // AFREUM KZT
        "ALAK", // AFREUM LAK
        "ALBP", // AFREUM LBP
        "ALBT", // AllianceBlock Token
        "ALCX", // Alchemix
        "ALGO", // Algorand
        "ALKR", // AFREUM LKR
        "ALPHA.e", // AlphaToken
        "ALPINE", // ALPINE Fan Token
        "ALRD", // AFREUM LRD
        "ALSL", // AFREUM LSL
        "ALYD", // AFREUM LYD
        "AMAD", // AFREUM MAD
        "AMB", // Apple
        "AMC", // DAAG Certificat/Tracker Perp AMC
        "AMD", // DAAG Certificat/Tracker Perp AMD
        "AMDL", // AFREUM MDL
        "AMGA", // AFREUM MGA
        "AMKD", // AFREUM MKD
        "AMMK", // AFREUM MMK
        "AMNT", // AFREUM MNT
        "AMO", // AMO Coin
        "AMOP", // AFREUM MOP
        "AMRU", // AFREUM MRU
        "AMUR", // AFREUM MUR
        "AMVR", // AFREUM MVR
        "AMWK", // AFREUM MWK
        "AMXN", // AFREUM MXN
        "AMYR", // AFREUM MYR
        "ANAD", // AFREUM NAD
        "ANGN", // AFREUM NGN
        "ANIO", // AFREUM NIO
        "ANOK", // AFREUM NOK
        "ANPR", // AFREUM NPR
        "ANZD", // AFREUM NZD
        "AOMR", // AFREUM OMR
        "APAB", // AFREUM PAB
        "APEN", // AFREUM PEN
        "APGK", // AFREUM PGK
        "APHP", // AFREUM PHP
        "API3", // API3
        "APKR", // AFREUM PKR
        "APLN", // AFREUM PLN
        "APT", // Aptos Token
        "APYG", // AFREUM PYG
        "AQAR", // AFREUM QAR
        "AR", // Arweave
        "ARKM", // Arkham
        "ARON", // AFREUM RON
        "ARSD", // AFREUM RSD
        "ARUB", // AFREUM RUB
        "ARWF", // AFREUM RWF
        "ASAR", // AFREUM SAR
        "ASBD", // AFREUM SBD
        "ASCR", // AFREUM SCR
        "ASDG", // AFREUM SDG
        "ASEK", // AFREUM SEK
        "ASGD", // AFREUM SGD
        "ASHP", // AFREUM SHP
        "ASLL", // AFREUM SLL
        "ASM", // ASSEMBLE
        "ASOS", // AFREUM SOS
        "ASR", // AS Roma
        "ASRD", // AFREUM SRD
        "ASSP", // AFREUM SSP
        "ASTN", // AFREUM STN
        "ASTR", // Astar
        "ASVC", // AFREUM SVC
        "ASYP", // AFREUM SYP
        "ASZL", // AFREUM SZL
        "ATHB", // AFREUM THB
        "ATJS", // AFREUM TJS
        "ATMT", // AFREUM TMT
        "ATND", // AFREUM TND
        "ATOP", // AFREUM TOP
        "ATRY", // AFREUM TRY
        "ATTD", // AFREUM TTD
        "ATWD", // AFREUM TWD
        "ATZS", // AFREUM TZS
        "AUAH", // AFREUM UAH
        "AUGX", // AFREUM UGX
        "AUSD", // AFREUM USD
        "AUYU", // AFREUM UYU
        "AUZS", // AFREUM UZS
        "AVABBC", // Avalanche ABBC
        "AVAX", // Avalanche AVAX
        "AVES", // AFREUM VES
        "AVND", // AFREUM VND
        "AVUV", // AFREUM VUV
        "AWST", // AFREUM WST
        "AXAF", // AFREUM XAF
        "AXCD", // AFREUM XCD
        "AXOF", // AFREUM XOF
        "AXPF", // AFREUM XPF
        "AXSet", // Axie Infinity Shard
        "AYER", // AFREUM YER
        "AZAR", // AFREUM ZAR
        "AZERO", // Aleph Zero
        "AZMW", // AFREUM ZMW
        "AZWL", // AFREUM ZWL
        "Amp", // AMP
        "ApeX", // ApexCoin
        "BABA", // DAAG Certificat/Tracker Perp BABA
        "BABBC", // Binance ABBC
        "BADGER", // Badger
        "BAR", // FC Barcelona
        "BAT.e", // Basic Attention Token
        "BCD", // Bitcoin Diamond
        "BETH", // Beacon ETH
        "BICO", // Biconomy Token
        "BIGTIME", // Big Time
        "BILI", // DAAG Certificat/Tracker Perp BILI
        "BIX", // BIXToken
        "BLD", // Agoric
        "BLUR", // Blur
        "BNB", // Binance Smart Chain
        "BNB-bsc", // Binance Coin
        "BNTX", // DAAG Certificat/Tracker Perp BNTX
        "BOME", // BOOK OF MEME
        "BOND", // BarnBridge
        "BONE", // Bone ShibaSwap
        "BORA", // BORA
        "BORG", // SwissBorg Token
        "BOT", // BOT Token
        "BPD", // Beautiful Princess Disorder
        "BPTC", // Business Platform Tomato Coin
        "BPWR", // BLUE POWER/GENS 0.10
        "BRISE", // Bitgert BRISE
        "BRKA", // DAAG Certificat/Tracker Perp BRK.A
        "BRZ", // BRZ Token
        "BSOL", // BlazeStake Staked SOL
        "BSV", // Bitcoin SV
        "BTC", // Bitcoin
        "BTC.b", // Bitcoin
        "BTSG", // BitSong
        "BUIDL", // BlackRock USD Institutional Digital Liquidity Fund
        "BURGER", // Burger Swap
        "BUSDet", // Binance USD
        "BYND", // DAAG Certificat/Tracker Perp BYND
        "BZX", // Bitcoin Zero
        "Bonk", // Bonk
        "CANTO", // Canto
        "CBETH", // Coinbase Wrapped Staked ETH
        "CCD", // Concordium
        "CDAI", // Compound Dai
        "CFX", // Conflux
        "CGPT", // ChainGPT
        "CH1142754337", // SIX Group/0.125 Bd 20261127 Sr
        "CH1199021903", // Tenity Group/RegSh CHF0.1
        "CH1228837865", // UBS London/2.33 Bd 20251114 Sr
        "CH1232107172", // Citta di Lugano/1.625 Bd 20290201
        "CH1265890678", // Canton of Basel Stadt
        "CH1303238757", // NA Aktionariat
        "CH1306117073", // Canton of Zurich
        "CH1319968462", // Citta di Lugano/1.415 Bd 20340307
        "CH1331113444", // Stadt St Gallen/1.25 Bd 20270308 Sr
        "CH1348614202", // UBS Switzerland/1.5075 MB 20290528
        "CH1353258168", // World Bank/1.1575 Bd 20310611 Sr
        "CHESS", // Chess
        "CHR", // Chromia
        "CKB", // Nervos Network
        "CLV", // Clover
        "CNTC", // Terra Classic CNY
        "COCOS", // CocosTokenV2
        "COIN", // DAAG Certificat/Tracker Perp COIN
        "COMP.e", // Compound
        "COS", // Cats Of Sol
        "COVAL", // CircuitsOfValue
        "CPC", // CryptoPerformance Coin
        "CPR", // COMPANYA CAP/PS 100000
        "CQT", // Covalent Query Token
        "CRE", // CarryToken
        "CREAM", // IceCream Finance
        "CRON", // DAAG Certificat/Tracker Perp CRON
        "CRVUSD", // crvUSD
        "CTSI", // Cartesi Token
        "CTX", // Cryptex
        "CUBE", // Cube Network
        "DAG", // Constellation
        "DAI.e", // Dai Stablecoin
        "DAKS", // Draggable Aktionariat AG Shares
        "DATA", // Streamr
        "DAWN", // Dawn Protocol
        "DBTK", // DigiBank DBTK Token
        "DE000A30V6H0", // SIEMENS AG/3.531 IHS 20240213 USEC
        "DIA", // DIAToken
        "DINC", // Dinarcoin
        "DKA", // dKargo
        "DNT", // district0x Network Token
        "DOGE", // Dogecoin
        "DOT", // Polkadot DOT
        "ECOx", // ECOx
        "EDGT", // Edgecoin
        "ENA", // ENA
        "ENG", // Enigma
        "ENTC", // ENTERBUTTON
        "EPX", // Ellipsis X
        "ERN", // @EthernityChain $ERN Token
        "ETC", // Ethereum Classic Ether
        "ETH", // Ethereum Ether
        "ETHFI", // ether.fi governance token
        "ETHW", // EthereumPoW
        "ETN", // Electroneum
        "EUL", // Euler
        "EURA", // Euro Electronic Money Token
        "EURC", // Euro Coin
        "EURR", // StablR Euro
        "EURS", // STASIS EURS Token
        "EURX", // Euro Cash Electronic Money Token
        "EURt7", // LCX/7 Bd 20300201 Sub Unsec
        "EUTC", // Terra Classic EUR
        "EWT", // Energy Web Token
        "EXFI", // Experimental Finance Token
        "FABBC", // Fantom ABBC
        "FARM", // FARM Reward Token
        "FCT", // [FCT] FirmaChain Token
        "FIDA", // Bonfida
        "FIL", // Filecoin
        "FIRO", // Firo
        "FIS", // StaFi
        "FLEX", // FLEX Coin
        "FLOW", // Flow
        "FLR", // Flare
        "FLX", // Flux Token
        "FLZ", // Fellaz
        "FOX", // FOX
        "FR0014003521", // European Invest/Zero Cpn Bd
        "FRGX", // FRGX
        "FRP", // FAME REWARD PLUS
        "FTN", // Fasttoken
        "FUN", // FunFair
        "FUSE", // Fuse
        "FX", // Function X
        "Floki", // Baby Moon Floki
        "G-CRE", // Gluwa Creditcoin Vesting Token
        "GBTC", // Terra Classic GBP
        "GCN", // Gascoin
        "GEMS", // AlgoGems
        "GFI", // Goldfinch
        "GGP", // Geegoopuzzle
        "GLMR", // Moonbeam
        "GLXY", // DAAG Certificat/Tracker Perp GLXY
        "GNS", // Gains Network
        "GNT", // Golem Network Token
        "GODS", // Gods Unchained
        "GOOGL", // DAAG Certificat/Tracker Perp GOOGL
        "GPT", // QnA3.AI Token
        "GREBII", // GREENROCK EN/VAR BD OE
        "GRT.e", // Graph Token
        "GST", // GreenSatoshiToken
        "GTU", // Global Trade Unit
        "HAPI", // HAPI
        "HBAR", // Hedera Hashgraph HBAR
        "HBCH", // Heco-Peg HBCH Token
        "HBD", // Hive Dollar
        "HBSV", // Huobi BSV
        "HDL", // HEADLINE
        "HDOT", // Heco-Peg HDOT Token
        "HFIL", // Heco-Peg HFIL Token
        "HFT", // Hashflow
        "HIFI", // Hifi Finance
        "HIVE", // Hive
        "HK0000895216", // HKSAR GOVT/4.05 NT 20240216 UNSEC
        "HK0000963279", // HKSAR/FR BD 20260126 UNSEC
        "HK0000963287", // HKSAR/FR BD 20260126 UNSEC
        "HK0000963295", // HKSAR/FR BD 20260126 UNSEC
        "HK0000976420", // HKSAR/FR BD 20260202 UNSEC
        "HLTC", // Heco-Peg HLTC Token
        "HOOK", // Hooked Protocol
        "HOP", // Hop
        "HUNT", // HuntToken
        "ICP", // Internet Computer Token
        "ICX", // ICON
        "IDEX", // IDEX Token
        "INTC", // DAAG Certificat/Tracker Perp INTC
        "INV", // Inverse DAO
        "IOST", // IOST
        "IPX", // InpulseX
        "JAM", // Geojam
        "JASMY", // JasmyCoin
        "JBL", // JuniorBaseballLeague
        "JEWEL", // DFK Subnet JEWEL
        "JITOSOL", // Jito Staked SOL
        "JLP", // Jupiter Perps LP
        "JPTC", // Terra Classic JPY
        "JST", // JUST
        "JTO", // Jito
        "JUST", // DAAG Certificat/Tracker Perp JUST
        "JUV", // Juventus
        "KAI", // Kardia Chain
        "KAS", // Kaspa
        "KCC", // KCC
        "KDA", // Kadena
        "KEY", // SelfKey
        "KOK", // KOK Coin
        "KRL", // Kryll
        "KRTC", // Terra Classic KRW
        "KSM", // Kusama
        "L-BTC", // Bitcoin Liquid
        "LAYR", // Composable Finance
        "LAZIO", // FC Lazio Fan Token
        "LBA", // LibraToken
        "LCX", // LCX
        "LEND", // EthLend Token
        "LEVER", // LeverFi
        "LINK.e", // Chainlink Token
        "LOKA", // League of Kingdoms Arena
        "LOOKS", // LooksRare Token
        "LQTY", // Liquity
        "LTC", // Litecoin
        "LTX", // Lattice Token
        "LU2542747121", // EUROP.INVEST.BK/2.507 BD 20241129
        "LU2557886475", // EUROP.INVEST.BK/VAR BD 20250203
        "LU2637450516", // EUROP.INVEST.BK/BD 20250619
        "LUNC", // Terra Classic
        "LUSD", // LUSD Stablecoin
        "LYXe", // LUKSO Token
        "MABBC", // Matic ABBC
        "MAID", // MaidSafeCoin
        "MATIC", // Polygon Matic
        "MATICet", // Matic
        "MATICpo", // Matic
        "MBL", // MovieBloc
        "MBOX", // Mobox
        "MC314", // MANCIPI
        "MCO", // Monaco
        "MCO2", // Moss Carbon Credit
        "METGGSDA", // MET.GL.GR.SU./ CL DA
        "METIS", // Metis Andromeda
        "MEW", // cat in a dogs world
        "MILK", // MILK
        "MIM", // Magic Internet Money
        "MKR.e", // Maker
        "MLC", // MELE
        "MLN", // Melon Token
        "MMT", // MyMetaTrader
        "MNT", // Mantle
        "MNTC", // Terra Classic MNT
        "MODE", // Mode
        "MONA", // MonaCoin
        "MONI", // Monsta Infinite Token
        "MOVR", // Moonriver
        "MRNA", // DAAG Certificat/Tracker Perp MRNA
        "MSFT", // DAAG Certificat/Tracker Perp MSFT
        "MSTR", // DAAG Certificat/Tracker Perp MSTR
        "MTL", // Metal
        "MTR", // Meter
        "MV", // Metaverse
        "MX", // MX Token
        "MeMe", // MeMe
        "NAS", // Nebulas
        "NEAR", // NEAR Protocol
        "NEON", // NEON EVM
        "NFLX", // DAAG Certificat/Tracker Perp NFLX
        "NFTN", // NFTNetwork
        "NIM", // Nimiq
        "NIO", // DAAG Certificat/Tracker Perp NIO
        "NMR", // Numeraire
        "NOK", // DAAG Certificat/Tracker Perp NOK
        "NOTE", // Note
        "NPXS", // Pundi X Token
        "NU", // NuCypher
        "NUM", // NUM Token
        "NVDA", // DAAG Certificat/Tracker Perp NVDA
        "NXRA", // AllianceBlock Nexera Token
        "OCEAN", // Ocean Token
        "OCT", // Octopus Network Token
        "OG", // OG
        "OGN", // OriginToken
        "OKT", // OKC Token
        "OMI", // OMI Token
        "ONDO", // Ondo
        "ONG", // Ontology Gas
        "ONGAS", // Ontology Gas
        "OOKI", // Ooki Token
        "OPT", // OptionFlowToken
        "ORAI", // Oraichain Token
        "ORBR", // Orbler
        "ORCA", // Orca
        "OXT", // Orchid
        "PAI", // Project Pai
        "PAX", // Paxos Standard
        "PCI", // Paycoin
        "PDT", // Paragons DAO Token
        "PENN", // DAAG Certificat/Tracker Perp PENN
        "PEPE2.0", // Pepe 2.0
        "PEPEBOMB", // pepe
        "PFE", // DAAG Certificat/Tracker Perp PFE
        "PHA", // Phala
        "PHB", // Phoenix Global
        "PICKLE", // PickleToken
        "PIG", // Pigcoin
        "PIVX", // PIVX
        "PNT", // pNetwork Token
        "POL", // Polygon Ecosystem Token
        "POLA", // Polaris Share
        "POLS", // PolkastarterToken
        "POLY", // Polymath
        "POPCAT", // POPCAT
        "PORK", // PepeFork
        "PORTAL", // PORTAL
        "PORTO", // FC Porto Fan Token
        "POWR", // PowerLedger
        "PRQ", // Parsiq Token
        "PUNDIX", // Pundi X Token
        "PYPL", // DAAG Certificat/Tracker Perp PYPL
        "PYTH", // Pyth Network
        "Planets", // PLANET
        "QKC", // QuarkChain
        "QRDO", // Qredo Token
        "QSP", // Quantstamp
        "QTF", // Quantfury Token
        "QTUM", // Qtum
        "RAD", // Radicle
        "RAI", // Rai Reflex Index
        "RARI", // Rarible
        "RBN", // Ribbon
        "RBTC", // Rootstock Smart Bitcoin
        "RCN", // Ripio Credit Network Token
        "REP", // Reputation
        "REPv2", // Reputation
        "REQ", // Request Token
        "REZ", // Renzo
        "RFR", // Refereum
        "RGT", // Rari Governance Token
        "RIO", // Realio Network
        "RLC", // iEx.ec Network Token
        "ROA", // ROA CORE
        "RON", // Ronin
        "ROOK", // ROOK
        "ROW", // RageOnWheels
        "RVN", // Ravencoin
        "S17A", // TIGRIS IMMO/GENS 500
        "SAED", // AFREUM STABLE AED
        "SAFE", // Safe Token
        "SAFN", // AFREUM STABLE AFN
        "SALL", // AFREUM STABLE ALL
        "SAMD", // AFREUM STABLE AMD
        "SANG", // AFREUM STABLE ANG
        "SANTOS", // FC Santos Fan Token
        "SAOA", // AFREUM STABLE AOA
        "SARS", // AFREUM STABLE ARS
        "SAUD", // AFREUM STABLE AUD
        "SAWG", // AFREUM STABLE AWG
        "SAZN", // AFREUM STABLE AZN
        "SBAM", // AFREUM STABLE BAM
        "SBBD", // AFREUM STABLE BBD
        "SBD", // Steem Dollars
        "SBDT", // AFREUM STABLE BDT
        "SBGN", // AFREUM STABLE BGN
        "SBHD", // AFREUM STABLE BHD
        "SBIF", // AFREUM STABLE BIF
        "SBMD", // AFREUM STABLE BMD
        "SBND", // AFREUM STABLE BND
        "SBOB", // AFREUM STABLE BOB
        "SBRL", // AFREUM STABLE BRL
        "SBSD", // AFREUM STABLE BSD
        "SBTN", // AFREUM STABLE BTN
        "SBWP", // AFREUM STABLE BWP
        "SBYN", // AFREUM STABLE BYN
        "SBZD", // AFREUM STABLE BZD
        "SCAD", // AFREUM STABLE CAD
        "SCDF", // AFREUM STABLE CDF
        "SCHF", // AFREUM STABLE CHF
        "SCLP", // AFREUM STABLE CLP
        "SCNY", // AFREUM STABLE CNY
        "SCOP", // AFREUM STABLE COP
        "SCRC", // AFREUM STABLE CRC
        "SCROOGE", // SCROOGE
        "SCUP", // AFREUM STABLE CUP
        "SCVE", // AFREUM STABLE CVE
        "SCZK", // AFREUM STABLE CZK
        "SD", // Stader
        "SDJF", // AFREUM STABLE DJF
        "SDKK", // AFREUM STABLE DKK
        "SDOP", // AFREUM STABLE DOP
        "SDTC", // Terra Classic SDR
        "SDZD", // AFREUM STABLE DZD
        "SEGP", // AFREUM STABLE EGP
        "SENSO", // Sensorium
        "SERN", // AFREUM STABLE ERN
        "SETB", // AFREUM STABLE ETB
        "SEUR", // AFREUM STABLE EUR
        "SFJD", // AFREUM STABLE FJD
        "SFKP", // AFREUM STABLE FKP
        "SFM", // SafeMoon
        "SFP", // SafePal Token
        "SGB", // Songbird
        "SGBP", // AFREUM STABLE GBP
        "SGEL", // AFREUM STABLE GEL
        "SGHS", // AFREUM STABLE GHS
        "SGIP", // AFREUM STABLE GIP
        "SGMD", // AFREUM STABLE GMD
        "SGNF", // AFREUM STABLE GNF
        "SGTQ", // AFREUM STABLE GTQ
        "SGYD", // AFREUM STABLE GYD
        "SHKD", // AFREUM STABLE HKD
        "SHNL", // AFREUM STABLE HNL
        "SHPING", // Shping Coin
        "SHRK", // AFREUM STABLE HRK
        "SHTG", // AFREUM STABLE HTG
        "SHUF", // AFREUM STABLE HUF
        "SID", // SIDO IMMO/GENS 1000
        "SIDR", // AFREUM STABLE IDR
        "SILS", // AFREUM STABLE ILS
        "SINR", // AFREUM STABLE INR
        "SIQD", // AFREUM STABLE IQD
        "SIRR", // AFREUM STABLE IRR
        "SISK", // AFREUM STABLE ISK
        "SJMD", // AFREUM STABLE JMD
        "SJOD", // AFREUM STABLE JOD
        "SJPY", // AFREUM STABLE JPY
        "SKES", // AFREUM STABLE KES
        "SKGS", // AFREUM STABLE KGS
        "SKHR", // AFREUM STABLE KHR
        "SKL", // SKALE
        "SKMF", // AFREUM STABLE KMF
        "SKPW", // AFREUM STABLE KPW
        "SKRW", // AFREUM STABLE KRW
        "SKWD", // AFREUM STABLE KWD
        "SKYD", // AFREUM STABLE KYD
        "SKZT", // AFREUM STABLE KZT
        "SLAK", // AFREUM STABLE LAK
        "SLBP", // AFREUM STABLE LBP
        "SLERF", // SLERF
        "SLKR", // AFREUM STABLE LKR
        "SLRD", // AFREUM STABLE LRD
        "SLSL", // AFREUM STABLE LSL
        "SLYD", // AFREUM STABLE LYD
        "SMAD", // AFREUM STABLE MAD
        "SMDL", // AFREUM STABLE MDL
        "SMGA", // AFREUM STABLE MGA
        "SMKD", // AFREUM STABLE MKD
        "SMMK", // AFREUM STABLE MMK
        "SMNT", // AFREUM STABLE MNT
        "SMOP", // AFREUM STABLE MOP
        "SMR", // Shimmer
        "SMRU", // AFREUM STABLE MRU
        "SMUR", // AFREUM STABLE MUR
        "SMVR", // AFREUM STABLE MVR
        "SMWK", // AFREUM STABLE MWK
        "SMXN", // AFREUM STABLE MXN
        "SMYR", // AFREUM STABLE MYR
        "SMZN", // AFREUM STABLE MZN
        "SNAD", // AFREUM STABLE NAD
        "SNGN", // AFREUM STABLE NGN
        "SNIO", // AFREUM STABLE NIO
        "SNM", // SONM
        "SNOK", // AFREUM STABLE NOK
        "SNPR", // AFREUM STABLE NPR
        "SNX.e", // Synthetix Network Token
        "SNZD", // AFREUM STABLE NZD
        "SOL", // Solana SOL
        "SOLA", // SOLA Token
        "SOLO", // Sologenic
        "SOMR", // AFREUM STABLE OMR
        "SPA", // Sperax
        "SPAB", // AFREUM STABLE PAB
        "SPEN", // AFREUM STABLE PEN
        "SPGK", // AFREUM STABLE PGK
        "SPHP", // AFREUM STABLE PHP
        "SPKR", // AFREUM STABLE PKR
        "SPLN", // AFREUM STABLE PLN
        "SPYG", // AFREUM STABLE PYG
        "SQ", // DAAG Certificat/Tracker Perp SQ Sub
        "SQAR", // AFREUM STABLE QAR
        "SRON", // AFREUM STABLE RON
        "SRSD", // AFREUM STABLE RSD
        "SRUB", // AFREUM STABLE RUB
        "SRWF", // AFREUM STABLE RWF
        "SSAR", // AFREUM STABLE SAR
        "SSBD", // AFREUM STABLE SBD
        "SSCR", // AFREUM STABLE SCR
        "SSDG", // AFREUM STABLE SDG
        "SSEK", // AFREUM STABLE SEK
        "SSGD", // AFREUM STABLE SGD
        "SSHP", // AFREUM STABLE SHP
        "SSLL", // AFREUM STABLE SLL
        "SSOS", // AFREUM STABLE SOS
        "SSRD", // AFREUM STABLE SRD
        "SSSP", // AFREUM STABLE SSP
        "SSTN", // AFREUM STABLE STN
        "SSV", // ssv.network
        "SSVC", // AFREUM STABLE SVC
        "SSX", // SOMESING
        "SSYP", // AFREUM STABLE SYP
        "SSZL", // AFREUM STABLE SZL
        "STEEM", // Steem
        "STHB", // AFREUM STABLE THB
        "STJS", // AFREUM STABLE TJS
        "STMT", // AFREUM STABLE TMT
        "STND", // AFREUM STABLE TND
        "STOP", // AFREUM STABLE TOP
        "STORJ", // StorjToken
        "STPT", // STPT
        "STRAX", // Stratis
        "STRY", // AFREUM STABLE TRY
        "STTD", // AFREUM STABLE TTD
        "STWD", // AFREUM STABLE TWD
        "STX", // Stacks
        "STZS", // AFREUM STABLE TZS
        "SUAH", // AFREUM STABLE UAH
        "SUGX", // AFREUM STABLE UGX
        "SUKU", // SUKU
        "SUNOLD", // SUNOLD
        "SUSD", // AFREUM STABLE USD
        "SUYU", // AFREUM STABLE UYU
        "SUZS", // AFREUM STABLE UZS
        "SVES", // AFREUM STABLE VES
        "SVND", // AFREUM STABLE VND
        "SVUV", // AFREUM STABLE VUV
        "SWEAT", // Sweat Economy
        "SWRV", // Swerve DAO Token
        "SWST", // AFREUM STABLE WST
        "SX", // SX Network
        "SXAF", // AFREUM STABLE XAF
        "SXCD", // AFREUM STABLE XCD
        "SXOF", // AFREUM STABLE XOF
        "SXPF", // AFREUM STABLE XPF
        "SYER", // AFREUM STABLE YER
        "SYS", // Syscoin
        "SZAR", // AFREUM STABLE ZAR
        "SZMW", // AFREUM STABLE ZMW
        "SZWL", // AFREUM STABLE ZWL
        "TBONDS01", // SwarmX/Struct Perp Fds Sr Unsec
        "TBONDS13", // SwarmX/Struct Perp Fds Sr Unsec
        "TFUEL", // TFUEL
        "TITAN", // IRON Titanium Token
        "TKO", // Tokocrypto Token
        "TLRY", // DAAG Certificat/Tracker Perp TLRY
        "TNSR", // Tensor
        "TOMI", // tomi Token
        "TOMO", // Viction
        "TOMOB", // TomoChain
        "TOMOE", // TomoChain
        "TON", // Toncoin
        "TRAC", // Trace Token
        "TRIBE", // Tribe
        "TRIBL", // Tribal Token
        "TROY", // TROY
        "TRX", // TRON TRX
        "TRY", // TRYfinance
        "TSM", // DAAG Certificat/Tracker Perp TSM
        "TT-USDC", // TT-USDC
        "TT-USDT", // TT-USDT
        "TURBO", // Turbo
        "TVK", // Virtua
        "Titan", // TitanSwap
        "UBER", // DAAG Certificat/Tracker Perp UBER
        "UBT", // UniBright
        "UMA", // UMA Voting Token v1
        "UMA.e", // UMA Voting Token v1
        "UNI.e", // Uniswap
        "UNIW", // UniWswap
        "UPBTC", // Universal Bitcoin
        "UPCO2", // Universal Carbon
        "UPEUR", // Universal Euro
        "UPP", // SENTINEL PROTOCOL
        "UPT", // Universal Protocol Token
        "UPUSD", // Universal US Dollar
        "UPXAU", // Universal Gold
        "UQC", // Uquid Coin
        "USDC.eth", // Wrapped USDC from Ethereum
        "USDCE", // USD Coin Bridged
        "USDCLEGACY", // USD Coin
        "USDE", // USDe
        "USDK", // USDK
        "USDL", // Lift Dollar
        "USDM", // Mountain Protocol USD
        "USDT-PPT", // USDT Crosschain Token
        "USDT.e", // Tether USD
        "USDT.eth", // Wrapped USDT from Ethereum on Meter
        "VCO", // VCOIN
        "VITA", // VitaDAO
        "VIVA", // Viva Classic
        "VLX", // Velas
        "VOW", // Vow
        "VOXEL", // VOXEL Token
        "VRA", // Verasity
        "VXX", // DAAG Certificat/Tracker Perp VXX
        "WABBC", // Wrapped ABBC
        "WAN", // Wanchain
        "WAR", // Wrapped AR
        "WAXP", // WAX
        "WBCD", // Wrapped Bitcoin Diamond
        "WCFX", // Wrapped Conflux
        "WE", // WeBuy
        "WEN", // Wen
        "WETC", // Wrapped Ether
        "WETH.e", // Wrapped Ether
        "WETH.eth", // Wrapped ETH from Ethereum
        "WETHW", // Wrapped ETHPoW
        "WFITFI", // Wrapped FITFI
        "WFLOW", // Wrapped Flow
        "WHBAR", // Wrapped HBAR
        "WICC", // Waykichain
        "WIF", // dogwifhat
        "WMOC", // Moss Coin
        "WOJAK", // Wojak
        "WONE", // Wrapped ONE
        "WOO.e", // Wootrade Network
        "WPCI", // Wrapped PCI
        "WPEPE", // Wrapped Pepe
        "WPLS", // Wrapped Pulse
        "WRON", // Wrapped Ronin
        "WSM", // Wall Street Memes
        "WTC", // Walton Token
        "WTR", // Water
        "WTRX", // Wrapped TRX
        "WXMR", // Wrapped Monero
        "WZEN", // Wrapped ZEN
        "XCH", // Chia
        "XCHF", // CryptoFranc
        "XDATA", // Streamr (old)
        "XDB", // digitalbits
        "XDC", // XinFin Network
        "XDCE", // XinFin XDCE
        "XEM", // NEM
        "XET", // Xfinite Entertainment Token
        "XGLI", // Glitter Finance
        "XHV", // Haven Protocol
        "XLM", // Stellar Lumen
        "XMR", // Monero XMR
        "XOR", // Sora XOR
        "XRP", // Ripple XRP
        "XS2615318289", // INTERNATIONAL B/3.399EMTN 20261023
        "XSGD", // XSGD
        "XT", // XT Token
        "XYM", // Symbol
        "XYO", // XY Oracle
        "YFI.e", // yearn.finance
        "ZEN", // Horizen
        "ZERO", // ZERO
        "ZEUS", // ZEUS
        "ZM", // DAAG Certificat/Tracker Perp ZM Sub
        "ZRP", // Zapit Reward Points
        "ZRX.e", // ZRX
        "aUSDT", // aUSDT
        "atUST", // UST Terra
        "axlWMATIC", // Wrapped Matic
        "bb-a-USDC", // Balancer Aave Boosted Pool (USDC)
        "bb-a-USDT", // Balancer Aave Boosted Pool (USDT)
        "bcUSDC", // BlockNG-Peg USDC Token
        "bcUSDT", // BlockNG-Peg USDT Token
        "bwJUP", // BSC Wrapped Jupiter
        "cETH", // Compound Ether
        "cUSDC", // Compound USD Coin
        "cbETH", // Coinbase Wrapped Staked ETH
        "ceUSDC", // USD Coin (Celer)
        "ethUSDC", // USD Coin on Elastos
        "ioETH", // Wrapped Ether
        "ioUSDC", // USD Coin
        "ioUSDT", // Tether USD
        "ioWBTC", // Wrapped Bitcoin
        "jDAI", // Dai
        "jUSDC", // USD Coin
        "jWBTC", // Wrapped BTC
        "lisUSD", // Lista USD
        "m.USDC", // USDC Token
        "m.USDT", // USDT Token
        "mADA", // Milkomeda C1
        "milkALGO", // Milkomeda A1
        "oUSDC", // Orbit Bridge Ton USD Coin
        "oUSDT", // Orbit Bridge Ton USD Tether
        "pCKB", // Godwoken
        "pONT", // Poly Ontology Token
        "pUSDt", // TetherToken
        "pWING", // Poly Ontology Wing Token
        "pogai", // POGAI
        "sTETH", // stakedETH
        "soETH", // Wrapped Ethereum
        "soFTT", // Wrapped FTT
        "soLINK", // Wrapped Chainlink
        "soSUSHI", // Wrapped SUSHI
        "token-wbtc", // Wrapped Bitcoin
        "token-wstx", // Wrapped Stacks
        "vADA", // Venus ADA
        "vBNB", // Venus BNB
        "vBTC", // Venus BTC
        "vBUSD", // Venus BUSD
        "vETH", // Venus ETH
        "vUSDC", // Venus USDC
        "vUSDT", // Venus USDT
        "wCFG", // Wrapped Centrifuge
        "wNXM", // Wrapped NXM
        "wXLM", // Wrapped Stellar Lumens
        "xAI", // xAI
        "xALGO", // Wrapped ALGO
        "xDAI", // Gnosis Chain
    )
}
