/*
 * This file is part of the Money package.
 *
 * Copyright (c) Eriksen Costa <eriksencosta@gmail.com>
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

/*
 * This file was auto-generated by running the "generateCryptoCurrenciesDataClasses" Gradle task. Always run the
 * task after a DTI database update.
 */

package com.eriksencosta.money.currency.crypto.data

// 50 currencies
@Suppress("StringLiteralDuplication")
internal class CurrenciesLookup17 {
    val currencies: Map<String, String> get() = mapOf(
        "XDC" to "CCQZQXFDC", // XinFin Network available in CurrenciesData17
        "XDCE" to "SRNJBLCPX", // XinFin XDCE available in CurrenciesData38
        "XEM" to "5WTDXDVL2", // NEM available in CurrenciesData8
        "XET" to "QBGXW5RWK", // Xfinite Entertainment Token available in CurrenciesData34
        "XGLI" to "DXS7K41RV", // Glitter Finance available in CurrenciesData19
        "XHV" to "JQ43814PC", // Haven Protocol available in CurrenciesData26
        "XOR" to "RS9HR8QCK", // Sora XOR available in CurrenciesData37
        "XS2615318289" to "J0D6B3L47", // INTERNATIONAL B/3.399EMTN 20261023 available in CurrenciesData24
        "XSGD" to "7496MZP2C", // XSGD available in CurrenciesData10
        "XT" to "J3ZLNM7HL", // XT Token available in CurrenciesData25
        "XYM" to "NPMVTRQ2X", // Symbol available in CurrenciesData32
        "XYO" to "TJ40H4L9S", // XY Oracle available in CurrenciesData39
        "YFI.e" to "B960VD22D", // yearn.finance available in CurrenciesData15
        "ZEN" to "LKG80JV60", // Horizen available in CurrenciesData29
        "ZERO" to "1CFNM04RC", // ZERO available in CurrenciesData1
        "ZEUS" to "TWJVSFWL0", // ZEUS available in CurrenciesData40
        "ZM" to "4K3C24LR5", // DAAG Certificat/Tracker Perp ZM Sub available in CurrenciesData6
        "ZRP" to "9GXVVGV87", // Zapit Reward Points available in CurrenciesData14
        "ZRX.e" to "GRQRQJ7H6", // ZRX available in CurrenciesData22
        "aUSDT" to "TTC7MQ9FW", // aUSDT available in CurrenciesData40
        "atUST" to "4MS00KZWV", // UST Terra available in CurrenciesData6
        "axlWMATIC" to "73THRBGS1", // Wrapped Matic available in CurrenciesData10
        "bb-a-USDC" to "NC5HMPH1L", // Balancer Aave Boosted Pool (USDC) available in CurrenciesData32
        "bb-a-USDT" to "9X1Z1NQG5", // Balancer Aave Boosted Pool (USDT) available in CurrenciesData15
        "bcUSDC" to "7NCQ6LHB3", // BlockNG-Peg USDC Token available in CurrenciesData11
        "bcUSDT" to "MRWMZXF10", // BlockNG-Peg USDT Token available in CurrenciesData31
        "bwJUP" to "PM4248QB4", // BSC Wrapped Jupiter available in CurrenciesData34
        "cETH" to "9HFWRMTZ9", // Compound Ether available in CurrenciesData14
        "cUSDC" to "MH7QMBCVF", // Compound USD Coin available in CurrenciesData30
        "cbETH" to "X82R2ZQC8", // Coinbase Wrapped Staked ETH available in CurrenciesData43
        "ceUSDC" to "D608V9MJ1", // USD Coin (Celer) available in CurrenciesData18
        "ethUSDC" to "PH8TSHXS5", // USD Coin on Elastos available in CurrenciesData33
        "ioETH" to "SJ1T9WHMM", // Wrapped Ether available in CurrenciesData38
        "ioUSDC" to "QT93Q5KF0", // USD Coin available in CurrenciesData35
        "ioUSDT" to "8WH8526LF", // Tether USD available in CurrenciesData13
        "ioWBTC" to "F1CB20TJZ", // Wrapped Bitcoin available in CurrenciesData20
        "jDAI" to "RC9WGGMXC", // Dai available in CurrenciesData36
        "jUSDC" to "3KMQGXCWL", // USD Coin available in CurrenciesData5
        "jWBTC" to "5XVNTL2F4", // Wrapped BTC available in CurrenciesData8
        "lisUSD" to "M3F870ZJJ", // Lista USD available in CurrenciesData30
        "m.USDC" to "CHTHF56TG", // USDC Token available in CurrenciesData17
        "m.USDT" to "VKNCKMZXB", // USDT Token available in CurrenciesData41
        "mADA" to "X851DCW19", // Milkomeda C1 available in CurrenciesData43
        "milkALGO" to "17GWTST28", // Milkomeda A1 available in CurrenciesData1
        "oUSDC" to "9DH9PWVFT", // Orbit Bridge Ton USD Coin available in CurrenciesData14
        "oUSDT" to "LZ9TRNQXQ", // Orbit Bridge Ton USD Tether available in CurrenciesData29
        "pCKB" to "K44NX5WJ7", // Godwoken available in CurrenciesData26
        "pONT" to "RZX4Q73H3", // Poly Ontology Token available in CurrenciesData37
        "pUSDt" to "PJ1BC8W44", // TetherToken available in CurrenciesData33
        "pWING" to "60WV8HCPT", // Poly Ontology Wing Token available in CurrenciesData9
    )
}
