/*
 * This file is part of the Money package.
 *
 * Copyright (c) Eriksen Costa <eriksencosta@gmail.com>
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

/*
 * This file was auto-generated by running the "generateCryptoCurrenciesDataClasses" Gradle task. Always run the
 * task after a DTI database update.
 */

package com.eriksencosta.money.currency.crypto.data

// 50 currencies
@Suppress("StringLiteralDuplication")
internal class CurrenciesLookup3 {
    val currencies: Map<String, String> get() = mapOf(
        "AKPW" to "P7JMF863J", // AFREUM KPW available in CurrenciesData33
        "AKRW" to "ZFWL1RK29", // AFREUM KRW available in CurrenciesData45
        "AKT" to "DKRZN4PQW", // AKT available in CurrenciesData19
        "AKWD" to "JLGWL4R1R", // AFREUM KWD available in CurrenciesData25
        "AKYD" to "R4QJQRQNJ", // AFREUM KYD available in CurrenciesData36
        "AKZT" to "9FQC6M44R", // AFREUM KZT available in CurrenciesData14
        "ALAK" to "FRRW9S9KR", // AFREUM LAK available in CurrenciesData21
        "ALBP" to "7F16CLJ2C", // AFREUM LBP available in CurrenciesData11
        "ALBT" to "PSTHR9DXT", // AllianceBlock Token available in CurrenciesData34
        "ALCX" to "HRJ0ZBW0D", // Alchemix available in CurrenciesData24
        "ALGO" to "M8Z9JSG9Q", // Algorand available in CurrenciesData30
        "ALKR" to "M45J5XBWF", // AFREUM LKR available in CurrenciesData30
        "ALPHA.e" to "HX4LPG01H", // AlphaToken available in CurrenciesData24
        "ALPINE" to "9V66W5M31", // ALPINE Fan Token available in CurrenciesData14
        "ALRD" to "8CMH9Q7QM", // AFREUM LRD available in CurrenciesData12
        "ALSL" to "K2RWK5VN2", // AFREUM LSL available in CurrenciesData26
        "ALYD" to "13T549QT3", // AFREUM LYD available in CurrenciesData1
        "AMAD" to "WK55D5NB8", // AFREUM MAD available in CurrenciesData42
        "AMB" to "GDBFM94L0", // Apple available in CurrenciesData21
        "AMC" to "WCRQ5K6JB", // DAAG Certificat/Tracker Perp AMC available in CurrenciesData42
        "AMD" to "JR59F418X", // DAAG Certificat/Tracker Perp AMD available in CurrenciesData26
        "AMDL" to "R1KHLJ2BS", // AFREUM MDL available in CurrenciesData36
        "AMGA" to "744KKCK2N", // AFREUM MGA available in CurrenciesData10
        "AMKD" to "K9J23ZSX5", // AFREUM MKD available in CurrenciesData27
        "AMMK" to "LB2MSD4FS", // AFREUM MMK available in CurrenciesData28
        "AMNT" to "9BG3JZN4C", // AFREUM MNT available in CurrenciesData14
        "AMO" to "RKQK5M4KJ", // AMO Coin available in CurrenciesData36
        "AMOP" to "X15WLXLTJ", // AFREUM MOP available in CurrenciesData43
        "AMRU" to "2XTW9RV1V", // AFREUM MRU available in CurrenciesData4
        "AMUR" to "DTPJKFLST", // AFREUM MUR available in CurrenciesData19
        "AMVR" to "M0NHKRD19", // AFREUM MVR available in CurrenciesData29
        "AMWK" to "4Q1NFZLDQ", // AFREUM MWK available in CurrenciesData7
        "AMXN" to "J56NVCVJN", // AFREUM MXN available in CurrenciesData25
        "AMYR" to "G00RGKXM8", // AFREUM MYR available in CurrenciesData21
        "ANAD" to "7WRD7TJGW", // AFREUM NAD available in CurrenciesData11
        "ANGN" to "KP640Z19W", // AFREUM NGN available in CurrenciesData27
        "ANIO" to "XG0CNRQ6P", // AFREUM NIO available in CurrenciesData43
        "ANOK" to "MP6ZH948T", // AFREUM NOK available in CurrenciesData30
        "ANPR" to "5MJBHM6D9", // AFREUM NPR available in CurrenciesData8
        "ANZD" to "JW3C16B06", // AFREUM NZD available in CurrenciesData26
        "AOMR" to "41X0XL7NC", // AFREUM OMR available in CurrenciesData5
        "APAB" to "96K9NX7DV", // AFREUM PAB available in CurrenciesData13
        "APEN" to "84GBB5KK6", // AFREUM PEN available in CurrenciesData12
        "APGK" to "RSD6624S3", // AFREUM PGK available in CurrenciesData37
        "APHP" to "TVDFR4GBX", // AFREUM PHP available in CurrenciesData40
        "API3" to "QFRLW96WD", // API3 available in CurrenciesData35
        "APKR" to "DDW2PVLH4", // AFREUM PKR available in CurrenciesData19
        "APLN" to "T8TPN2450", // AFREUM PLN available in CurrenciesData39
        "APYG" to "H4WQ8DMKS", // AFREUM PYG available in CurrenciesData23
        "AQAR" to "RW8JS11D7", // AFREUM QAR available in CurrenciesData37
    )
}
