/*
 * This file is part of the Money package.
 *
 * Copyright (c) Eriksen Costa <eriksencosta@gmail.com>
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

/*
 * This file was auto-generated by running the "generateCryptoCurrenciesDataClasses" Gradle task. Always run the
 * task after a DTI database update.
 */

package com.eriksencosta.money.currency.crypto.data

import com.eriksencosta.money.currency.CurrencyData

// 50 currencies
@Suppress("MagicNumber", "MaxLineLength", "StringLiteralDuplication")
internal class CurrenciesData33 {
    val currencies: Map<String, CurrencyData> get() = mapOf(
        "NV703NKLG" to CurrencyData("NV703NKLG", "USDM", "Mountain Protocol USD", "USDM", "AUXILIARY", 18),
        "NVD7LRM61" to CurrencyData("NVD7LRM61", "ROSE", "Oasis Network", "ROSE", "NATIVE", 18),
        "NVQLHF357" to CurrencyData("NVQLHF357", "COMP", "Compound", "COMP", "AUXILIARY", 18),
        "NVVJ0PSWD" to CurrencyData("NVVJ0PSWD", "CTXC", "Cortex Coin", "CTXC", "AUXILIARY", 18),
        "NW8GGH7MN" to CurrencyData("NW8GGH7MN", "EDGT", "Edgecoin", "EDGT", "AUXILIARY", 7),
        "NWFNWKHJN" to CurrencyData("NWFNWKHJN", "USDC.e", "USD Coin", "USDC.e", "AUXILIARY", 6),
        "NWXBKPRXC" to CurrencyData("NWXBKPRXC", "XETA", "XANA", "XETA", "AUXILIARY", 18),
        "NXQZFP4PT" to CurrencyData("NXQZFP4PT", "ANKR", "Ankr Network", "ANKR", "AUXILIARY", 18),
        "NXZN9KF0J" to CurrencyData("NXZN9KF0J", "DAI", "Dai Stablecoin", "◈", "AUXILIARY", 18),
        "P0CVC5V9N" to CurrencyData("P0CVC5V9N", "STTD", "AFREUM STABLE TTD", "STTD", "AUXILIARY", 7),
        "P0V7ZJC0B" to CurrencyData("P0V7ZJC0B", "AKRO", "Akropolis", "AKRO", "AUXILIARY", 18),
        "P1FTS4328" to CurrencyData("P1FTS4328", "UNI", "Uniswap", "UNI", "AUXILIARY", 18),
        "P25MXHF1H" to CurrencyData("P25MXHF1H", "FTM", "Fantom", "FTM", "AUXILIARY", 18),
        "P2T8JX7HN" to CurrencyData("P2T8JX7HN", "BNB", "Binance", "BNB", "AUXILIARY", 18),
        "P49CZ2S5J" to CurrencyData("P49CZ2S5J", "VELO", "Velodrome", "VELO", "AUXILIARY", 18),
        "P4JBC8R50" to CurrencyData("P4JBC8R50", "SEI", "SEI", "SEI", "NATIVE", 6),
        "P4RFKKQJ3" to CurrencyData("P4RFKKQJ3", "BUSD", "Binance USD on Fuse", "BUSD", "AUXILIARY", 18),
        "P5PK5021M" to CurrencyData("P5PK5021M", "WBNB", "Wrapped BNB", "WBNB", "AUXILIARY", 18),
        "P5QS7QX45" to CurrencyData("P5QS7QX45", "SRM", "Serum", "SRM", "AUXILIARY", 6),
        "P5WWMTS41" to CurrencyData("P5WWMTS41", "ACB", "DAAG Certificat/Tracker Perp ACB", "ACB", "AUXILIARY", 8),
        "P61HJW99N" to CurrencyData("P61HJW99N", "BIX", "BIXToken", "BIX", "AUXILIARY", 18),
        "P6KCTXRL6" to CurrencyData("P6KCTXRL6", "METGGSDA", "MET.GL.GR.SU./ CL DA", "METGGSDA", "AUXILIARY", 0),
        "P6XNHFFFC" to CurrencyData("P6XNHFFFC", "USDT", "Tether USD", "₮", "AUXILIARY", 6),
        "P756V1FDJ" to CurrencyData("P756V1FDJ", "PEPE", "Arbi pepe", "🐸︎", "AUXILIARY", 18),
        "P7DLN3K3B" to CurrencyData("P7DLN3K3B", "FRAX", "Frax", "FRAX", "AUXILIARY", 18),
        "P7H2X1B9H" to CurrencyData("P7H2X1B9H", "USDC", "USD Coin", "USDC", "AUXILIARY", 18),
        "P7JMF863J" to CurrencyData("P7JMF863J", "AKPW", "AFREUM KPW", "AKPW", "AUXILIARY", 7),
        "P7MJF6MW8" to CurrencyData("P7MJF6MW8", "SZWL", "AFREUM STABLE ZWL", "SZWL", "AUXILIARY", 7),
        "P9DQPZQGG" to CurrencyData("P9DQPZQGG", "USDC", "USD Coin", "USDC", "AUXILIARY", 6),
        "P9KFC0FKC" to CurrencyData("P9KFC0FKC", "GGP", "Geegoopuzzle", "GGP", "AUXILIARY", 4),
        "P9R0DDN1T" to CurrencyData("P9R0DDN1T", "BAT", "Basic Attention Token", "BAT", "AUXILIARY", 18),
        "PC3MG8CS1" to CurrencyData("PC3MG8CS1", "BNTX", "DAAG Certificat/Tracker Perp BNTX", "BNTX", "AUXILIARY", 8),
        "PCFGK30QT" to CurrencyData("PCFGK30QT", "NRG", "Energi NRG", "NRG", "NATIVE", 2),
        "PCM57R0JT" to CurrencyData("PCM57R0JT", "BEAM", "Beam", "BEAM", "AUXILIARY", 18),
        "PCZ8FM2KX" to CurrencyData("PCZ8FM2KX", "IRIS", "IRISnet", "IRIS", "AUXILIARY", 6),
        "PD4LJFDSX" to CurrencyData("PD4LJFDSX", "BTG", "BITGOO", "BTG", "AUXILIARY", 8),
        "PD6TK5B06" to CurrencyData("PD6TK5B06", "SVES", "AFREUM STABLE VES", "SVES", "AUXILIARY", 7),
        "PDL9FBLPQ" to CurrencyData("PDL9FBLPQ", "JOE", "JoeToken", "JOE", "AUXILIARY", 18),
        "PDLPVX182" to CurrencyData("PDLPVX182", "USDC", "USD Coin", "USDC", "AUXILIARY", 6),
        "PDQJHSXGM" to CurrencyData("PDQJHSXGM", "AVUV", "AFREUM VUV", "AVUV", "AUXILIARY", 7),
        "PDX13MN94" to CurrencyData("PDX13MN94", "USDt", "Tether USDt", "USDt", "AUXILIARY", 6),
        "PF7655L1W" to CurrencyData("PF7655L1W", "TIME", "ChronoTech Token", "TIME", "AUXILIARY", 8),
        "PG4CNR9QC" to CurrencyData("PG4CNR9QC", "UST", "Wrapped UST Token", "UST", "AUXILIARY", 18),
        "PGMLRJSPV" to CurrencyData("PGMLRJSPV", "ZBU", "ZEEBU", "ZBU", "AUXILIARY", 18),
        "PH8TSHXS5" to CurrencyData("PH8TSHXS5", "ethUSDC", "USD Coin on Elastos", "ethUSDC", "AUXILIARY", 6),
        "PHM8B4RQT" to CurrencyData("PHM8B4RQT", "AJPY", "AFREUM JPY", "AJPY", "AUXILIARY", 7),
        "PJ1BC8W44" to CurrencyData("PJ1BC8W44", "pUSDt", "TetherToken", "pUSDt", "AUXILIARY", 6),
        "PJHWRT4MP" to CurrencyData("PJHWRT4MP", "PYUSD", "PayPal USD", "PYUSD", "AUXILIARY", 6),
        "PJTFF3BDT" to CurrencyData("PJTFF3BDT", "ETH", "Ether", "Ξ", "AUXILIARY", 18),
        "PKRTR3JHV" to CurrencyData("PKRTR3JHV", "AIRR", "AFREUM IRR", "AIRR", "AUXILIARY", 7),
    )
}
