/*
 * This file is part of the Money package.
 *
 * Copyright (c) Eriksen Costa <eriksencosta@gmail.com>
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

/*
 * This file was auto-generated by running the "generateCryptoCurrenciesDataClasses" Gradle task. Always run the
 * task after a DTI database update.
 */

package com.eriksencosta.money.currency.crypto.data

// 50 currencies
@Suppress("StringLiteralDuplication")
internal class CurrenciesLookup12 {
    val currencies: Map<String, String> get() = mapOf(
        "SCAD" to "6F1HH16W6", // AFREUM STABLE CAD available in CurrenciesData9
        "SCDF" to "VK0VS9V61", // AFREUM STABLE CDF available in CurrenciesData41
        "SCHF" to "N315XSJFS", // AFREUM STABLE CHF available in CurrenciesData31
        "SCLP" to "MBMF7QB8R", // AFREUM STABLE CLP available in CurrenciesData30
        "SCNY" to "NJL843MQG", // AFREUM STABLE CNY available in CurrenciesData32
        "SCOP" to "GFN2JK0GV", // AFREUM STABLE COP available in CurrenciesData21
        "SCRC" to "B1JQCK0PB", // AFREUM STABLE CRC available in CurrenciesData15
        "SCROOGE" to "242LJPB5G", // SCROOGE available in CurrenciesData2
        "SCUP" to "6TJFKVB1Z", // AFREUM STABLE CUP available in CurrenciesData10
        "SCVE" to "KNFCSHLZN", // AFREUM STABLE CVE available in CurrenciesData27
        "SCZK" to "DG9TH5J85", // AFREUM STABLE CZK available in CurrenciesData19
        "SD" to "2KK4GQLD5", // Stader available in CurrenciesData3
        "SDJF" to "J9TTK24QB", // AFREUM STABLE DJF available in CurrenciesData25
        "SDKK" to "7STDR9ZL4", // AFREUM STABLE DKK available in CurrenciesData11
        "SDOP" to "GFB995KNJ", // AFREUM STABLE DOP available in CurrenciesData21
        "SDTC" to "G1HDCB6XX", // Terra Classic SDR available in CurrenciesData21
        "SDZD" to "SQB8ZGMQR", // AFREUM STABLE DZD available in CurrenciesData38
        "SEGP" to "4DQ5TLTJ2", // AFREUM STABLE EGP available in CurrenciesData6
        "SENSO" to "KVF1031CQ", // Sensorium available in CurrenciesData28
        "SERN" to "G4FGGX4BL", // AFREUM STABLE ERN available in CurrenciesData21
        "SETB" to "WL0JVNMPV", // AFREUM STABLE ETB available in CurrenciesData42
        "SEUR" to "9ZQPXXG9V", // AFREUM STABLE EUR available in CurrenciesData15
        "SFJD" to "56QKD8Q78", // AFREUM STABLE FJD available in CurrenciesData7
        "SFKP" to "997CHXT2G", // AFREUM STABLE FKP available in CurrenciesData14
        "SFM" to "RJLCSM3K2", // SafeMoon available in CurrenciesData36
        "SFP" to "1P4SSTK2K", // SafePal Token available in CurrenciesData2
        "SGB" to "L5TJKVVGF", // Songbird available in CurrenciesData28
        "SGBP" to "43ZFR0SQ6", // AFREUM STABLE GBP available in CurrenciesData5
        "SGEL" to "DCDN58XDP", // AFREUM STABLE GEL available in CurrenciesData18
        "SGHS" to "DZLGG7RRP", // AFREUM STABLE GHS available in CurrenciesData19
        "SGIP" to "QN5FC973R", // AFREUM STABLE GIP available in CurrenciesData35
        "SGMD" to "4PNGRRT4S", // AFREUM STABLE GMD available in CurrenciesData6
        "SGNF" to "GS41FM8CD", // AFREUM STABLE GNF available in CurrenciesData22
        "SGTQ" to "K2D6M96TP", // AFREUM STABLE GTQ available in CurrenciesData26
        "SGYD" to "24BJT2F9L", // AFREUM STABLE GYD available in CurrenciesData2
        "SHKD" to "WWJL4WXKN", // AFREUM STABLE HKD available in CurrenciesData43
        "SHNL" to "N8J695HTD", // AFREUM STABLE HNL available in CurrenciesData31
        "SHPING" to "D9H3GJVD5", // Shping Coin available in CurrenciesData18
        "SHRK" to "KPFNCGR12", // AFREUM STABLE HRK available in CurrenciesData27
        "SHTG" to "H6HSB3NRB", // AFREUM STABLE HTG available in CurrenciesData23
        "SHUF" to "TX7TRXHS0", // AFREUM STABLE HUF available in CurrenciesData40
        "SID" to "K0C0VSTL8", // SIDO IMMO/GENS 1000 available in CurrenciesData26
        "SIDR" to "1G7Z6TH24", // AFREUM STABLE IDR available in CurrenciesData1
        "SILS" to "JCV2KV911", // AFREUM STABLE ILS available in CurrenciesData25
        "SINR" to "SFHGMDSR5", // AFREUM STABLE INR available in CurrenciesData38
        "SIQD" to "GR45L3S73", // AFREUM STABLE IQD available in CurrenciesData22
        "SIRR" to "F0S5Q8B63", // AFREUM STABLE IRR available in CurrenciesData19
        "SISK" to "HLG5F3MRM", // AFREUM STABLE ISK available in CurrenciesData24
        "SJMD" to "C58DSD0DS", // AFREUM STABLE JMD available in CurrenciesData17
        "SJOD" to "KWQ4G7CJ8", // AFREUM STABLE JOD available in CurrenciesData28
    )
}
