/*
 * This file is part of the Money package.
 *
 * Copyright (c) Eriksen Costa <eriksencosta@gmail.com>
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

/*
 * This file was auto-generated by running the "generateCryptoCurrenciesDataClasses" Gradle task. Always run the
 * task after a DTI database update.
 */

package com.eriksencosta.money.currency.crypto.data

// 50 currencies
@Suppress("StringLiteralDuplication")
internal class CurrenciesLookup8 {
    val currencies: Map<String, String> get() = mapOf(
        "HBSV" to "GQ68Z03WZ", // Huobi BSV available in CurrenciesData22
        "HDL" to "FZJ3Q9MHV", // HEADLINE available in CurrenciesData21
        "HDOT" to "562T78F9X", // Heco-Peg HDOT Token available in CurrenciesData7
        "HFIL" to "D3K7WMHT1", // Heco-Peg HFIL Token available in CurrenciesData18
        "HFT" to "9ZZS6Q0NJ", // Hashflow available in CurrenciesData15
        "HIFI" to "9Q0BZD6BD", // Hifi Finance available in CurrenciesData14
        "HIVE" to "SW2NXBK4D", // Hive available in CurrenciesData38
        "HK0000895216" to "JVTWMTRJ7", // HKSAR GOVT/4.05 NT 20240216 UNSEC available in CurrenciesData26
        "HK0000963279" to "1SJDQ6WSB", // HKSAR/FR BD 20260126 UNSEC available in CurrenciesData2
        "HK0000963287" to "6CTQJ6Z1C", // HKSAR/FR BD 20260126 UNSEC available in CurrenciesData9
        "HK0000963295" to "RXTQCJR5R", // HKSAR/FR BD 20260126 UNSEC available in CurrenciesData37
        "HK0000976420" to "T7JHJTN7F", // HKSAR/FR BD 20260202 UNSEC available in CurrenciesData39
        "HLTC" to "S495BVMQV", // Heco-Peg HLTC Token available in CurrenciesData37
        "HOOK" to "5Q34Q72PJ", // Hooked Protocol available in CurrenciesData8
        "HOP" to "V9RDNLSMZ", // Hop available in CurrenciesData40
        "HUNT" to "N9NW8G6MF", // HuntToken available in CurrenciesData31
        "ICX" to "7FMV5P1LR", // ICON available in CurrenciesData11
        "IDEX" to "BP6D251H9", // IDEX Token available in CurrenciesData16
        "INTC" to "2B7D7PF38", // DAAG Certificat/Tracker Perp INTC available in CurrenciesData3
        "INV" to "5MNV1WP0H", // Inverse DAO available in CurrenciesData8
        "IOST" to "R9TSFJ27T", // IOST available in CurrenciesData36
        "IPX" to "NLC9B8MWQ", // InpulseX available in CurrenciesData32
        "JAM" to "1ZQJ6D6XT", // Geojam available in CurrenciesData2
        "JASMY" to "1ZPV1ZRZC", // JasmyCoin available in CurrenciesData2
        "JBL" to "QNZDQH768", // JuniorBaseballLeague available in CurrenciesData35
        "JEWEL" to "PVS2KWZVT", // DFK Subnet JEWEL available in CurrenciesData34
        "JITOSOL" to "9KRM76LJH", // Jito Staked SOL available in CurrenciesData14
        "JLP" to "62DDW4B6S", // Jupiter Perps LP available in CurrenciesData9
        "JPTC" to "MVNS8ZS0X", // Terra Classic JPY available in CurrenciesData31
        "JST" to "VGSK822DJ", // JUST available in CurrenciesData41
        "JTO" to "1P87W66DP", // Jito available in CurrenciesData2
        "JUST" to "L30FLT5HM", // DAAG Certificat/Tracker Perp JUST available in CurrenciesData28
        "JUV" to "SKQJ8Z2MJ", // Juventus available in CurrenciesData38
        "KAI" to "STXDTB1ZW", // Kardia Chain available in CurrenciesData38
        "KCC" to "6VRB7HW47", // KCC available in CurrenciesData10
        "KDA" to "5HFS8PZMW", // Kadena available in CurrenciesData8
        "KEY" to "BZJSXCGD6", // SelfKey available in CurrenciesData16
        "KOK" to "6CKPGS2JV", // KOK Coin available in CurrenciesData9
        "KRL" to "NR28RS0JP", // Kryll available in CurrenciesData32
        "KRTC" to "XZFC7H04P", // Terra Classic KRW available in CurrenciesData44
        "KSM" to "MXLJ762RF", // Kusama available in CurrenciesData31
        "L-BTC" to "XRL18NJLL", // Bitcoin Liquid available in CurrenciesData44
        "LAYR" to "QDXDCXTHJ", // Composable Finance available in CurrenciesData35
        "LAZIO" to "1SM976GP1", // FC Lazio Fan Token available in CurrenciesData2
        "LBA" to "4ZLW05RXQ", // LibraToken available in CurrenciesData7
        "LCX" to "F2N6WJ9S8", // LCX available in CurrenciesData20
        "LEND" to "JZBH0W7W0", // EthLend Token available in CurrenciesData26
        "LEVER" to "2XVQCZ90M", // LeverFi available in CurrenciesData4
        "LINK.e" to "GH40FM7C2", // Chainlink Token available in CurrenciesData22
        "LOKA" to "XG3S0NSVG", // League of Kingdoms Arena available in CurrenciesData43
    )
}
