/*
 * This file is part of the Money package.
 *
 * Copyright (c) Eriksen Costa <eriksencosta@gmail.com>
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

/*
 * This file was auto-generated by running the "generateCirculatingCurrenciesDataClasses" Gradle task. Always run the
 * task after upgrading the ICU library.
 */

package com.eriksencosta.money.currency.circulating.data

// 306 currencies
@Suppress("LargeClass")
internal class CurrenciesSecondaryCodes {
    val codes: Set<String> get() = setOf(
        "004", // Afghan Afghani (1927–2002)
        "012", // Algerian Dinar
        "020", // Andorran Peseta
        "031", // Azerbaijani Manat (1993–2006)
        "036", // Australian Dollar
        "040", // Austrian Schilling
        "044", // Bahamian Dollar
        "048", // Bahraini Dinar
        "050", // Bangladeshi Taka
        "051", // Armenian Dram
        "052", // Barbadian Dollar
        "056", // Belgian Franc
        "060", // Bermudan Dollar
        "064", // Bhutanese Ngultrum
        "070", // Bosnia-Herzegovina Dinar (1992–1994)
        "072", // Botswanan Pula
        "084", // Belize Dollar
        "090", // Solomon Islands Dollar
        "096", // Brunei Dollar
        "100", // Bulgarian Hard Lev
        "108", // Burundian Franc
        "112", // Belarusian Ruble (1994–1999)
        "116", // Cambodian Riel
        "124", // Canadian Dollar
        "132", // Cape Verdean Escudo
        "136", // Cayman Islands Dollar
        "144", // Sri Lankan Rupee
        "152", // Chilean Peso
        "156", // Chinese Yuan
        "170", // Colombian Peso
        "174", // Comorian Franc
        "188", // Costa Rican Colón
        "192", // Cuban Peso
        "196", // Cypriot Pound
        "200", // Czechoslovak Hard Koruna
        "203", // Czech Koruna
        "208", // Danish Krone
        "214", // Dominican Peso
        "218", // Ecuadorian Sucre
        "222", // Salvadoran Colón
        "226", // Equatorial Guinean Ekwele
        "230", // Ethiopian Birr
        "232", // Eritrean Nakfa
        "233", // Estonian Kroon
        "238", // Falkland Islands Pound
        "242", // Fijian Dollar
        "246", // Finnish Markka
        "250", // French Franc
        "262", // Djiboutian Franc
        "268", // Georgian Kupon Larit
        "270", // Gambian Dalasi
        "276", // German Mark
        "278", // East German Mark
        "288", // Ghanaian Cedi (1979–2007)
        "292", // Gibraltar Pound
        "300", // Greek Drachma
        "320", // Guatemalan Quetzal
        "328", // Guyanaese Dollar
        "332", // Haitian Gourde
        "340", // Honduran Lempira
        "344", // Hong Kong Dollar
        "348", // Hungarian Forint
        "356", // Indian Rupee
        "360", // Indonesian Rupiah
        "364", // Iranian Rial
        "368", // Iraqi Dinar
        "372", // Irish Pound
        "380", // Italian Lira
        "388", // Jamaican Dollar
        "392", // Japanese Yen
        "398", // Kazakhstani Tenge
        "400", // Jordanian Dinar
        "404", // Kenyan Shilling
        "408", // North Korean Won
        "410", // South Korean Won
        "414", // Kuwaiti Dinar
        "417", // Kyrgystani Som
        "418", // Laotian Kip
        "422", // Lebanese Pound
        "426", // Lesotho Loti
        "430", // Liberian Dollar
        "434", // Libyan Dinar
        "442", // Luxembourgian Franc
        "446", // Macanese Pataca
        "450", // Malagasy Franc
        "454", // Malawian Kwacha
        "458", // Malaysian Ringgit
        "462", // Maldivian Rufiyaa
        "466", // Malian Franc
        "478", // Mauritanian Ouguiya (1973–2017)
        "480", // Mauritian Rupee
        "484", // Mexican Peso
        "496", // Mongolian Tugrik
        "498", // Moldovan Leu
        "504", // Moroccan Dirham
        "512", // Omani Rial
        "516", // Namibian Dollar
        "524", // Nepalese Rupee
        "528", // Dutch Guilder
        "532", // Netherlands Antillean Guilder
        "533", // Aruban Florin
        "548", // Vanuatu Vatu
        "554", // New Zealand Dollar
        "566", // Nigerian Naira
        "578", // Norwegian Krone
        "586", // Pakistani Rupee
        "590", // Panamanian Balboa
        "598", // Papua New Guinean Kina
        "600", // Paraguayan Guarani
        "608", // Philippine Peso
        "616", // Polish Zloty (1950–1995)
        "620", // Portuguese Escudo
        "626", // Timorese Escudo
        "634", // Qatari Riyal
        "642", // Romanian Leu (1952–2006)
        "643", // Russian Ruble
        "646", // Rwandan Franc
        "654", // St. Helena Pound
        "678", // São Tomé & Príncipe Dobra (1977–2017)
        "682", // Saudi Riyal
        "690", // Seychellois Rupee
        "694", // Sierra Leonean Leone (1964—2022)
        "702", // Singapore Dollar
        "703", // Slovak Koruna
        "704", // Vietnamese Dong
        "705", // Slovenian Tolar
        "706", // Somali Shilling
        "710", // South African Rand
        "720", // Yemeni Dinar
        "724", // Spanish Peseta
        "728", // South Sudanese Pound
        "740", // Surinamese Guilder
        "748", // Swazi Lilangeni
        "752", // Swedish Krona
        "756", // Swiss Franc
        "760", // Syrian Pound
        "762", // Tajikistani Ruble
        "764", // Thai Baht
        "776", // Tongan Paʻanga
        "780", // Trinidad & Tobago Dollar
        "784", // United Arab Emirates Dirham
        "788", // Tunisian Dinar
        "792", // Turkish Lira (1922–2005)
        "795", // Turkmenistani Manat (1993–2009)
        "804", // Ukrainian Karbovanets
        "807", // Macedonian Denar
        "818", // Egyptian Pound
        "826", // British Pound
        "834", // Tanzanian Shilling
        "840", // US Dollar
        "860", // Uzbekistani Som
        "862", // Venezuelan Bolívar (1871–2008)
        "882", // Samoan Tala
        "886", // Yemeni Rial
        "894", // Zambian Kwacha (1968–2012)
        "901", // New Taiwan Dollar
        "925", // Sierra Leonean Leone
        "926", // Bolívar Soberano
        "927", // Uruguayan Nominal Wage Index Unit
        "928", // Venezuelan Bolívar
        "929", // Mauritanian Ouguiya
        "930", // São Tomé & Príncipe Dobra
        "931", // Cuban Convertible Peso
        "932", // Zimbabwean Dollar (2009)
        "933", // Belarusian Ruble
        "934", // Turkmenistani Manat
        "935", // Zimbabwean Dollar (2008)
        "936", // Ghanaian Cedi
        "937", // Venezuelan Bolívar (2008–2018)
        "938", // Sudanese Pound
        "940", // Uruguayan Peso (Indexed Units)
        "941", // Serbian Dinar
        "943", // Mozambican Metical
        "944", // Azerbaijani Manat
        "946", // Romanian Leu
        "947", // WIR Euro
        "948", // WIR Franc
        "949", // Turkish Lira
        "950", // Central African CFA Franc
        "951", // East Caribbean Dollar
        "952", // West African CFA Franc
        "953", // CFP Franc
        "954", // European Currency Unit
        "955", // European Composite Unit
        "956", // European Monetary Unit
        "957", // European Unit of Account (XBC)
        "958", // European Unit of Account (XBD)
        "959", // Gold
        "960", // Special Drawing Rights
        "961", // Silver
        "962", // Platinum
        "963", // Testing Currency Code
        "964", // Palladium
        "965", // ADB Unit of Account
        "967", // Zambian Kwacha
        "968", // Surinamese Dollar
        "969", // Malagasy Ariary
        "970", // Colombian Real Value Unit
        "971", // Afghan Afghani
        "972", // Tajikistani Somoni
        "973", // Angolan Kwanza
        "974", // Belarusian Ruble (2000–2016)
        "975", // Bulgarian Lev
        "976", // Congolese Franc
        "977", // Bosnia-Herzegovina Convertible Mark
        "978", // Euro
        "979", // Mexican Investment Unit
        "980", // Ukrainian Hryvnia
        "981", // Georgian Lari
        "982", // Angolan Readjusted Kwanza (1995–1999)
        "983", // Ecuadorian Unit of Constant Value
        "984", // Bolivian Mvdol
        "985", // Polish Zloty
        "986", // Brazilian Real
        "987", // Brazilian Cruzeiro (1993–1994)
        "988", // Luxembourg Financial Franc
        "989", // Luxembourgian Convertible Franc
        "990", // Chilean Unit of Account (UF)
        "991", // South African Rand (financial)
        "992", // Belgian Franc (financial)
        "993", // Belgian Franc (convertible)
        "994", // Sucre
        "995", // Spanish Peseta (convertible account)
        "996", // Spanish Peseta (A account)
        "997", // US Dollar (Next day)
        "998", // US Dollar (Same day)
        "999", // Unknown Currency
    )
}
