/*
 * This file is part of the Money package.
 *
 * Copyright (c) Eriksen Costa <eriksencosta@gmail.com>
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

/*
 * This file was auto-generated by running the "generateCirculatingCurrenciesDataClasses" Gradle task. Always run the
 * task after upgrading the ICU library.
 */

package com.eriksencosta.money.currency.circulating.data

import com.eriksencosta.money.caching.Cache
import com.eriksencosta.money.currency.createSizedCache
import com.eriksencosta.money.currency.findCodeBySecondaryCode

@Suppress("CyclomaticComplexMethod")
internal object CurrenciesLookup {
    private const val NUMBER_OF_LOOKUP_CLASSES = 6

    private val cache: Cache<Map<String, String>> by lazy {
        createSizedCache(NUMBER_OF_LOOKUP_CLASSES)
    }

    private val prioritizedCurrencies = CurrenciesLookup0().currencies

    fun of(code: String): String = prioritizedCurrencies.getOrElse(code) {
        when (code) {
            in "004".."288" -> findCodeBySecondaryCode("Lookup1", code) { CurrenciesLookup1().currencies }
            in "292".."620" -> findCodeBySecondaryCode("Lookup2", code) { CurrenciesLookup2().currencies }
            in "626".."940" -> findCodeBySecondaryCode("Lookup3", code) { CurrenciesLookup3().currencies }
            in "941".."996" -> findCodeBySecondaryCode("Lookup4", code) { CurrenciesLookup4().currencies }
            in "997".."999" -> findCodeBySecondaryCode("Lookup5", code) { CurrenciesLookup5().currencies }
            else -> ""
        }
    }

    private fun findCodeBySecondaryCode(key: String, code: String, block: () -> Map<String, String>): String =
        cache.get(key) { block() }.findCodeBySecondaryCode(code)
}
