/*
 * This file is part of the Money package.
 *
 * Copyright (c) Eriksen Costa <eriksencosta@gmail.com>
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

/*
 * This file was auto-generated by running the "generateCirculatingCurrenciesDataClasses" Gradle task. Always run the
 * task after upgrading the ICU library.
 */

package com.eriksencosta.money.currency.circulating.data

// 50 currencies
@Suppress("StringLiteralDuplication")
internal class CurrenciesLookup2 {
    val currencies: Map<String, String> get() = mapOf(
        "292" to "GIP", // Gibraltar Pound available in CurrenciesData2
        "300" to "GRD", // Greek Drachma available in CurrenciesData3
        "320" to "GTQ", // Guatemalan Quetzal available in CurrenciesData3
        "328" to "GYD", // Guyanaese Dollar available in CurrenciesData3
        "332" to "HTG", // Haitian Gourde available in CurrenciesData3
        "340" to "HNL", // Honduran Lempira available in CurrenciesData3
        "348" to "HUF", // Hungarian Forint available in CurrenciesData3
        "364" to "IRR", // Iranian Rial available in CurrenciesData3
        "368" to "IQD", // Iraqi Dinar available in CurrenciesData3
        "372" to "IEP", // Irish Pound available in CurrenciesData3
        "380" to "ITL", // Italian Lira available in CurrenciesData3
        "388" to "JMD", // Jamaican Dollar available in CurrenciesData3
        "398" to "KZT", // Kazakhstani Tenge available in CurrenciesData3
        "400" to "JOD", // Jordanian Dinar available in CurrenciesData3
        "404" to "KES", // Kenyan Shilling available in CurrenciesData3
        "408" to "KPW", // North Korean Won available in CurrenciesData3
        "414" to "KWD", // Kuwaiti Dinar available in CurrenciesData3
        "417" to "KGS", // Kyrgystani Som available in CurrenciesData3
        "418" to "LAK", // Laotian Kip available in CurrenciesData3
        "422" to "LBP", // Lebanese Pound available in CurrenciesData3
        "426" to "LSL", // Lesotho Loti available in CurrenciesData3
        "430" to "LRD", // Liberian Dollar available in CurrenciesData3
        "434" to "LYD", // Libyan Dinar available in CurrenciesData3
        "442" to "LUF", // Luxembourgian Franc available in CurrenciesData3
        "446" to "MOP", // Macanese Pataca available in CurrenciesData4
        "450" to "MGF", // Malagasy Franc available in CurrenciesData4
        "454" to "MWK", // Malawian Kwacha available in CurrenciesData4
        "458" to "MYR", // Malaysian Ringgit available in CurrenciesData4
        "462" to "MVR", // Maldivian Rufiyaa available in CurrenciesData4
        "466" to "MLF", // Malian Franc available in CurrenciesData4
        "478" to "MRO", // Mauritanian Ouguiya (1973–2017) available in CurrenciesData4
        "480" to "MUR", // Mauritian Rupee available in CurrenciesData4
        "496" to "MNT", // Mongolian Tugrik available in CurrenciesData4
        "498" to "MDL", // Moldovan Leu available in CurrenciesData3
        "504" to "MAD", // Moroccan Dirham available in CurrenciesData3
        "512" to "OMR", // Omani Rial available in CurrenciesData4
        "516" to "NAD", // Namibian Dollar available in CurrenciesData4
        "524" to "NPR", // Nepalese Rupee available in CurrenciesData4
        "528" to "NLG", // Dutch Guilder available in CurrenciesData4
        "532" to "ANG", // Netherlands Antillean Guilder available in CurrenciesData1
        "533" to "AWG", // Aruban Florin available in CurrenciesData1
        "548" to "VUV", // Vanuatu Vatu available in CurrenciesData5
        "566" to "NGN", // Nigerian Naira available in CurrenciesData4
        "586" to "PKR", // Pakistani Rupee available in CurrenciesData4
        "590" to "PAB", // Panamanian Balboa available in CurrenciesData4
        "598" to "PGK", // Papua New Guinean Kina available in CurrenciesData4
        "600" to "PYG", // Paraguayan Guarani available in CurrenciesData4
        "608" to "PHP", // Philippine Peso available in CurrenciesData4
        "616" to "PLZ", // Polish Zloty (1950–1995) available in CurrenciesData4
        "620" to "PTE", // Portuguese Escudo available in CurrenciesData4
    )
}
