/*
 * This file is part of the Money package.
 *
 * Copyright (c) Eriksen Costa <eriksencosta@gmail.com>
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

/*
 * This file was auto-generated by running the "generateCirculatingCurrenciesDataClasses" Gradle task. Always run the
 * task after upgrading the ICU library.
 */

package com.eriksencosta.money.currency.circulating.data

// 24 currencies
@Suppress("StringLiteralDuplication")
internal class CurrenciesLookup0 {
    val currencies: Map<String, String> get() = mapOf(
        "036" to "AUD", // Australian Dollar available in CurrenciesData0
        "124" to "CAD", // Canadian Dollar available in CurrenciesData0
        "156" to "CNY", // Chinese Yuan available in CurrenciesData0
        "208" to "DKK", // Danish Krone available in CurrenciesData0
        "344" to "HKD", // Hong Kong Dollar available in CurrenciesData0
        "356" to "INR", // Indian Rupee available in CurrenciesData0
        "360" to "IDR", // Indonesian Rupiah available in CurrenciesData0
        "392" to "JPY", // Japanese Yen available in CurrenciesData0
        "410" to "KRW", // South Korean Won available in CurrenciesData0
        "484" to "MXN", // Mexican Peso available in CurrenciesData0
        "554" to "NZD", // New Zealand Dollar available in CurrenciesData0
        "578" to "NOK", // Norwegian Krone available in CurrenciesData0
        "643" to "RUB", // Russian Ruble available in CurrenciesData0
        "682" to "SAR", // Saudi Riyal available in CurrenciesData0
        "702" to "SGD", // Singapore Dollar available in CurrenciesData0
        "710" to "ZAR", // South African Rand available in CurrenciesData0
        "752" to "SEK", // Swedish Krona available in CurrenciesData0
        "756" to "CHF", // Swiss Franc available in CurrenciesData0
        "826" to "GBP", // British Pound available in CurrenciesData0
        "840" to "USD", // US Dollar available in CurrenciesData0
        "901" to "TWD", // New Taiwan Dollar available in CurrenciesData0
        "949" to "TRY", // Turkish Lira available in CurrenciesData0
        "978" to "EUR", // Euro available in CurrenciesData0
        "986" to "BRL", // Brazilian Real available in CurrenciesData0
    )
}
