/*
 * This file is part of the Money package.
 *
 * Copyright (c) Eriksen Costa <eriksencosta@gmail.com>
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

/*
 * This file was auto-generated by running the "generateCirculatingCurrenciesDataClasses" Gradle task. Always run the
 * task after upgrading the ICU library.
 */

package com.eriksencosta.money.currency.circulating.data

import com.eriksencosta.money.currency.CurrencyData

// 50 currencies
@Suppress("MagicNumber", "MaxLineLength", "StringLiteralDuplication")
internal class CurrenciesData2 {
    val currencies: Map<String, CurrencyData> get() = mapOf(
        "BWP" to CurrencyData("BWP", "072", "Botswanan Pula", "P", "TENDER", 2),
        "BYB" to CurrencyData("BYB", "112", "Belarusian Ruble (1994–1999)", "BYB", "HISTORICAL", 2),
        "BYN" to CurrencyData("BYN", "933", "Belarusian Ruble", "Br", "TENDER", 2),
        "BYR" to CurrencyData("BYR", "974", "Belarusian Ruble (2000–2016)", "BYR", "HISTORICAL", 0),
        "BZD" to CurrencyData("BZD", "084", "Belize Dollar", "\$", "TENDER", 2),
        "CDF" to CurrencyData("CDF", "976", "Congolese Franc", "FC", "TENDER", 2),
        "CHE" to CurrencyData("CHE", "947", "WIR Euro", "CHE", "HISTORICAL", 2),
        "CHW" to CurrencyData("CHW", "948", "WIR Franc", "CHW", "HISTORICAL", 2),
        "CLE" to CurrencyData("CLE", "000", "Chilean Escudo", "CLE", "HISTORICAL", 2),
        "CLF" to CurrencyData("CLF", "990", "Chilean Unit of Account (UF)", "CLF", "HISTORICAL", 4),
        "CLP" to CurrencyData("CLP", "152", "Chilean Peso", "\$", "TENDER", 0),
        "CNH" to CurrencyData("CNH", "000", "Chinese Yuan (offshore)", "CNH", "HISTORICAL", 2),
        "CNX" to CurrencyData("CNX", "000", "Chinese People’s Bank Dollar", "CNX", "HISTORICAL", 2),
        "COP" to CurrencyData("COP", "170", "Colombian Peso", "\$", "TENDER", 2),
        "COU" to CurrencyData("COU", "970", "Colombian Real Value Unit", "COU", "HISTORICAL", 2),
        "CRC" to CurrencyData("CRC", "188", "Costa Rican Colón", "₡", "TENDER", 2),
        "CSD" to CurrencyData("CSD", "891", "Serbian Dinar (2002–2006)", "CSD", "HISTORICAL", 2),
        "CSK" to CurrencyData("CSK", "200", "Czechoslovak Hard Koruna", "CSK", "HISTORICAL", 2),
        "CUC" to CurrencyData("CUC", "931", "Cuban Convertible Peso", "CUC", "HISTORICAL", 2),
        "CUP" to CurrencyData("CUP", "192", "Cuban Peso", "\$", "TENDER", 2),
        "CVE" to CurrencyData("CVE", "132", "Cape Verdean Escudo", "\$", "TENDER", 2),
        "CYP" to CurrencyData("CYP", "196", "Cypriot Pound", "CYP", "HISTORICAL", 2),
        "CZK" to CurrencyData("CZK", "203", "Czech Koruna", "Kč", "TENDER", 2),
        "DDM" to CurrencyData("DDM", "278", "East German Mark", "DDM", "HISTORICAL", 2),
        "DEM" to CurrencyData("DEM", "276", "German Mark", "DEM", "HISTORICAL", 2),
        "DJF" to CurrencyData("DJF", "262", "Djiboutian Franc", "Fdj", "TENDER", 0),
        "DOP" to CurrencyData("DOP", "214", "Dominican Peso", "RD\$", "TENDER", 2),
        "DZD" to CurrencyData("DZD", "012", "Algerian Dinar", "د.ج.‏", "TENDER", 2),
        "ECS" to CurrencyData("ECS", "218", "Ecuadorian Sucre", "ECS", "HISTORICAL", 2),
        "ECV" to CurrencyData("ECV", "983", "Ecuadorian Unit of Constant Value", "ECV", "HISTORICAL", 2),
        "EEK" to CurrencyData("EEK", "233", "Estonian Kroon", "EEK", "HISTORICAL", 2),
        "EGP" to CurrencyData("EGP", "818", "Egyptian Pound", "ج.م.‏", "TENDER", 2),
        "ERN" to CurrencyData("ERN", "232", "Eritrean Nakfa", "Nfk", "TENDER", 2),
        "ESA" to CurrencyData("ESA", "996", "Spanish Peseta (A account)", "ESA", "HISTORICAL", 2),
        "ESB" to CurrencyData("ESB", "995", "Spanish Peseta (convertible account)", "ESB", "HISTORICAL", 2),
        "ESP" to CurrencyData("ESP", "724", "Spanish Peseta", "ESP", "HISTORICAL", 0),
        "ETB" to CurrencyData("ETB", "230", "Ethiopian Birr", "ብር", "TENDER", 2),
        "FIM" to CurrencyData("FIM", "246", "Finnish Markka", "FIM", "HISTORICAL", 2),
        "FJD" to CurrencyData("FJD", "242", "Fijian Dollar", "\$", "TENDER", 2),
        "FKP" to CurrencyData("FKP", "238", "Falkland Islands Pound", "£", "TENDER", 2),
        "FRF" to CurrencyData("FRF", "250", "French Franc", "FRF", "HISTORICAL", 2),
        "GEK" to CurrencyData("GEK", "268", "Georgian Kupon Larit", "GEK", "HISTORICAL", 2),
        "GEL" to CurrencyData("GEL", "981", "Georgian Lari", "₾", "TENDER", 2),
        "GHC" to CurrencyData("GHC", "288", "Ghanaian Cedi (1979–2007)", "GHC", "HISTORICAL", 2),
        "GHS" to CurrencyData("GHS", "936", "Ghanaian Cedi", "GH₵", "TENDER", 2),
        "GIP" to CurrencyData("GIP", "292", "Gibraltar Pound", "£", "TENDER", 2),
        "GMD" to CurrencyData("GMD", "270", "Gambian Dalasi", "D", "TENDER", 2),
        "GNF" to CurrencyData("GNF", "324", "Guinean Franc", "߿", "TENDER", 0),
        "GNS" to CurrencyData("GNS", "324", "Guinean Syli", "GNS", "HISTORICAL", 2),
        "GQE" to CurrencyData("GQE", "226", "Equatorial Guinean Ekwele", "GQE", "HISTORICAL", 2),
    )
}
