/*
 * This file is part of the Money package.
 *
 * Copyright (c) Eriksen Costa <eriksencosta@gmail.com>
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

/*
 * This file was auto-generated by running the "generateCirculatingCurrenciesDataClasses" Gradle task. Always run the
 * task after upgrading the ICU library.
 */

package com.eriksencosta.money.currency.circulating.data

// 3 currencies
@Suppress("StringLiteralDuplication")
internal class CurrenciesLookup5 {
    val currencies: Map<String, String> get() = mapOf(
        "997" to "USN", // US Dollar (Next day) available in CurrenciesData5
        "998" to "USS", // US Dollar (Same day) available in CurrenciesData5
        "999" to "XXX", // Unknown Currency available in CurrenciesData6
    )
}
