/*
 * This file is part of the Money package.
 *
 * Copyright (c) Eriksen Costa <eriksencosta@gmail.com>
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

/*
 * This file was auto-generated by running the "generateCirculatingCurrenciesDataClasses" Gradle task. Always run the
 * task after upgrading the ICU library.
 */

package com.eriksencosta.money.currency.circulating.data

// 306 currencies
@Suppress("LargeClass")
internal class CurrenciesCodes {
    val codes: Set<String> get() = setOf(
        "ADP", // Andorran Peseta
        "AED", // United Arab Emirates Dirham
        "AFA", // Afghan Afghani (1927–2002)
        "AFN", // Afghan Afghani
        "ALK", // Albanian Lek (1946–1965)
        "ALL", // Albanian Lek
        "AMD", // Armenian Dram
        "ANG", // Netherlands Antillean Guilder
        "AOA", // Angolan Kwanza
        "AOK", // Angolan Kwanza (1977–1991)
        "AON", // Angolan New Kwanza (1990–2000)
        "AOR", // Angolan Readjusted Kwanza (1995–1999)
        "ARA", // Argentine Austral
        "ARL", // Argentine Peso Ley (1970–1983)
        "ARM", // Argentine Peso (1881–1970)
        "ARP", // Argentine Peso (1983–1985)
        "ARS", // Argentine Peso
        "ATS", // Austrian Schilling
        "AUD", // Australian Dollar
        "AWG", // Aruban Florin
        "AZM", // Azerbaijani Manat (1993–2006)
        "AZN", // Azerbaijani Manat
        "BAD", // Bosnia-Herzegovina Dinar (1992–1994)
        "BAM", // Bosnia-Herzegovina Convertible Mark
        "BAN", // Bosnia-Herzegovina New Dinar (1994–1997)
        "BBD", // Barbadian Dollar
        "BDT", // Bangladeshi Taka
        "BEC", // Belgian Franc (convertible)
        "BEF", // Belgian Franc
        "BEL", // Belgian Franc (financial)
        "BGL", // Bulgarian Hard Lev
        "BGM", // Bulgarian Socialist Lev
        "BGN", // Bulgarian Lev
        "BGO", // Bulgarian Lev (1879–1952)
        "BHD", // Bahraini Dinar
        "BIF", // Burundian Franc
        "BMD", // Bermudan Dollar
        "BND", // Brunei Dollar
        "BOB", // Bolivian Boliviano
        "BOL", // Bolivian Boliviano (1863–1963)
        "BOP", // Bolivian Peso
        "BOV", // Bolivian Mvdol
        "BRB", // Brazilian New Cruzeiro (1967–1986)
        "BRC", // Brazilian Cruzado (1986–1989)
        "BRE", // Brazilian Cruzeiro (1990–1993)
        "BRL", // Brazilian Real
        "BRN", // Brazilian New Cruzado (1989–1990)
        "BRR", // Brazilian Cruzeiro (1993–1994)
        "BRZ", // Brazilian Cruzeiro (1942–1967)
        "BSD", // Bahamian Dollar
        "BTN", // Bhutanese Ngultrum
        "BUK", // Burmese Kyat
        "BWP", // Botswanan Pula
        "BYB", // Belarusian Ruble (1994–1999)
        "BYN", // Belarusian Ruble
        "BYR", // Belarusian Ruble (2000–2016)
        "BZD", // Belize Dollar
        "CAD", // Canadian Dollar
        "CDF", // Congolese Franc
        "CHE", // WIR Euro
        "CHF", // Swiss Franc
        "CHW", // WIR Franc
        "CLE", // Chilean Escudo
        "CLF", // Chilean Unit of Account (UF)
        "CLP", // Chilean Peso
        "CNH", // Chinese Yuan (offshore)
        "CNX", // Chinese People’s Bank Dollar
        "CNY", // Chinese Yuan
        "COP", // Colombian Peso
        "COU", // Colombian Real Value Unit
        "CRC", // Costa Rican Colón
        "CSD", // Serbian Dinar (2002–2006)
        "CSK", // Czechoslovak Hard Koruna
        "CUC", // Cuban Convertible Peso
        "CUP", // Cuban Peso
        "CVE", // Cape Verdean Escudo
        "CYP", // Cypriot Pound
        "CZK", // Czech Koruna
        "DDM", // East German Mark
        "DEM", // German Mark
        "DJF", // Djiboutian Franc
        "DKK", // Danish Krone
        "DOP", // Dominican Peso
        "DZD", // Algerian Dinar
        "ECS", // Ecuadorian Sucre
        "ECV", // Ecuadorian Unit of Constant Value
        "EEK", // Estonian Kroon
        "EGP", // Egyptian Pound
        "ERN", // Eritrean Nakfa
        "ESA", // Spanish Peseta (A account)
        "ESB", // Spanish Peseta (convertible account)
        "ESP", // Spanish Peseta
        "ETB", // Ethiopian Birr
        "EUR", // Euro
        "FIM", // Finnish Markka
        "FJD", // Fijian Dollar
        "FKP", // Falkland Islands Pound
        "FRF", // French Franc
        "GBP", // British Pound
        "GEK", // Georgian Kupon Larit
        "GEL", // Georgian Lari
        "GHC", // Ghanaian Cedi (1979–2007)
        "GHS", // Ghanaian Cedi
        "GIP", // Gibraltar Pound
        "GMD", // Gambian Dalasi
        "GNF", // Guinean Franc
        "GNS", // Guinean Syli
        "GQE", // Equatorial Guinean Ekwele
        "GRD", // Greek Drachma
        "GTQ", // Guatemalan Quetzal
        "GWE", // Portuguese Guinea Escudo
        "GWP", // Guinea-Bissau Peso
        "GYD", // Guyanaese Dollar
        "HKD", // Hong Kong Dollar
        "HNL", // Honduran Lempira
        "HRD", // Croatian Dinar
        "HRK", // Croatian Kuna
        "HTG", // Haitian Gourde
        "HUF", // Hungarian Forint
        "IDR", // Indonesian Rupiah
        "IEP", // Irish Pound
        "ILP", // Israeli Pound
        "ILR", // Israeli Shekel (1980–1985)
        "ILS", // Israeli New Shekel
        "INR", // Indian Rupee
        "IQD", // Iraqi Dinar
        "IRR", // Iranian Rial
        "ISJ", // Icelandic Króna (1918–1981)
        "ISK", // Icelandic Króna
        "ITL", // Italian Lira
        "JMD", // Jamaican Dollar
        "JOD", // Jordanian Dinar
        "JPY", // Japanese Yen
        "KES", // Kenyan Shilling
        "KGS", // Kyrgystani Som
        "KHR", // Cambodian Riel
        "KMF", // Comorian Franc
        "KPW", // North Korean Won
        "KRH", // South Korean Hwan (1953–1962)
        "KRO", // South Korean Won (1945–1953)
        "KRW", // South Korean Won
        "KWD", // Kuwaiti Dinar
        "KYD", // Cayman Islands Dollar
        "KZT", // Kazakhstani Tenge
        "LAK", // Laotian Kip
        "LBP", // Lebanese Pound
        "LKR", // Sri Lankan Rupee
        "LRD", // Liberian Dollar
        "LSL", // Lesotho Loti
        "LTL", // Lithuanian Litas
        "LTT", // Lithuanian Talonas
        "LUC", // Luxembourgian Convertible Franc
        "LUF", // Luxembourgian Franc
        "LUL", // Luxembourg Financial Franc
        "LVL", // Latvian Lats
        "LVR", // Latvian Ruble
        "LYD", // Libyan Dinar
        "MAD", // Moroccan Dirham
        "MAF", // Moroccan Franc
        "MCF", // Monegasque Franc
        "MDC", // Moldovan Cupon
        "MDL", // Moldovan Leu
        "MGA", // Malagasy Ariary
        "MGF", // Malagasy Franc
        "MKD", // Macedonian Denar
        "MKN", // Macedonian Denar (1992–1993)
        "MLF", // Malian Franc
        "MMK", // Myanmar Kyat
        "MNT", // Mongolian Tugrik
        "MOP", // Macanese Pataca
        "MRO", // Mauritanian Ouguiya (1973–2017)
        "MRU", // Mauritanian Ouguiya
        "MTL", // Maltese Lira
        "MTP", // Maltese Pound
        "MUR", // Mauritian Rupee
        "MVP", // Maldivian Rupee (1947–1981)
        "MVR", // Maldivian Rufiyaa
        "MWK", // Malawian Kwacha
        "MXN", // Mexican Peso
        "MXP", // Mexican Silver Peso (1861–1992)
        "MXV", // Mexican Investment Unit
        "MYR", // Malaysian Ringgit
        "MZE", // Mozambican Escudo
        "MZM", // Mozambican Metical (1980–2006)
        "MZN", // Mozambican Metical
        "NAD", // Namibian Dollar
        "NGN", // Nigerian Naira
        "NIC", // Nicaraguan Córdoba (1988–1991)
        "NIO", // Nicaraguan Córdoba
        "NLG", // Dutch Guilder
        "NOK", // Norwegian Krone
        "NPR", // Nepalese Rupee
        "NZD", // New Zealand Dollar
        "OMR", // Omani Rial
        "PAB", // Panamanian Balboa
        "PEI", // Peruvian Inti
        "PEN", // Peruvian Sol
        "PES", // Peruvian Sol (1863–1965)
        "PGK", // Papua New Guinean Kina
        "PHP", // Philippine Peso
        "PKR", // Pakistani Rupee
        "PLN", // Polish Zloty
        "PLZ", // Polish Zloty (1950–1995)
        "PTE", // Portuguese Escudo
        "PYG", // Paraguayan Guarani
        "QAR", // Qatari Riyal
        "RHD", // Rhodesian Dollar
        "ROL", // Romanian Leu (1952–2006)
        "RON", // Romanian Leu
        "RSD", // Serbian Dinar
        "RUB", // Russian Ruble
        "RUR", // Russian Ruble (1991–1998)
        "RWF", // Rwandan Franc
        "SAR", // Saudi Riyal
        "SBD", // Solomon Islands Dollar
        "SCR", // Seychellois Rupee
        "SDD", // Sudanese Dinar (1992–2007)
        "SDG", // Sudanese Pound
        "SDP", // Sudanese Pound (1957–1998)
        "SEK", // Swedish Krona
        "SGD", // Singapore Dollar
        "SHP", // St. Helena Pound
        "SIT", // Slovenian Tolar
        "SKK", // Slovak Koruna
        "SLE", // Sierra Leonean Leone
        "SLL", // Sierra Leonean Leone (1964—2022)
        "SOS", // Somali Shilling
        "SRD", // Surinamese Dollar
        "SRG", // Surinamese Guilder
        "SSP", // South Sudanese Pound
        "STD", // São Tomé & Príncipe Dobra (1977–2017)
        "STN", // São Tomé & Príncipe Dobra
        "SUR", // Soviet Rouble
        "SVC", // Salvadoran Colón
        "SYP", // Syrian Pound
        "SZL", // Swazi Lilangeni
        "THB", // Thai Baht
        "TJR", // Tajikistani Ruble
        "TJS", // Tajikistani Somoni
        "TMM", // Turkmenistani Manat (1993–2009)
        "TMT", // Turkmenistani Manat
        "TND", // Tunisian Dinar
        "TOP", // Tongan Paʻanga
        "TPE", // Timorese Escudo
        "TRL", // Turkish Lira (1922–2005)
        "TRY", // Turkish Lira
        "TTD", // Trinidad & Tobago Dollar
        "TWD", // New Taiwan Dollar
        "TZS", // Tanzanian Shilling
        "UAH", // Ukrainian Hryvnia
        "UAK", // Ukrainian Karbovanets
        "UGS", // Ugandan Shilling (1966–1987)
        "UGX", // Ugandan Shilling
        "USD", // US Dollar
        "USN", // US Dollar (Next day)
        "USS", // US Dollar (Same day)
        "UYI", // Uruguayan Peso (Indexed Units)
        "UYP", // Uruguayan Peso (1975–1993)
        "UYU", // Uruguayan Peso
        "UYW", // Uruguayan Nominal Wage Index Unit
        "UZS", // Uzbekistani Som
        "VEB", // Venezuelan Bolívar (1871–2008)
        "VED", // Bolívar Soberano
        "VEF", // Venezuelan Bolívar (2008–2018)
        "VES", // Venezuelan Bolívar
        "VND", // Vietnamese Dong
        "VNN", // Vietnamese Dong (1978–1985)
        "VUV", // Vanuatu Vatu
        "WST", // Samoan Tala
        "XAF", // Central African CFA Franc
        "XAG", // Silver
        "XAU", // Gold
        "XBA", // European Composite Unit
        "XBB", // European Monetary Unit
        "XBC", // European Unit of Account (XBC)
        "XBD", // European Unit of Account (XBD)
        "XCD", // East Caribbean Dollar
        "XCG", // Caribbean guilder
        "XDR", // Special Drawing Rights
        "XEU", // European Currency Unit
        "XFO", // French Gold Franc
        "XFU", // French UIC-Franc
        "XOF", // West African CFA Franc
        "XPD", // Palladium
        "XPF", // CFP Franc
        "XPT", // Platinum
        "XRE", // RINET Funds
        "XSU", // Sucre
        "XTS", // Testing Currency Code
        "XUA", // ADB Unit of Account
        "XXX", // Unknown Currency
        "YDD", // Yemeni Dinar
        "YER", // Yemeni Rial
        "YUD", // Yugoslavian Hard Dinar (1966–1990)
        "YUM", // Yugoslavian New Dinar (1994–2002)
        "YUN", // Yugoslavian Convertible Dinar (1990–1992)
        "YUR", // Yugoslavian Reformed Dinar (1992–1993)
        "ZAL", // South African Rand (financial)
        "ZAR", // South African Rand
        "ZMK", // Zambian Kwacha (1968–2012)
        "ZMW", // Zambian Kwacha
        "ZRN", // Zairean New Zaire (1993–1998)
        "ZRZ", // Zairean Zaire (1971–1993)
        "ZWD", // Zimbabwean Dollar (1980–2008)
        "ZWL", // Zimbabwean Dollar (2009)
        "ZWR", // Zimbabwean Dollar (2008)
    )
}
