/*
 * This file is part of the Money package.
 *
 * Copyright (c) Eriksen Costa <eriksencosta@gmail.com>
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

/*
 * This file was auto-generated by running the "generateCirculatingCurrenciesDataClasses" Gradle task. Always run the
 * task after upgrading the ICU library.
 */

package com.eriksencosta.money.currency.circulating.data

import com.eriksencosta.money.currency.CurrencyData

// 50 currencies
@Suppress("MagicNumber", "MaxLineLength", "StringLiteralDuplication")
internal class CurrenciesData5 {
    val currencies: Map<String, CurrencyData> get() = mapOf(
        "SDP" to CurrencyData("SDP", "736", "Sudanese Pound (1957–1998)", "SDP", "HISTORICAL", 2),
        "SHP" to CurrencyData("SHP", "654", "St. Helena Pound", "£", "TENDER", 2),
        "SIT" to CurrencyData("SIT", "705", "Slovenian Tolar", "SIT", "HISTORICAL", 2),
        "SKK" to CurrencyData("SKK", "703", "Slovak Koruna", "SKK", "HISTORICAL", 2),
        "SLE" to CurrencyData("SLE", "925", "Sierra Leonean Leone", "Le", "TENDER", 2),
        "SLL" to CurrencyData("SLL", "694", "Sierra Leonean Leone (1964—2022)", "SLL", "HISTORICAL", 0),
        "SOS" to CurrencyData("SOS", "706", "Somali Shilling", "S", "TENDER", 0),
        "SRD" to CurrencyData("SRD", "968", "Surinamese Dollar", "\$", "TENDER", 2),
        "SRG" to CurrencyData("SRG", "740", "Surinamese Guilder", "SRG", "HISTORICAL", 2),
        "SSP" to CurrencyData("SSP", "728", "South Sudanese Pound", "£", "TENDER", 2),
        "STD" to CurrencyData("STD", "678", "São Tomé & Príncipe Dobra (1977–2017)", "STD", "HISTORICAL", 0),
        "STN" to CurrencyData("STN", "930", "São Tomé & Príncipe Dobra", "Db", "TENDER", 2),
        "SUR" to CurrencyData("SUR", "810", "Soviet Rouble", "SUR", "HISTORICAL", 2),
        "SVC" to CurrencyData("SVC", "222", "Salvadoran Colón", "SVC", "HISTORICAL", 2),
        "SYP" to CurrencyData("SYP", "760", "Syrian Pound", "ل.س.‏", "TENDER", 0),
        "SZL" to CurrencyData("SZL", "748", "Swazi Lilangeni", "E", "TENDER", 2),
        "THB" to CurrencyData("THB", "764", "Thai Baht", "฿", "TENDER", 2),
        "TJR" to CurrencyData("TJR", "762", "Tajikistani Ruble", "TJR", "HISTORICAL", 2),
        "TJS" to CurrencyData("TJS", "972", "Tajikistani Somoni", "сом.", "TENDER", 2),
        "TMM" to CurrencyData("TMM", "795", "Turkmenistani Manat (1993–2009)", "TMM", "HISTORICAL", 0),
        "TMT" to CurrencyData("TMT", "934", "Turkmenistani Manat", "TMT", "TENDER", 2),
        "TND" to CurrencyData("TND", "788", "Tunisian Dinar", "د.ت.‏", "TENDER", 3),
        "TOP" to CurrencyData("TOP", "776", "Tongan Paʻanga", "T\$", "TENDER", 2),
        "TPE" to CurrencyData("TPE", "626", "Timorese Escudo", "TPE", "HISTORICAL", 2),
        "TRL" to CurrencyData("TRL", "792", "Turkish Lira (1922–2005)", "TRL", "HISTORICAL", 0),
        "TTD" to CurrencyData("TTD", "780", "Trinidad & Tobago Dollar", "\$", "TENDER", 2),
        "TZS" to CurrencyData("TZS", "834", "Tanzanian Shilling", "TSh", "TENDER", 2),
        "UAH" to CurrencyData("UAH", "980", "Ukrainian Hryvnia", "₴", "TENDER", 2),
        "UAK" to CurrencyData("UAK", "804", "Ukrainian Karbovanets", "UAK", "HISTORICAL", 2),
        "UGS" to CurrencyData("UGS", "800", "Ugandan Shilling (1966–1987)", "UGS", "HISTORICAL", 2),
        "UGX" to CurrencyData("UGX", "800", "Ugandan Shilling", "USh", "TENDER", 0),
        "USN" to CurrencyData("USN", "997", "US Dollar (Next day)", "USN", "HISTORICAL", 2),
        "USS" to CurrencyData("USS", "998", "US Dollar (Same day)", "USS", "HISTORICAL", 2),
        "UYI" to CurrencyData("UYI", "940", "Uruguayan Peso (Indexed Units)", "UYI", "HISTORICAL", 0),
        "UYP" to CurrencyData("UYP", "858", "Uruguayan Peso (1975–1993)", "UYP", "HISTORICAL", 2),
        "UYU" to CurrencyData("UYU", "858", "Uruguayan Peso", "\$", "TENDER", 2),
        "UYW" to CurrencyData("UYW", "927", "Uruguayan Nominal Wage Index Unit", "UYW", "HISTORICAL", 4),
        "UZS" to CurrencyData("UZS", "860", "Uzbekistani Som", "сўм", "TENDER", 2),
        "VEB" to CurrencyData("VEB", "862", "Venezuelan Bolívar (1871–2008)", "VEB", "HISTORICAL", 2),
        "VED" to CurrencyData("VED", "926", "Bolívar Soberano", "VED", "HISTORICAL", 2),
        "VEF" to CurrencyData("VEF", "937", "Venezuelan Bolívar (2008–2018)", "VEF", "HISTORICAL", 2),
        "VES" to CurrencyData("VES", "928", "Venezuelan Bolívar", "Bs.S", "TENDER", 2),
        "VND" to CurrencyData("VND", "704", "Vietnamese Dong", "₫", "TENDER", 0),
        "VNN" to CurrencyData("VNN", "000", "Vietnamese Dong (1978–1985)", "VNN", "HISTORICAL", 2),
        "VUV" to CurrencyData("VUV", "548", "Vanuatu Vatu", "VT", "TENDER", 0),
        "WST" to CurrencyData("WST", "882", "Samoan Tala", "WS\$", "TENDER", 2),
        "XAF" to CurrencyData("XAF", "950", "Central African CFA Franc", "XAF", "TENDER", 0),
        "XAG" to CurrencyData("XAG", "961", "Silver", "XAG", "OTHER", 2),
        "XAU" to CurrencyData("XAU", "959", "Gold", "XAU", "OTHER", 2),
        "XBA" to CurrencyData("XBA", "955", "European Composite Unit", "XBA", "OTHER", 2),
    )
}
