/*
 * This file is part of the Money package.
 *
 * Copyright (c) Eriksen Costa <eriksencosta@gmail.com>
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

/*
 * This file was auto-generated by running the "generateCirculatingCurrenciesDataClasses" Gradle task. Always run the
 * task after upgrading the ICU library.
 */

package com.eriksencosta.money.currency.circulating.data

import com.eriksencosta.money.currency.findCodeBySecondaryCode

@Suppress("CyclomaticComplexMethod")
internal object CurrenciesLookup {
    private val prioritizedCurrencies = CurrenciesLookup0().currencies

    fun of(code: String): String = prioritizedCurrencies.getOrElse(code) {
        when (code) {
            in "004".."288" -> CurrenciesLookup1().currencies.findCodeBySecondaryCode(code)
            in "292".."620" -> CurrenciesLookup2().currencies.findCodeBySecondaryCode(code)
            in "626".."938" -> CurrenciesLookup3().currencies.findCodeBySecondaryCode(code)
            in "940".."995" -> CurrenciesLookup4().currencies.findCodeBySecondaryCode(code)
            in "996".."999" -> CurrenciesLookup5().currencies.findCodeBySecondaryCode(code)
            else -> ""
        }
    }
}
