/*
 * This file is part of the Money package.
 *
 * Copyright (c) Eriksen Costa <eriksencosta@gmail.com>
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

/*
 * This file was auto-generated by running the "generateCirculatingCurrenciesDataClasses" Gradle task. Always run the
 * task after upgrading the ICU library.
 */

package com.eriksencosta.money.currency.circulating.data

import com.eriksencosta.money.currency.CurrencyData

// 50 currencies
@Suppress("MagicNumber", "MaxLineLength", "StringLiteralDuplication")
internal class CurrenciesData3 {
    val currencies: Map<String, CurrencyData> get() = mapOf(
        "GRD" to CurrencyData("GRD", "300", "Greek Drachma", "GRD", "HISTORICAL", 2),
        "GTQ" to CurrencyData("GTQ", "320", "Guatemalan Quetzal", "Q", "TENDER", 2),
        "GWE" to CurrencyData("GWE", "624", "Portuguese Guinea Escudo", "GWE", "HISTORICAL", 2),
        "GWP" to CurrencyData("GWP", "624", "Guinea-Bissau Peso", "GWP", "HISTORICAL", 2),
        "GYD" to CurrencyData("GYD", "328", "Guyanaese Dollar", "\$", "TENDER", 2),
        "HNL" to CurrencyData("HNL", "340", "Honduran Lempira", "L", "TENDER", 2),
        "HRD" to CurrencyData("HRD", "191", "Croatian Dinar", "HRD", "HISTORICAL", 2),
        "HRK" to CurrencyData("HRK", "191", "Croatian Kuna", "HRK", "HISTORICAL", 2),
        "HTG" to CurrencyData("HTG", "332", "Haitian Gourde", "G", "TENDER", 2),
        "HUF" to CurrencyData("HUF", "348", "Hungarian Forint", "Ft", "TENDER", 2),
        "IEP" to CurrencyData("IEP", "372", "Irish Pound", "IEP", "HISTORICAL", 2),
        "ILP" to CurrencyData("ILP", "376", "Israeli Pound", "ILP", "HISTORICAL", 2),
        "ILR" to CurrencyData("ILR", "376", "Israeli Shekel (1980–1985)", "ILR", "HISTORICAL", 2),
        "ILS" to CurrencyData("ILS", "376", "Israeli New Shekel", "₪", "TENDER", 2),
        "IQD" to CurrencyData("IQD", "368", "Iraqi Dinar", "د.ع.‏", "TENDER", 0),
        "IRR" to CurrencyData("IRR", "364", "Iranian Rial", "ریال", "TENDER", 0),
        "ISJ" to CurrencyData("ISJ", "352", "Icelandic Króna (1918–1981)", "ISJ", "HISTORICAL", 2),
        "ISK" to CurrencyData("ISK", "352", "Icelandic Króna", "kr.", "TENDER", 0),
        "ITL" to CurrencyData("ITL", "380", "Italian Lira", "ITL", "HISTORICAL", 0),
        "JMD" to CurrencyData("JMD", "388", "Jamaican Dollar", "\$", "TENDER", 2),
        "JOD" to CurrencyData("JOD", "400", "Jordanian Dinar", "د.أ.‏", "TENDER", 3),
        "KES" to CurrencyData("KES", "404", "Kenyan Shilling", "Ksh", "TENDER", 2),
        "KGS" to CurrencyData("KGS", "417", "Kyrgystani Som", "сом", "TENDER", 2),
        "KHR" to CurrencyData("KHR", "116", "Cambodian Riel", "៛", "TENDER", 2),
        "KMF" to CurrencyData("KMF", "174", "Comorian Franc", "CF", "TENDER", 0),
        "KPW" to CurrencyData("KPW", "408", "North Korean Won", "KPW", "TENDER", 0),
        "KRH" to CurrencyData("KRH", "000", "South Korean Hwan (1953–1962)", "KRH", "HISTORICAL", 2),
        "KRO" to CurrencyData("KRO", "000", "South Korean Won (1945–1953)", "KRO", "HISTORICAL", 2),
        "KWD" to CurrencyData("KWD", "414", "Kuwaiti Dinar", "د.ك.‏", "TENDER", 3),
        "KYD" to CurrencyData("KYD", "136", "Cayman Islands Dollar", "\$", "TENDER", 2),
        "KZT" to CurrencyData("KZT", "398", "Kazakhstani Tenge", "₸", "TENDER", 2),
        "LAK" to CurrencyData("LAK", "418", "Laotian Kip", "₭", "TENDER", 0),
        "LBP" to CurrencyData("LBP", "422", "Lebanese Pound", "ل.ل.‏", "TENDER", 0),
        "LKR" to CurrencyData("LKR", "144", "Sri Lankan Rupee", "රු.", "TENDER", 2),
        "LRD" to CurrencyData("LRD", "430", "Liberian Dollar", "\$", "TENDER", 2),
        "LSL" to CurrencyData("LSL", "426", "Lesotho Loti", "LSL", "TENDER", 2),
        "LTL" to CurrencyData("LTL", "440", "Lithuanian Litas", "LTL", "HISTORICAL", 2),
        "LTT" to CurrencyData("LTT", "440", "Lithuanian Talonas", "LTT", "HISTORICAL", 2),
        "LUC" to CurrencyData("LUC", "989", "Luxembourgian Convertible Franc", "LUC", "HISTORICAL", 2),
        "LUF" to CurrencyData("LUF", "442", "Luxembourgian Franc", "LUF", "HISTORICAL", 0),
        "LUL" to CurrencyData("LUL", "988", "Luxembourg Financial Franc", "LUL", "HISTORICAL", 2),
        "LVL" to CurrencyData("LVL", "428", "Latvian Lats", "LVL", "HISTORICAL", 2),
        "LVR" to CurrencyData("LVR", "428", "Latvian Ruble", "LVR", "HISTORICAL", 2),
        "LYD" to CurrencyData("LYD", "434", "Libyan Dinar", "د.ل.‏", "TENDER", 3),
        "MAD" to CurrencyData("MAD", "504", "Moroccan Dirham", "د.م.‏", "TENDER", 2),
        "MAF" to CurrencyData("MAF", "000", "Moroccan Franc", "MAF", "HISTORICAL", 2),
        "MCF" to CurrencyData("MCF", "000", "Monegasque Franc", "MCF", "HISTORICAL", 2),
        "MDC" to CurrencyData("MDC", "000", "Moldovan Cupon", "MDC", "HISTORICAL", 2),
        "MDL" to CurrencyData("MDL", "498", "Moldovan Leu", "L", "TENDER", 2),
        "MGA" to CurrencyData("MGA", "969", "Malagasy Ariary", "Ar", "TENDER", 0),
    )
}
