/*
 * This file is part of the Money package.
 *
 * Copyright (c) Eriksen Costa <eriksencosta@gmail.com>
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

/*
 * This file was auto-generated by running the "generateCirculatingCurrenciesDataClasses" Gradle task. Always run the
 * task after upgrading the ICU library.
 */

package com.eriksencosta.money.currency.circulating.data

import com.eriksencosta.money.currency.CurrencyData
import com.eriksencosta.money.currency.UndefinedCurrencyData
import com.eriksencosta.money.currency.findByCode

@Suppress("CyclomaticComplexMethod")
internal object CurrenciesData {
    private val prioritizedCurrencies = CurrenciesData0().currencies

    fun of(code: String): CurrencyData = prioritizedCurrencies.getOrElse(code) {
        when (code) {
            in "ADP".."BUK" -> CurrenciesData1().currencies.findByCode(code)
            in "BWP".."GQE" -> CurrenciesData2().currencies.findByCode(code)
            in "GRD".."MGA" -> CurrenciesData3().currencies.findByCode(code)
            in "MGF".."SDG" -> CurrenciesData4().currencies.findByCode(code)
            in "SDP".."XBA" -> CurrenciesData5().currencies.findByCode(code)
            in "XBB".."ZWR" -> CurrenciesData6().currencies.findByCode(code)
            else -> UndefinedCurrencyData(code)
        }
    }
}
