/*
 * This file is part of the Money package.
 *
 * Copyright (c) Eriksen Costa <eriksencosta@gmail.com>
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

/*
 * This file was auto-generated by running the "generateCirculatingCurrenciesDataClasses" Gradle task. Always run the
 * task after upgrading the ICU library.
 */

package com.eriksencosta.money.currency.circulating.data

// 50 currencies
@Suppress("StringLiteralDuplication")
internal class CurrenciesLookup3 {
    val currencies: Map<String, String> get() = mapOf(
        "626" to "TPE", // Timorese Escudo available in CurrenciesData5
        "634" to "QAR", // Qatari Riyal available in CurrenciesData4
        "642" to "ROL", // Romanian Leu (1952–2006) available in CurrenciesData4
        "646" to "RWF", // Rwandan Franc available in CurrenciesData4
        "654" to "SHP", // St. Helena Pound available in CurrenciesData5
        "678" to "STD", // São Tomé & Príncipe Dobra (1977–2017) available in CurrenciesData5
        "690" to "SCR", // Seychellois Rupee available in CurrenciesData4
        "694" to "SLL", // Sierra Leonean Leone (1964—2022) available in CurrenciesData5
        "703" to "SKK", // Slovak Koruna available in CurrenciesData5
        "704" to "VND", // Vietnamese Dong available in CurrenciesData5
        "705" to "SIT", // Slovenian Tolar available in CurrenciesData5
        "706" to "SOS", // Somali Shilling available in CurrenciesData5
        "720" to "YDD", // Yemeni Dinar available in CurrenciesData6
        "724" to "ESP", // Spanish Peseta available in CurrenciesData2
        "728" to "SSP", // South Sudanese Pound available in CurrenciesData5
        "740" to "SRG", // Surinamese Guilder available in CurrenciesData5
        "748" to "SZL", // Swazi Lilangeni available in CurrenciesData5
        "760" to "SYP", // Syrian Pound available in CurrenciesData5
        "762" to "TJR", // Tajikistani Ruble available in CurrenciesData5
        "764" to "THB", // Thai Baht available in CurrenciesData5
        "776" to "TOP", // Tongan Paʻanga available in CurrenciesData5
        "780" to "TTD", // Trinidad & Tobago Dollar available in CurrenciesData5
        "784" to "AED", // United Arab Emirates Dirham available in CurrenciesData1
        "788" to "TND", // Tunisian Dinar available in CurrenciesData5
        "792" to "TRL", // Turkish Lira (1922–2005) available in CurrenciesData5
        "795" to "TMM", // Turkmenistani Manat (1993–2009) available in CurrenciesData5
        "804" to "UAK", // Ukrainian Karbovanets available in CurrenciesData5
        "807" to "MKD", // Macedonian Denar available in CurrenciesData4
        "818" to "EGP", // Egyptian Pound available in CurrenciesData2
        "834" to "TZS", // Tanzanian Shilling available in CurrenciesData5
        "860" to "UZS", // Uzbekistani Som available in CurrenciesData5
        "862" to "VEB", // Venezuelan Bolívar (1871–2008) available in CurrenciesData5
        "882" to "WST", // Samoan Tala available in CurrenciesData5
        "886" to "YER", // Yemeni Rial available in CurrenciesData6
        "894" to "ZMK", // Zambian Kwacha (1968–2012) available in CurrenciesData6
        "925" to "SLE", // Sierra Leonean Leone available in CurrenciesData5
        "926" to "VED", // Bolívar Soberano available in CurrenciesData5
        "927" to "UYW", // Uruguayan Nominal Wage Index Unit available in CurrenciesData5
        "928" to "VES", // Venezuelan Bolívar available in CurrenciesData5
        "929" to "MRU", // Mauritanian Ouguiya available in CurrenciesData4
        "930" to "STN", // São Tomé & Príncipe Dobra available in CurrenciesData5
        "931" to "CUC", // Cuban Convertible Peso available in CurrenciesData2
        "932" to "ZWL", // Zimbabwean Dollar (2009) available in CurrenciesData6
        "933" to "BYN", // Belarusian Ruble available in CurrenciesData2
        "934" to "TMT", // Turkmenistani Manat available in CurrenciesData5
        "935" to "ZWR", // Zimbabwean Dollar (2008) available in CurrenciesData6
        "936" to "GHS", // Ghanaian Cedi available in CurrenciesData2
        "937" to "VEF", // Venezuelan Bolívar (2008–2018) available in CurrenciesData5
        "938" to "SDG", // Sudanese Pound available in CurrenciesData4
        "940" to "UYI", // Uruguayan Peso (Indexed Units) available in CurrenciesData5
    )
}
