name: Security scan

on:
  push:
    branches: [ "*" ]
    tags:
      - "v[0-9]+.[0-9]+.[0-9]+"
      - "v[0-9]+.[0-9]+.[0-9]+-**"
  pull_request:
    branches: [ "*" ]
  schedule:
    - cron: "0 0,8,16 * * *"

concurrency:
  group: ${{ github.workflow }}-${{ github.head_ref || github.ref_name || github.ref || github.run_id }}
  cancel-in-progress: true

permissions:
  contents: read

env:
  CODACY_ENABLE: yes

jobs:
  security-scan:
    name: Codacy Security Scan
    runs-on: ubuntu-latest
    permissions:
      contents: read
      security-events: write
      actions: read

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Run Codacy Analysis CLI
        uses: codacy/codacy-analysis-cli-action@v4
        if: env.CODACY_ENABLE == 'yes'
        with:
          project-token: ${{ secrets.CODACY_PROJECT_TOKEN }}
          verbose: true
          output: results.sarif
          format: sarif
          # Adjust severity of non-security issues
          gh-code-scanning-compat: true
          # Force 0 exit code to allow SARIF file generation
          # This will hand over control about PR rejection to the GitHub side
          max-allowed-issues: 2147483647

      - name: Submit SARIF results
        uses: github/codeql-action/upload-sarif@v2
        if: env.CODACY_ENABLE == 'yes'
        with:
          sarif_file: results.sarif
